var gtdThreadListDownloadProgress=giUIObject.extend({el:null,_loadbox:null,_threadContainer:null,_eventsContainer:null,connect:function(main){giLogger.log("st","gtdThreadListDownloadProgress.connect",main?main.pageId:giLogger.UNKNOWN_PAGE_ID);this.base(main);this._eventsContainer=new giEventsContainer(this);var doc=main.gmail.canvasDocument;this.el=doc.createElement("DIV");this.el.id="gtdi-threadlist-downloadprogress";this._loadbox={loading:{},partialComplete:{}};this._loadbox.loading.el=doc.createElement("DIV");
this._loadbox.loading.el.style.display="none";this._loadbox.loading.el.className="gtdi-loadingbox";this._loadbox.loading.el.innerHTML="<img src='"+giUrl.getURL("skin/indicator_small.gif")+"'/><div>"+giI18N.getString("ThreadList.Loadbox.loading").replace("%1","<span></span>").replace("%2","<span></span>")+"</div>";this._loadbox.loading.elCurrent=this._loadbox.loading.el.getElementsByTagName("SPAN")[0];this._loadbox.loading.elTotal=this._loadbox.loading.el.getElementsByTagName("SPAN")[1];this.el.appendChild(this._loadbox.loading.el);
this._loadbox.partialComplete.el=doc.createElement("DIV");this._loadbox.partialComplete.el.className="gtdi-loadingbox";this._loadbox.partialComplete.el.style.display="none";this._loadbox.partialComplete.el.innerHTML=giI18N.getString("ThreadList.Loadbox.partialComplete").replace("%1","<span></span>").replace("%2","<span></span>");this._loadbox.partialComplete.elCurrent=this._loadbox.partialComplete.el.getElementsByTagName("SPAN")[0];this._loadbox.partialComplete.elTotal=this._loadbox.partialComplete.el.getElementsByTagName("SPAN")[1];
this._loadbox.partialComplete.elDownload=doc.createElement("A");this._loadbox.partialComplete.elDownload.className="gtdi-downloadall";this._loadbox.partialComplete.elDownload.href="#";this._loadbox.partialComplete.elDownload.innerHTML=giI18N.getString("ThreadList.Loadbox.partialComplete.all");this._loadbox.partialComplete.el.appendChild(this._loadbox.partialComplete.elDownload);this.el.appendChild(this._loadbox.partialComplete.el);this._eventsContainer.observe(this.el,"click",this._click,false)},
disconnect:function(){if(this.el&&this.el.parentNode)this.el.parentNode.removeChild(this.el);this.el=null;this._unhookThreadContainer();this._eventsContainer.reset();this._eventsContainer=null;this.base()},_unhookThreadContainer:function(){if(this._threadContainer){this._threadContainer.removeEventListener(glThreadContainer.NEW_SEARCH,this._newSearch,this);this._threadContainer.removeEventListener(glThreadContainer.LOADED,this._loadComplete,this);this._threadContainer.removeEventListener(glThreadContainer.LOADING_UPDATE,
this._loadingUpdate,this);this._threadContainer=null}},setThreadContainer:function(threadContainer){this._unhookThreadContainer();this._threadContainer=threadContainer;if(this._threadContainer){this._threadContainer.addEventListener(glThreadContainer.NEW_SEARCH,this._newSearch,this);this._threadContainer.addEventListener(glThreadContainer.LOADED,this._loadComplete,this);this._threadContainer.addEventListener(glThreadContainer.LOADING_UPDATE,this._loadingUpdate,this);this._refresh()}},_refresh:function(){if(this._threadContainer.isSearching()){this._loadbox.partialComplete.el.style.display=
"none";var upto=this._threadContainer.threads.length+25;var total=this._threadContainer.getNumberThreads(glThreadContainer.COUNT_TOTAL_DESIRED);if(this._threadContainer.getNumberThreads(glThreadContainer.COUNT_TOTAL_CALCULATED)<total)total=this._threadContainer.getNumberThreads(glThreadContainer.COUNT_TOTAL_CALCULATED);if(upto>total)upto=total;this._loadbox.loading.elCurrent.innerHTML=this._threadContainer.threads.length+"-"+upto;this._loadbox.loading.elTotal.innerHTML=total;this._loadbox.loading.el.style.display=
""}else if(this._threadContainer.isComplete())this.el.style.display="none";else{this._loadbox.partialComplete.elCurrent.innerHTML=this._threadContainer.threads.length;this._loadbox.partialComplete.elTotal.innerHTML=this._threadContainer.getNumberThreads(glThreadContainer.COUNT_TOTAL_CALCULATED);this._loadbox.partialComplete.el.style.display="";this._loadbox.loading.el.style.display="none";this.el.style.display=""}},_newSearch:function(event){this._refresh()},_loadingUpdate:function(event){this._refresh()},
_loadComplete:function(event){this._refresh()},_click:function(evt){try{var el=evt.target;if(el.className=="gtdi-downloadall")this._threadContainer.search()}catch(e){giLogger.warn(e,"gtdThreadListDownloadProgress._click",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}}});
