var gtdThreadList=giUIObject.extend({el:null,_elInner:null,_elGroupByContainer:null,_elActionsBar:null,_eventsContainer:null,_threadsHash:null,_groupBys:null,_groups:null,_groupsHash:null,_threadContainer:null,_threadListDownloadProgress:null,connect:function(main){giLogger.log("st","gtdThreadList.connect",main?main.pageId:giLogger.UNKNOWN_PAGE_ID);this.base(main);this._eventsContainer=new giEventsContainer(this);this._threadsHash={};this._groups=[];this._groupsHash={};this._groupBys={};var doc=main.gmail.canvasDocument;
this.el=doc.createElement("DIV");this.el.id="gtdi-threads";this.el.setAttribute("gtdi-resizable","1");this._elInner=doc.createElement("DIV");this._elInner.id="gtdi-threadlists";this._elInner.setAttribute("gtdi-remember-scroll","1");this._elInner.setAttribute("gtdi-resizable","1");this.el.appendChild(this._elInner);var elActions=doc.createElement("DIV");elActions.id="gtdi-threadtoolbar";this.el.appendChild(elActions);this._elActionsBar=doc.createElement("DIV");this._elActionsBar.className="gtdi-btns";
elActions.appendChild(this._elActionsBar);this._labelsMenu=this._main.getUIObject("labelsMenu");this._elActionsBar.appendChild(this._labelsMenu.el);this._elGroupByContainer=doc.createElement("DIV");this._elGroupByContainer.className="gtdi-btn-grp gtdi-icons gtdi-threadlist-groupby";this._elActionsBar.appendChild(this._elGroupByContainer);this.addGroupBy(new gtdThreadListGroupByProject(this._main));this.addGroupBy(new gtdThreadListGroupByContext(this._main));this.addGroupBy(new gtdThreadListGroupByContact(this._main));
this.addGroupBy(new gtdThreadListGroupByList(this._main));this.selectGroupBy("project");this._eventsContainer.observe(this.el,"click",this._click,false)},disconnect:function(){if(this._threadContainer){this._threadContainer.removeEventListener(glThreadContainer.CHANGED,this._threadChanged,this);this._threadContainer=null}else this._main.gmail.actions.removeEventListener(glActionManager.THREAD_CHANGED,this._threadChanged,this);if(this._threadListDownloadProgress){this._threadListDownloadProgress.disconnect();
this._threadListDownloadProgress=null}if(this.el&&this.el.parentNode)this.el.parentNode.removeChild(this.el);this.el=null;this._elGroupByContainer=null;this._elActionsBar=null;if(this._labelsMenu){this._labelsMenu.disconnect();this._labelsMenu=null}this._threadsHash=null;for(var i=0;i<this._groups.length;i++)this._groups[i].disconnect();this._groups=null;this._groupsHash=null;this._groupBys=null;this._threadsHash=null;this._eventsContainer.reset();this._eventsContainer=null;this.base()},setThreads:function(threads,
threadContainer){var liteAdd=true;var seenThreads={};added=[];removed=[];for(var i=0;i<threads.length;i++){if(this._threadsHash[threads[i].threadId]);else added.push(threads[i]);seenThreads[threads[i].threadId]=true}for(t in this._threadsHash){liteAdd=false;if(!seenThreads[this._threadsHash[t].threadId])removed.push(this._threadsHash[t])}for(var i=0;i<added.length;i++){this._threadsHash[added[i].threadId]=added[i];this._addThreadToGroups(added[i],liteAdd)}for(var i=0;i<removed.length;i++){for(var j=
0;j<this._groups.length;j++){var group=this._groups[j];group.removeThread(removed[i]);if(group.getNumberThreads()==0){group.disconnect();var pos=this._groups.indexOf(group);this._groups.splice(pos,1);delete this._groupsHash[group.id]}group=null}delete this._threadsHash[removed[i].threadId]}if(liteAdd)for(var i=0;i<this._groups.length;i++)this._groups[i].sort();if(added.length>0||removed.length>0)this.sortGroups();this._testShowNoThreads();if(threadContainer!=this._threadContainer){if(this._threadContainer)this._threadContainer.removeEventListener(glThreadContainer.CHANGED,
this._threadChanged,this);else this._main.gmail.actions.removeEventListener(glActionManager.THREAD_CHANGED,this._threadChanged,this);this._threadContainer=threadContainer;if(this._threadContainer)this._threadContainer.addEventListener(glThreadContainer.CHANGED,this._threadChanged,this);else this._main.gmail.actions.addEventListener(glActionManager.THREAD_CHANGED,this._threadChanged,this)}if(!this._threadListDownloadProgress&&this._threadContainer){this._threadListDownloadProgress=this._main.getUIObject("threadListDownloadProgress");
if(this._elInner.firstChild)this._elInner.insertBefore(this._threadListDownloadProgress.el,this._elInner.firstChild);else this._elInner.appendChild(this._threadListDownloadProgress.el)}if(this._threadListDownloadProgress)this._threadListDownloadProgress.setThreadContainer(this._threadContainer)},_addThreadToGroups:function(thread,lite){var groupIds=this._getActiveGroupBy().data.groupThread(thread);for(var i=0;i<groupIds.length;i++){var group=this._groupsHash[groupIds[i][0]];if(!group)group=this._createGroup(groupIds[i][0],
groupIds[i][1]);group.addThread(thread,lite)}},_createGroup:function(gid,displayName){var group=this._main.getUIObject("threadListGroup");group.load(gid,displayName,this._getActiveGroupBy().data);var browserTypeItem=this._getActiveGroupBy().data.getBrowserTypeAndItem(group);if(browserTypeItem){group.elTitle.setAttribute("gtdi-type",browserTypeItem[0]);group.elTitle.setAttribute("gtdi-item",browserTypeItem[1]);giUIObject.addClassName(group.elTitle,"gtdi-group-has-browser-type")}this._groups.push(group);
this._groupsHash[gid]=group;return group},sortGroups:function(){var groupBy=this._getActiveGroupBy().data;if(groupBy.sortGroups)this._groups.sort(groupBy.sortGroups);for(var i=0;i<this._groups.length;i++){if(this._groups[i].id=="misc"&&i!=this._groups.length-1){this._groups.push(this._groups[i]);this._groups.splice(i,1)}this._elInner.appendChild(this._groups[i].el)}},_threadChanged:function(evt){var threadsChanged=[];if(evt.name==glActionManager.THREAD_CHANGED){var thread=this._threadsHash[evt.thread];
if(thread){thread.updateFromEvent(evt);threadsChanged.push(thread)}}else if(evt.name==glThreadContainer.CHANGED)for(var i=0;i<evt.updatedThreads.length;i++){var thread=this._threadsHash[evt.updatedThreads[i].threadId];if(thread)threadsChanged.push(thread)}for(var i=0;i<threadsChanged.length;i++){var thread=threadsChanged[i];var groupIdsFull=this._getActiveGroupBy().data.groupThread(thread);var groupIds=[];for(var j=0;j<groupIdsFull.length;j++)groupIds.push(groupIdsFull[j][0]);for(var j=0;j<this._groups.length;j++){var group=
this._groups[j];var groupFound=groupIds.indexOf(group.id);var tlThread=group.getThreadListThread(thread);if(tlThread)if(groupFound==-1)group.removeThread(thread);else tlThread.refresh();else if(groupFound>-1)group.addThread(thread);if(groupFound>-1)groupIds.splice(groupFound,1)}for(var j=0;j<groupIds.length;j++){var group=this._createGroup(groupIds[j]);group.addThread(thread)}}if(threadsChanged.length>0)this.sortGroups()},addGroupBy:function(groupBy){var doc=this._main.gmail.canvasDocument;var el=
doc.createElement("DIV");el.setAttribute("gtdi-groupby",groupBy.id);el.className="gtdi-btn";el.innerHTML="<b class='gtdi-btn-t'></b><b class='gtdi-btn-t2'></b><b class='gtdi-btn-m'></b><b class='gtdi-btn-b2'></b><b class='gtdi-btn-b'></b><span class='gtdi-btn-label' title='"+groupBy.displayName+"'><img src='"+groupBy.iconSrc+"' /></span>";this._elGroupByContainer.appendChild(el);this._groupBys[groupBy.id]={id:groupBy.id,data:groupBy,el:el}},_getActiveGroupBy:function(){var elGroupBy=this.el.ownerDocument.evaluate(".//DIV[@gtdi-groupby and contains(@class, 'gtdi-active')]",
this._elGroupByContainer,null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue;if(elGroupBy)return this._groupBys[elGroupBy.getAttribute("gtdi-groupby")]},selectGroupBy:function(id){var currentGroupBy=this._getActiveGroupBy();if(currentGroupBy){if(currentGroupBy.id==id)return;giUIObject.removeClassName(currentGroupBy.el,"gtdi-active")}var doc=this._main.gmail.canvasDocument;var elGroupBy=doc.evaluate(".//*[@gtdi-groupby='"+id+"']",this._elGroupByContainer,null,XPathResult.FIRST_ORDERED_NODE_TYPE,
null).singleNodeValue;if(elGroupBy)giUIObject.addClassName(elGroupBy,"gtdi-active");for(var i=0;i<this._groups.length;i++)this._groups[i].disconnect();this._groups.length=0;this._groupsHash={};for(t in this._threadsHash)this._addThreadToGroups(this._threadsHash[t],true);for(g in this._groups)this._groups[g].sort();this.sortGroups()},_testShowNoThreads:function(){var elNoThreads=this._elInner.ownerDocument.evaluate(".//*[@class='gtdi-no-threads']",this._elInner,null,XPathResult.FIRST_ORDERED_NODE_TYPE,
null).singleNodeValue;if(elNoThreads)elNoThreads.parentNode.removeChild(elNoThreads);var foundThread=false;for(t in this._threadsHash){foundThread=true;break}if(!foundThread){var elNoThreads=this._elInner.ownerDocument.createElement("DIV");elNoThreads.className="gtdi-no-threads";elNoThreads.innerHTML=giI18N.getString("ThreadList.NoThreads");this._elInner.appendChild(elNoThreads)}},getCheckedThreads:function(){var checkedThreads=[];for(g in this._groups){var groupThreads=this._groups[g].getThreads();
for(var i=0;i<groupThreads.length;i++)if(groupThreads[i].isChecked()&&checkedThreads.indexOf(groupThreads[i].thread)==-1)checkedThreads.push(groupThreads[i].thread)}return checkedThreads},_click:function(event){try{var el=event.target;var thread=this._getThreadFromEl(el);while(el.parentNode&&el!=this.el){if(el.getAttribute("gtdi-groupby")){this.selectGroupBy(el.getAttribute("gtdi-groupby"));break}else if(el.className=="gtdi-labelremove"){var labelname=el.parentNode.getAttribute("gtdi-labelname");
this._main.gmail.actions.performAction(glActionManager.REMOVE_LABEL,thread,null,labelname);break}else if(el.nodeName=="INPUT"){if(this._labelsMenu){var checkedThreads=this.getCheckedThreads();this._labelsMenu.loadThreads(checkedThreads)}if(this.hasEventListener(gtdThreadList.CHECK_THREAD))this.dispatchEvent({name:gtdThreadList.CHECK_THREAD,thread:thread,checked:el.checked});break}else if(el.className=="gtdi-open-in-gmail"){this.dispatchEvent({name:gtdBrowser.LOAD_TYPE,item:thread,newWindow:event.shiftKey,
openInGmail:true,type:gtdBrowser.TYPES.THREAD});break}else if(thread&&el.parentNode==this.el){var threads=[];for(g in this._groups){var groupThreads=this._groups[g].getThreads();for(var i=0;i<groupThreads.length;i++)threads.push(groupThreads[i].thread)}this.dispatchEvent({name:gtdBrowser.LOAD_TYPE,threads:threads,item:thread,type:gtdBrowser.TYPES.THREAD});break}el=el.parentNode}}catch(e){giLogger.warn(e,"gtdThreadList._click",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}},_getThreadFromEl:function(el){while(el.parentNode&&
el!=this.el&&!el.getAttribute("gtdi-thread-id"))el=el.parentNode;if(el.getAttribute("gtdi-thread-id"))return this._threadsHash[el.getAttribute("gtdi-thread-id")]},setServerActionType:function(type){this._labelsMenu.setServerActionType(type)}},{CHECK_THREAD:"check_thread"});gtdThreadList.implement(giEventDispatcher);
