var gtdThreadListThread=giUIObject.extend({el:null,_elCheckbox:null,_elSubject:null,_elSnippet:null,_elPeople:null,_elAttachment:null,_elDate:null,_elLabels:null,thread:null,connect:function(main){giLogger.log("st","gtdThreadListThread.connect",main?main.pageId:giLogger.UNKNOWN_PAGE_ID);this.base(main);var doc=main.gmail.canvasDocument;this.el=doc.createElement("TABLE");this.el.setAttribute("width","100%");this.el.className="gtdi-threadlist-thread";var elTr=doc.createElement("TR");this.el.appendChild(elTr);
var elTd=doc.createElement("TD");elTd.className="gtdi-threadlist-thread-colfirst";elTd.setAttribute("width","140");elTr.appendChild(elTd);this._elCheckbox=doc.createElement("INPUT");this._elCheckbox.setAttribute("type","checkbox");this._elCheckbox.className="gtdi-selectthread";elTd.appendChild(this._elCheckbox);this._elPeople=doc.createElement("SPAN");this._elPeople.className="gtdi-people";elTd.appendChild(this._elPeople);var elTd=doc.createElement("TD");elTd.className="gtdi-threadlist-thread-colmiddle";
elTr.appendChild(elTd);var elSubjectContainer=doc.createElement("DIV");elSubjectContainer.className="gtdi-threadlist-thread-subjectcontainer";elTd.appendChild(elSubjectContainer);this._elSubject=doc.createElement("SPAN");this._elSubject.className="gtdi-subjectline";elSubjectContainer.appendChild(this._elSubject);this._elSnippet=doc.createElement("SPAN");this._elSnippet.className="gtdi-snippet";elSubjectContainer.appendChild(this._elSnippet);var elTd=doc.createElement("TD");elTd.className="gtdi-threadlist-thread-collast";
elTr.appendChild(elTd);this._elAttachment=doc.createElement("IMG");this._elAttachment.src=giUrl.getURL("skin/gtd/i/gtdi-attachment.png");this._elAttachment.title=giI18N.getString("ThreadList.ThreadAttachment.title");elTd.appendChild(this._elAttachment);this._elDate=doc.createElement("SPAN");this._elDate.className="gtdi-date";elTd.appendChild(this._elDate);var elPopout=doc.createElement("IMG");elPopout.src=giUrl.getURL("skin/gtd/goto.png");elPopout.className="gtdi-open-in-gmail";elPopout.title=giI18N.getString("Browser.Popup.openInGmail");
elTd.appendChild(elPopout);var elTr=doc.createElement("TR");this.el.appendChild(elTr);var elTd=doc.createElement("TD");elTd.className="gtdi-threadlist-thread-colfirst";elTr.appendChild(elTd);var elTd=doc.createElement("TD");elTd.setAttribute("colspan","2");elTd.className="gtdi-labels";elTr.appendChild(elTd);this._elLabels=elTd},load:function(thread){this.el.setAttribute("gtdi-thread-id",thread.threadId);this.thread=thread;this.refresh()},refresh:function(){this._elSubject.title=giUtil.decodeEntities(this.thread.subjectSnippetHtml);
this._elSubject.innerHTML=this._elSubject.title;var snippet=giUtil.decodeEntities(giUtil.stripTags(this.thread.bodySnippetHtml));this._elSnippet.title=snippet;this._elSnippet.innerHTML=snippet?"- "+snippet:"";this._elPeople.innerHTML=this.thread.contactsSnippetHtml?this.thread.contactsSnippetHtml.replace("<b>","").replace("</b>",""):"";var dateSnippetHtml=giUtil.stripTags(this.thread.dateSnippetHtml);this._elDate.innerHTML=dateSnippetHtml;if(/\d+\/\d+\/\d+/.test(dateSnippetHtml))this._elDate.style.color=
"rgb(153,46,40)";else if(/\d+\s\w+/i.test(dateSnippetHtml)){var now=new Date;var d=new Date(dateSnippetHtml+" "+now.getFullYear());var age=now.valueOf()-d.valueOf();if(age<1728E5)this._elDate.style.color="rgb(0,0,0)";else if(age<6048E5)this._elDate.style.color="rgb(193, 125, 0)";else this._elDate.style.color="rgb(153,46,40)"}else this._elDate.style.color="rgb(0,0,0)";if(this.thread.attachmentsCSV){this._elAttachment.style.display="";this._elAttachment.title=this.thread.attachmentsCSV}else this._elAttachment.style.display=
"none";if(this.thread.isRead)giUIObject.removeClassName(this.el,"gtdi-unread");else giUIObject.addClassName(this.el,"gtdi-unread");var doc=this._main.gmail.canvasDocument;var labels=this.thread.labels;this._elLabels.innerHTML="";var statusEls=[];var projectEls=[];var otherEls=[];var typeSettings=null;for(var i=0;i<labels.length;i++){var labelname=labels[i];if(labelname.substr(0,1)!="^"){if(!typeSettings)typeSettings=this._main.prefs.getPref("labels.types");var elLabel=doc.createElement("DIV");elLabel.className=
"gtdi-label";elLabel.setAttribute("gtdLabelName",labelname);elLabel.innerHTML="<span class='gtdi-labelname'>"+labelname+"</span>";if(gtdLabelsData.testPrefix(labelname,typeSettings.statuses.prefix))statusEls.push(elLabel);else if(gtdLabelsData.testPrefix(labelname,typeSettings.projects.prefix))projectEls.push(elLabel);else otherEls.push(elLabel)}}for(var i=0;i<statusEls.length;i++)this._elLabels.appendChild(statusEls[i]);for(var i=0;i<projectEls.length;i++)this._elLabels.appendChild(projectEls[i]);
for(var i=0;i<otherEls.length;i++)this._elLabels.appendChild(otherEls[i]);if(this._elLabels.childNodes.length==0)this._elLabels.innerHTML="&nbsp;"},isChecked:function(){return this._elCheckbox.checked},disconnect:function(full){if(this.el&&this.el.parentNode)this.el.parentNode.removeChild(this.el);this._elLabels.innerHTML="";this.thread=null;if(full)for(p in this){if(this.hasOwnProperty(p))this[p]=null}else gtdThreadListThread.objectPool.push(this)}},{create:function(gtd,thread){var tlThread=null;
if(gtdThreadListThread.objectPool.length>0){tlThread=gtdThreadListThread.objectPool[0];tlThread._elCheckbox.checked=false;gtdThreadListThread.objectPool.splice(0,1)}else tlThread=gtd.getUIObject("threadListThread");tlThread.load(thread);return tlThread},unload:function(){for(var i=0;i<gtdThreadListThread.objectPool.length;i++)gtdThreadListThread.objectPool[i].disconnect(true);gtdThreadListThread.objectPool.length=0},objectPool:[]});
