var gtdDeadlineEventSet=giUIObject.extend({_eventsContainer:null,el:null,_elPrettyDate:null,_elTextBox:null,_elToday:null,_elSave:null,_elLoading:null,_elWarning:null,_elQuickLinks:null,_thread:null,_showWarningTimer:null,_serverActionType:null,_prefix:null,connect:function(main){giLogger.log("st","gtdDeadlineEventSet.connect",main?main.pageId:giLogger.UNKNOWN_PAGE_ID);this.base(main);this._eventsContainer=new giEventsContainer(this);this._prefix=this._main.prefs.getPref("labels.types.deadlines.prefix");
this._threads=[];var doc=this._main.gmail.canvasDocument;this.el=doc.createElement("DIV");this.el.className="gtdi-deadlineeventset";var elDeadlineContainer=doc.createElement("DIV");elDeadlineContainer.className="gtdi-deadlineeventset-deadlinecontainer";this.el.appendChild(elDeadlineContainer);var elDeadlineSubContainer=doc.createElement("DIV");elDeadlineSubContainer.className="gtdi-deadlineeventset-deadlinesubcontainer";elDeadlineContainer.appendChild(elDeadlineSubContainer);var elDeadlineIntro=doc.createElement("DIV");
elDeadlineIntro.className="gtdi-deadlineeventset-deadlineintro";elDeadlineIntro.innerHTML=giI18N.getString("Deadline.Intro")+":";elDeadlineSubContainer.appendChild(elDeadlineIntro);var elDeadlineDateContainer=doc.createElement("DIV");elDeadlineDateContainer.className="gtdi-deadlineeventset-deadlinedatecontainer";elDeadlineSubContainer.appendChild(elDeadlineDateContainer);this._elPrettyDate=doc.createElement("SPAN");this._elPrettyDate.value=giI18N.getString("Deadline.PrettyDate.none");elDeadlineDateContainer.appendChild(this._elPrettyDate);
this._elTextBox=doc.createElement("INPUT");this._elTextBox.setAttribute("type","textbox");this._elTextBox.value=giI18N.getString("Deadline.DefaultDate");elDeadlineDateContainer.appendChild(this._elTextBox);this._elLoading=doc.createElement("SPAN");this._elLoading.innerHTML="<img src='"+giUrl.getURL("skin/loader.gif")+"'/>";this._elLoading.style.display="none";elDeadlineSubContainer.appendChild(this._elLoading);this._elSave=doc.createElement("BUTTON");this._elSave.innerHTML=giI18N.getString("Deadline.Save");
elDeadlineSubContainer.appendChild(this._elSave);this._elToday=doc.createElement("SPAN");this._elToday.className="gtdi-deadlineeventset-deadlinesubcontainer-today";this._elToday.innerHTML=giI18N.getString("Deadline.Today");elDeadlineSubContainer.appendChild(this._elToday);this._elWarning=doc.createElement("DIV");this._elWarning.className="gtdi-deadlineeventset-deadlinewarning";this._elWarning.style.display="none";elDeadlineContainer.appendChild(this._elWarning);this._elQuickLinks=doc.createElement("DIV");
this._elQuickLinks.className="gtdi-deadlineeventset-deadlinequicklinks";elDeadlineContainer.appendChild(this._elQuickLinks);var quickLinks=[[giI18N.getString("Deadline.QuickLinks.none"),"none"],["1 "+giI18N.getString("Deadline.QuickLinks.day.singular"),1],["2 "+giI18N.getString("Deadline.QuickLinks.day.plural"),2],["1 "+giI18N.getString("Deadline.QuickLinks.week.singular"),7]];for(var i=0;i<quickLinks.length;i++){var link=quickLinks[i];var elQuickLink=doc.createElement("SPAN");elQuickLink.setAttribute("gtdi-deadlineeventset-quicklink-days",
link[1]);elQuickLink.innerHTML=link[0];this._elQuickLinks.appendChild(elQuickLink)}var elEventContainer=doc.createElement("DIV");elEventContainer.className="gtdi-deadlineeventset-eventcontainer";this.el.appendChild(elEventContainer);this._eventsContainer.observe(this.el,"click",this._click,false);this._eventsContainer.observe(this._elTextBox,"mousedown",this._userSelectTextBox,false);this._eventsContainer.observe(this._elTextBox,"mouseup",this._userInput,false);this._eventsContainer.observe(this._elTextBox,
"keyup",this._userInput,false);this._main.gmail.actions.addEventListener(glActionManager.THREAD_CHANGED,this._threadChanged,this)},disconnect:function(){if(this._showWarningTimer){clearTimeout(this._showWarningTimer);this._showWarningTimer=null}if(this._thread)this._thread.removeEventListener(glThread.THREAD_LOADED,this._loadThread,this);this._main.gmail.actions.removeEventListener(glActionManager.THREAD_CHANGED,this._threadChanged,this);if(this.el&&this.el.parentNode)this.el.parentNode.removeChild(this.el);
this.el=null;for(p in this)if(this[p]&&this[p].nodeName&&this[p].nodeType)this[p]=null;this._eventsContainer.reset();this._eventsContainer=null;this.base()},init:function(actionBox){this._actionBox=actionBox;this._actionBox.addRow("deadlines",this.el)},load:function(thread){if(this._thread)this._thread.removeEventListener(glThread.THREAD_LOADED,this._loadThread,this);this._thread=thread;this._thread.addEventListener(glThread.THREAD_LOADED,this._loadThread,this);this._loadThread()},_loadThread:function(){this._testThreadDeadline()},
_testThreadDeadline:function(){var date=this._getDateFromThread();if(date.isValid){this._elSave.disabled=true;this._elTextBox.disabled=false;this._elLoading.style.display="none";this._elWarning.style.display="none";var today=new Date;if(date.day>0){this._elPrettyDate.innerHTML=giI18N.getString("Deadline.PrettyDate.month."+date.month)+" "+date.day;this._elTextBox.value=date.month+"/"+date.day;if(date.day==today.getDate()&&date.month==today.getMonth()+1)giUIObject.addClassName(this._elToday,"gtdi-active");
else giUIObject.removeClassName(this._elToday,"gtdi-active")}else{giUIObject.removeClassName(this._elToday,"gtdi-active");this._elPrettyDate.innerHTML=giI18N.getString("Deadline.PrettyDate.none");this._elTextBox.value=giI18N.getString("Deadline.DefaultDate")}var quickLinks=this._elQuickLinks.ownerDocument.evaluate(".//*[@gtdi-deadlineeventset-quicklink-days]",this._elQuickLinks,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null);for(var i=0;i<quickLinks.snapshotLength;i++){var elQuickLink=quickLinks.snapshotItem(i);
giUIObject.removeClassName(elQuickLink,"gtdi-active");var days=elQuickLink.getAttribute("gtdi-deadlineeventset-quicklink-days");if(days=="none"&&date.day==0)giUIObject.addClassName(elQuickLink,"gtdi-active");else{var futureDate=new Date(today.valueOf()+1E3*60*60*24*parseInt(days));if(futureDate.getMonth()+1==date.month&&futureDate.getDate()==date.day)giUIObject.addClassName(elQuickLink,"gtdi-active")}}this._lastTextBoxValue=this._elTextBox.value}else if(!this._showWarningTimer){var me=this;this._showWarningTimer=
setTimeout(function(){me._showWarning()},2E3)}},_showWarning:function(){this._showWarningTimer=null;var date=this._getDateFromThread();if(!date.isValid){this._elTextBox.disabled=false;this._elSave.disabled=false;this._elWarning.innerHTML="Deadline only partially set.";this._elWarning.style.display=""}},_getDateFromThread:function(){var date={day:0,month:0};var hasDeadline=false;for(var i=0;i<this._thread.labels.length;i++){var label=this._thread.labels[i].toLowerCase();if(label==this._prefix.toLowerCase()+
"deadline")hasDeadline=true;if(label.indexOf(this._prefix.toLowerCase()+"m/")==0)date.month=parseInt(label.substr(4));if(label.indexOf(this._prefix.toLowerCase()+"d/")==0)date.day=parseInt(label.substr(4))}if(hasDeadline&&date.day>0&&date.day<32&&date.month>0&&date.month<13)date.isValid=true;else if(date.day!=0||date.month!=0||hasDeadline)date.isValid=false;else date.isValid=true;return date},_threadChanged:function(evt){if(evt.action==glActionManager.ADD_LABEL||evt.action==glActionManager.REMOVE_LABEL)if(evt.label.indexOf(this._prefix)==
0){this._thread.updateFromEvent(evt);this._testThreadDeadline()}},_save:function(ignoreSaveButton){try{if(!ignoreSaveButton&&this._elSave.disabled)return;var date=gtdDeadlineEventSet.getDateFromTextBox(this._elTextBox.value);if(!date.isValid){alert(giI18N.getString("Deadline.invalidInput"));return}var currentDate=this._getDateFromThread();if(date.day==currentDate.day&&date.month==currentDate.month)return;this._elSave.disabled=true;this._elTextBox.disabled=true;this._elLoading.style.display="";if(date.day>
0)var toAdd=[this._main.labelsData.getDeadlineLabel(),this._main.labelsData.getDeadlineMonth(date.month),this._main.labelsData.getDeadlineDay(date.day)];else var toAdd=[];var me=this;for(var i=toAdd.length-1;i>=0;i--)if(!this._main.labelsData.hasLabel(toAdd[i])){var label=toAdd[i];this._main.gmail.actions.performAction(glActionManager.ADD_LABEL,null,glActionManager.USE_DOM,label,this._actionsHeader);setTimeout(function(){me._main.gmail.actions.performAction(glActionManager.HIDE_LABEL,null,glActionManager.USE_AJAX,
label)},2E3)}var prefix=this._main.prefs.getPref("labels.types.deadlines.prefix");var fLabelTest=function(label,state){if((idx=toAdd.indexOf(label))>-1){toAdd.splice(idx,1);return 2}else if(label.indexOf(prefix)==0)return 0;return-1};this._main.gmail.actions.actionDOMBuffer.bulkLabel(this._actionsHeader,fLabelTest);for(var i=0;i<toAdd.length;i++){var label=toAdd[i];this._main.gmail.actions.performAction(glActionManager.ADD_LABEL,null,glActionManager.USE_DOM,label,this._actionsHeader);setTimeout(function(){me._main.gmail.actions.performAction(glActionManager.HIDE_LABEL,
null,glActionManager.USE_AJAX,label)},2E3)}}catch(e){giLogger.warn(e,"gtdDeadlineEventSet._save",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}},_userSelectTextBox:function(){try{this._elTextBox.focus();this._elTextBox.select()}catch(e){giLogger.warn(e,"gtdDeadlineEventSet._userSelectTextBox",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}},_userInput:function(){try{if(this._lastTextBoxValue!=this._elTextBox.value){var date=gtdDeadlineEventSet.getDateFromTextBox(this._elTextBox.value);
if(date.isValid)this._elSave.disabled=false;else this._elSave.disabled=true}}catch(e){giLogger.warn(e,"gtdDeadlineEventSet._userInput",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}},_click:function(event){try{var el=event.target;var elTree=el;var c=0;while(elTree.parentNode&&++c<5){if(elTree==this._elSave)this._save();else if(elTree==this._elToday)if(giUIObject.hasClassName(this._elToday,"gtdi-active")){giUIObject.removeClassName(this._elToday,"gtdi-active");this._elTextBox.value="";
this._save(true)}else{giUIObject.addClassName(this._elToday,"gtdi-active");var date=new Date;this._elTextBox.value=date.getMonth()+1+"/"+date.getDate();this._save(true)}else if(elTree==this._elQuickLinks){var days=el.getAttribute("gtdi-deadlineeventset-quicklink-days");if(days=="none"){this._elTextBox.value="";this._save(true)}else{var today=new Date;var futureDate=new Date(today.valueOf()+1E3*60*60*24*days);this._elTextBox.value=futureDate.getMonth()+1+"/"+futureDate.getDate();this._save(true)}}elTree=
elTree.parentNode}}catch(e){giLogger.warn(e,"gtdDeadlineEventSet._click",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}},setServerActionType:function(type){this._serverActionType=type}},{getDateFromTextBox:function(value){var date={day:0,month:0};if(value=="")date.isValid=true;else if(!/^\d+\/\d+$/.test(value))date.isValid=false;else{var splitter=value.split("/");date.month=parseInt(splitter[0]);date.day=parseInt(splitter[1]);if(date.day>0&&date.day<32&&date.month>0&&date.month<13)date.isValid=
true;else date.isValid=false}return date}});
