var giPluginManager=giBase.extend(null,{_plugins:{},_pluginPageInstances:{},_prefs:null,browserName:null,version:"3.0.22.7",loadPage:function(doc,browserName,account,href){for(var i=0;i<giPluginManager._pluginPageInstances.length;i++)if(giPluginManager._pluginPageInstances[i].doc==doc)return;doc._gtdiLoadPage=true;giPluginManager.browserName=browserName;var pageId=(new Date).valueOf().toString()+Math.floor(Math.random()*100+1);try{var url=doc&&doc.defaultView&&doc.defaultView.location?doc.defaultView.location.href:
"not-found";giLogger.log("start load page: "+url+" (top.location.href: "+href+")","giPluginManager.loadPage",pageId);if(!giPluginManager._pluginPageInstances[pageId]){giPluginManager._pluginPageInstances[pageId]={doc:doc,pageId:pageId,loadFailMonitor:null,docFail:null,initialUrl:url};giPluginManager._pluginPageInstances[pageId].loadFailMonitor=new giLoadFailMonitor(pageId)}var elBody=doc.getElementsByTagName("BODY")[0];if(!elBody){giPluginManager.docFail(pageId,doc,"giPluginManager.load.[no-body]",
null);return}if(!account)account=glPageWrapper.getGlobalStatic(doc,pageId,"account");if(account&&giUtil.testEmailAddress(account)){giPluginManager._pluginPageInstances[pageId].account=account;giI18N.load(function(){giPluginManager._loadPagePostI18N(pageId)})}else{giLogger.logConcern("Could not find account for url "+url,"giPluginManager.loadPage",pageId);var globalsUrl=glPageWrapper.getGlobalStatic(doc,pageId,"url");giPluginManager.docFail(pageId,doc,"giPluginManager.load.[no-account]","globalsUrl: "+
globalsUrl)}}catch(e){giLogger.warn(e,"giPluginManager.loadPage",null,pageId)}return pageId},docFail:function(pageId,doc,title,details){var url=doc&&doc.defaultView&&doc.defaultView.location?doc.defaultView.location.href:"not-found";details+="\nurl: "+url;giLogger.warn("GTDInbox load problem due to doc failure: = "+title,"giPluginManager.docFail",details,pageId);var pageData=giPluginManager._pluginPageInstances[pageId];var iframeEls=doc.getElementsByTagName("IFRAME");var iframes=[];for(var i=0;i<
iframeEls.length;i++)iframes.push(iframeEls[i].id);var html="not-found";try{var canvasDocument=doc;var canvasDocumentElement=canvasDocument.documentElement;html=canvasDocumentElement.innerHTML;if(!html)throw new Error("No HTML found in canvasDocumentElement");}catch(e){giLogger.warn("Could not find canvasDocument HTML for doc: "+e,"giPluginManager.docFail","url: "+url,pageId)}pageData.docFail={frameIds:iframes,url:url,html:html}},_loadPagePostI18N:function(pageId){try{giLogger.log("account: "+giPluginManager._pluginPageInstances[pageId].account,
"giPluginManager.loadPage",pageId);if(!giPluginManager._prefs)giPluginManager._prefs=giPrefManager.createInstance();if(giPluginManager._prefs.loaded)giPluginManager._loadPagePostPrefManager(pageId);else giPluginManager._prefs.addEventListener(giPrefManager.LOADED,function(){giPluginManager._loadPagePostPrefManager(pageId)},giPluginManager)}catch(e){giLogger.warn(e,"giPluginManager._loadPagePostI18N",null,pageId)}},_loadPagePostPrefManager:function(pageId){try{var tmpGrace_lastLoginDate=giPluginManager._prefs.getPref(giPluginManager._pluginPageInstances[pageId].account,
"server_account.last_plus_login");var tmpGrace_allow=false;if(tmpGrace_lastLoginDate){var tmpGrace_date=tmpGrace_lastLoginDate;var tmpGrace_dayAgo=(new Date).valueOf()-1E3*60*60*24*2;if(tmpGrace_date>tmpGrace_dayAgo)tmpGrace_allow=true}giPluginManager._pluginPageInstances[pageId].serverAccount=new giServerAccount(pageId,tmpGrace_allow);var passwordHash=giPluginManager._prefs.getPref(giPluginManager._pluginPageInstances[pageId].account,"server_account.password_hash");if(passwordHash){giPluginManager._pluginPageInstances[pageId].loginFunc=
function(evt){giPluginManager._loadPagePostLogin(pageId)};giPluginManager._pluginPageInstances[pageId].serverAccount.addEventListener(giServerAccount.LOADED,giPluginManager._pluginPageInstances[pageId].loginFunc,this);giPluginManager._pluginPageInstances[pageId].serverAccount.load(giPluginManager._pluginPageInstances[pageId].account,passwordHash)}else{giPluginManager._pluginPageInstances[pageId].serverAccount.load(giPluginManager._pluginPageInstances[pageId].account);giPluginManager._loadPagePostLogin(pageId)}}catch(e){giLogger.warn(e,
"giPluginManager._loadPagePostPrefManager",null,pageId)}},_loadPagePostLogin:function(pageId){try{if(giPluginManager._pluginPageInstances[pageId].serverAccount.isRegistered()){giPluginManager._pluginPageInstances[pageId].serverAccount.removeEventListener(giServerAccount.LOADED,giPluginManager._pluginPageInstances[pageId].loginFunc,this);giPluginManager._pluginPageInstances[pageId].loginFunc=null;if(giPluginManager._pluginPageInstances[pageId].serverAccount.getAccountType()==giServerAccount.TYPES.PLUS)giPluginManager._prefs.setPref(giPluginManager._pluginPageInstances[pageId].account,
"server_account.last_plus_login",(new Date).valueOf(),true)}var initializing=false;for(p in giPluginManager._plugins)if(!giPluginManager._plugins[p].initialized){if(!giPluginManager._plugins[p].id||typeof giPluginManager._plugins[p].id=="undefined"){var output=[];output.push("pluginData error for object '"+p+"' (");for(prop in giPluginManager._plugins[p])output.push(prop+": "+giPluginManager._plugins[p][prop]+", ");giLogger.error(output.join(""),"giPluginManager._loadPagePostLogin",pageId)}giPluginManager._initPluginPrefs(pageId,
giPluginManager._plugins[p].id);initializing=true}if(!initializing)giPluginManager._loadPageComplete(pageId)}catch(e){giLogger.warn(e,"giPluginManager._loadPagePostLogin",null,pageId)}},_loadPageComplete:function(pageId){giLogger.log("trying load complete","giPluginManager._loadPageComplete",pageId);try{var pageData=giPluginManager._pluginPageInstances[pageId];for(p in giPluginManager._plugins)if(!giPluginManager._plugins[p].initialized)return;var enabledPlugins=[];var enabledPluginsStr=[];for(p in giPluginManager._plugins){var enabled=
giPluginManager._prefs.getPluginPref(pageData.account,p,"enabled");enabledPluginsStr.push(p+": "+enabled);if(enabled)enabledPlugins.push(giPluginManager._plugins[p])}if(enabledPlugins.length==0)return;giLogger.log("run","giPluginManager._loadPageComplete",pageId);pageBase=new glGmail(pageData.doc,pageId);giLogger.log("create plugins -- "+enabledPluginsStr.join(", "),"giPluginManager._loadPageComplete",pageId);pageData.plugins=[];for(var i=0;i<enabledPlugins.length;i++)try{var pluginInstance=new window[enabledPlugins[i].main];
pluginInstance.load(new giPluginPrefManager(pageData.account,enabledPlugins[i].id),pageBase,enabledPlugins[i].id,pageData.serverAccount,pageId);pageData.plugins.push(pluginInstance)}catch(e){giLogger.warn("Failed to initialize "+e,"giPluginManager._loadPageComplete","plugin id: "+enabledPlugins[i].id,pageId)}giLogger.log("connect pageBase","giPluginManager._loadPageComplete",pageId);pageData.pageBase=pageBase;pageData.doc.defaultView.addEventListener("pagehide",giPluginManager._pageUnload,true);giLogger.log("connect pageBase",
"giPluginManager._loadPageComplete",pageId);pageBase.connect();giLogger.log("attach boxServer","giPluginManager._loadPageComplete",pageId);var box=giPluginManager.getPluginInstance(boxMain,pageBase);box.loadServerUI(pageData.serverAccount);if(pageData.account=="a.r.mitchell.test@googlemail.com"){var serverAccount=new giServerAccount;serverAccount._isLoaded=true;serverAccount._loggedIn=false;serverAccount._accountType=giServerAccount.TYPES.FREE;box.loadServerUI(serverAccount,true);var serverAccount=
new giServerAccount;serverAccount._isLoaded=true;serverAccount._loggedIn=true;serverAccount._passwordHash="blahblah";serverAccount._accountType=giServerAccount.TYPES.PLUS;box.loadServerUI(serverAccount,true);var serverAccount=new giServerAccount;serverAccount._isLoaded=true;serverAccount._loggedIn=true;serverAccount._passwordHash="blahblah";serverAccount._accountType=giServerAccount.TYPES.FREE;box.loadServerUI(serverAccount,true);var serverAccount=new giServerAccount;serverAccount._isLoaded=true;
serverAccount._loggedIn=false;serverAccount._passwordHash="blahblah";serverAccount._errorLog=[{type:"unknownCredentials"}];box.loadServerUI(serverAccount,true);var serverAccount=new giServerAccount;serverAccount._isLoaded=true;serverAccount._loggedIn=false;serverAccount._passwordHash="blahblah";serverAccount._errorLog=[{type:"serverFail"}];box.loadServerUI(serverAccount,true)}}catch(e){giLogger.warn(e,"giPluginManager._loadPageComplete",null,pageId)}},registerPlugin:function(pluginData){giLogger.log("Register plugin: "+
pluginData.id,"giPluginManager.registerPlugin");giPluginManager._plugins[pluginData.id]=pluginData},_initPluginPrefs:function(pageId,pluginId){try{giLogger.log("st "+pluginId,"giPluginManager._initPluginPrefs",pageId);var pageData=giPluginManager._pluginPageInstances[pageId];var pluginData=giPluginManager._plugins[pluginId];var oldVersion=giPluginManager._prefs.getPluginVersion(pluginData.id);var pluginDefaults=giPluginManager._prefs.getPluginDefaults(pluginData.id);var hasProps=false;for(p in pluginDefaults){hasProps=
true;break}if(!hasProps)oldVersion=null;var accounts=giPluginManager._prefs.getAccounts();for(var i=0;i<accounts.length;i++){var accountPrefs=giPluginManager._prefs.getPref(accounts[i]);var hasProps=false;if(typeof giPluginManager._prefs.getPluginPref(accounts[i],pluginId,"enabled")!="undefined")for(aid in accountPrefs){for(p in accountPrefs[aid]){hasProps=true;break}if(hasProps)break}if(!hasProps){oldVersion=null;giPluginManager._prefs.resetPluginPrefs(pageData.account,pluginId);break}}if(oldVersion==
pluginData.version){giPluginManager._plugins[pluginId].initialized=true;giPluginManager._loadPageComplete(pageId)}else{giLogger.log("version change for "+pluginData.id+" from "+oldVersion+" to "+pluginData.version,"giPluginManager._initPluginPrefs",pageId);if(pluginData.defaults){giLogger.log(pluginData.id+" load defaults","giPluginManager._initPluginPrefs",pageId);giFileIO.readFile(pluginData.defaults,null,null,function(newDefaultsJson){try{giLogger.log(pluginData.id+" calback from loading "+pluginData.defaults+
". Json: "+newDefaultsJson,"giPluginManager._initPluginPrefs",pageId);var newDefaults=giJson.decode(newDefaultsJson);if(typeof newDefaults["enabled"]=="undefined")newDefaults.enabled=true;giLogger.log(pluginData.id+" version change - new defaults to be written to default-store:\n"+newDefaultsJson,"giPluginManager._initPluginPrefs",pageId);giPluginManager._initPluginPrefs_setDefaults(pageId,pluginData,oldVersion,newDefaults)}catch(e){giLogger.warn(e,"giPluginManager._initPluginPrefs","defaults: "+
pluginData.defaults+", id: "+pluginData.id,pageId)}})}else{var newDefaults={enabled:true};giPluginManager._initPluginPrefs_setDefaults(pageId,pluginData,oldVersion,newDefaults)}}}catch(e){giLogger.warn(e.toString(),"giPluginManager._initPluginPrefs","id: "+pluginData.id,pageId)}},_initPluginPrefs_setDefaults:function(pageId,pluginData,oldVersion,newDefaults){try{giLogger.log("st "+pluginData.id,"giPluginManager._initPluginPrefs_setDefaults",pageId);giPluginManager._prefs.setPluginDefaults(pluginData.id,
newDefaults);if(pluginData.migrator)try{giLogger.log(pluginData.id+" version change - load migrator, class: "+pluginData.migrator,"giPluginManager._initPluginPrefs",pageId);var migrator=new window[pluginData.migrator];giLogger.log(pluginData.id+" version change - loaded migrator","giPluginManager._initPluginPrefs",pageId)}catch(e){giLogger.warn(e,"giPluginManager.registerPlugin","load migrator for "+pluginData.id,pageId)}var accounts=giPluginManager._prefs.getAccounts();var lastAccountWithError="";
for(var i=0;i<accounts.length;i++)try{var account=accounts[i];giLogger.log(pluginData.id+" version change - upgrading "+account,"giPluginManager._initPluginPrefs",pageId);giPluginManager._prefs.extendPluginPrefsWithDefaults(account,pluginData.id);if(migrator){giLogger.log(pluginData.id+" version change - migrate "+account,"giPluginManager._initPluginPrefs",pageId);migrator.migrate(new giPluginPrefManager(account,pluginData.id),oldVersion)}giLogger.log(pluginData.id+" version change - upgraded "+account,
"giPluginManager._initPluginPrefs",pageId)}catch(e){giLogger.warn("Error in account-migrate: "+e,"giPluginManager._initPluginPrefs","defaults: "+pluginData.defaults+", id: "+pluginData.id,pageId);giPluginManager._prefs.resetPluginPrefs(account,pluginData.id);if(lastAccountWithError!=account)i=i-1;lastAccountWithError=account}if(migrator)delete migrator;giPluginManager._prefs.setPluginVersion(pluginData.id,pluginData.version);giLogger.log(pluginData.id+" version change - complete","giPluginManager._initPluginPrefs",
pageId);giPluginManager._plugins[pluginData.id].initialized=true}catch(e){giLogger.log(e,"giPluginManager._initPluginPrefs_setDefaults","id: "+pluginData.id,pageId)}giPluginManager._loadPageComplete(pageId)},getPluginInstance:function(classDef,pageBase){for(pageId in giPluginManager._pluginPageInstances)if(giPluginManager._pluginPageInstances[pageId].pageBase==pageBase)if(giPluginManager._pluginPageInstances[pageId].plugins)for(var j=0;j<giPluginManager._pluginPageInstances[pageId].plugins.length;j++)if(giPluginManager._pluginPageInstances[pageId].plugins[j]instanceof
classDef)return giPluginManager._pluginPageInstances[pageId].plugins[j]},_pageUnload:function(evt){var doc=evt.target.ownerDocument!=null?evt.target.ownerDocument:evt.target;if(!!doc.defaultView.frameElement||doc.URL=="about:blank")return;doc.defaultView.removeEventListener("pagehide",giPluginManager._pageUnload,true);for(pageId in giPluginManager._pluginPageInstances){var pageData=giPluginManager._pluginPageInstances[pageId];if(pageData.doc!=doc)continue;giLogger.log("Unloading active page","giPluginManager._pageUnload",
pageData.pageId);for(var j=0;j<pageData.plugins.length;j++)try{pageData.plugins[j].unload()}catch(e){var id=pageData.plugins[j]?pageData.plugins[j]._classPrefix:"unknown-id";giLogger.warn("Could not unload plugin "+id+": "+e,"giPluginManager._pageUnload",pageData.pageId)}giLogger.log("Unloading pageBase","giPluginManager._pageUnload",pageData.pageId);pageData.pageBase.unload();if(pageData.loadFailMonitor)pageData.loadFailMonitor.unload();giLogger.removePageLogs(pageData.pageId);delete giPluginManager._pluginPageInstances[pageId];
return}}});
