var giPrefManager=giBase.extend({_prefData:null,_checkedPluginInit:null,loaded:false,constructor:function(){this._checkedPluginInit={};if(typeof giPluginManager!="undefined"&&giPluginManager.browserName)if(giPluginManager.browserName=="mozilla"){this._prefData=Components.classes["@gtdinbox.com/pref-manager;1"].getService().wrappedJSObject;this.loaded=true;this.dispatchEvent({name:giPrefManager.LOADED})}else{if(giPluginManager.browserName=="chrome"){this._prefData=new giPrefData;if(this._prefData._loaded){this.loaded=
true;this.dispatchEvent({name:giPrefManager.LOADED})}else this._prefData.addEventListener(giPrefData.LOADED,function(){this.loaded=true;this.dispatchEvent({name:giPrefManager.LOADED})},this)}}else if(typeof Components!="undefined"&&typeof Components.classes){this._prefData=Components.classes["@gtdinbox.com/pref-manager;1"].getService().wrappedJSObject;this.loaded=true;this.dispatchEvent({name:giPrefManager.LOADED})}else throw new Error("giPrefData not found (custom gtdi error)");},resetAll:function(){if(!this.loaded)giLogger.error("Not loaded.",
"giPrefManager.resetAll");this._prefData.prefs={};this._prefData.accounts=[];this._prefData.defaults={};this._prefData.requestSave()},getPref:function(account,pref){if(!this.loaded)giLogger.error("Not loaded.","giPrefManager.getPref");this._initializeAccount(account);var prefPath=pref?pref.split("."):[];prefPath.unshift(account);var wantedPref=this._prefData.prefs;while(prefPath.length){var next=prefPath.shift();if(typeof wantedPref[next]=="undefined")return undefined;wantedPref=wantedPref[next]}return wantedPref},
getPluginPref:function(account,plugin,pref){if(!this.loaded)giLogger.error("Not loaded.","giPrefManager.getPluginPref");this._initializePluginPrefs(account,plugin);var prefPath=pref?pref.split("."):[];prefPath.unshift(plugin);return this.getPref(account,prefPath.join("."))},setPref:function(account,pref,value,instantSave){if(!this.loaded)giLogger.error("Not loaded.","giPrefManager.setPref");var prefPath=pref?pref.split("."):[];prefPath.unshift(account);var base=this._prefData.prefs;while(prefPath.length>
1){var currentStep=prefPath.shift();if(typeof base[currentStep]=="undefined")base[currentStep]={};base=base[currentStep]}base[prefPath[0]]=value;if(typeof base[prefPath[0]]!="undefined"&&(value===null||value===undefined))delete base[prefPath[0]];if(instantSave)this._prefData.save();else this._prefData.requestSave()},setPluginPref:function(account,plugin,pref,value,instantSave){if(!this.loaded)giLogger.error("Not loaded.","giPrefManager.setPluginPref");this._initializePluginPrefs(account,plugin);var prefPath=
pref?pref.split("."):[];prefPath.unshift(plugin);return this.setPref(account,prefPath.join("."),value,instantSave)},getAccounts:function(){if(!this.loaded)giLogger.error("Not loaded.","giPrefManager.getAccounts");var accounts=[];for(a in this._prefData.prefs)if(this._prefData.prefs.hasOwnProperty(a))accounts.push(a);return accounts},resetPluginPrefs:function(account,plugin){if(!this.loaded)giLogger.error("Not loaded.","giPrefManager.resetPluginPrefs");var defaults=giJson.decode(giJson.encode(this._prefData.defaults[plugin]));
this.setPref(account,plugin,defaults)},extendPluginPrefsWithDefaults:function(account,plugin){if(!this.loaded)giLogger.error("Not loaded.","giPrefManager.extendPluginPrefsWithDefaults");var defaults=giJson.decode(giJson.encode(this._prefData.defaults[plugin]));var current=this.getPref(account,plugin)||{};this._extendPluginPrefsWithDefaults(defaults,current);this._prefData.requestSave()},_extendPluginPrefsWithDefaults:function(defaultPrefs,accountPrefs){for(p in defaultPrefs)if(defaultPrefs.hasOwnProperty(p))if(accountPrefs[p]){if(defaultPrefs[p].constructor&&
defaultPrefs[p].constructor==Object)this._extendPluginPrefsWithDefaults(defaultPrefs[p],accountPrefs[p])}else accountPrefs[p]=defaultPrefs[p]},getPluginDefaults:function(plugin){if(!this.loaded)giLogger.error("Not loaded.","giPrefManager.getPluginDefaults");return this._prefData.defaults[plugin]},setPluginDefaults:function(plugin,defaults){if(!this.loaded)giLogger.error("Not loaded.","giPrefManager.setPluginDefaults");this._prefData.defaults[plugin]=defaults;this._prefData.requestSave()},getPluginVersion:function(plugin){if(!this.loaded)giLogger.error("Not loaded.",
"giPrefManager.getPluginVersion");return this._prefData.pluginVersions[plugin]},setPluginVersion:function(plugin,newVersion){if(!this.loaded)giLogger.error("Not loaded.","giPrefManager.setPluginVersion");this._prefData.pluginVersions[plugin]=newVersion;this._prefData.save()},_initializeAccount:function(account){if(typeof this._prefData.prefs[account]!="undefined")return;this.setPref(account,null,giJson.decode(giJson.encode(this._prefData.defaults)));this._prefData.accounts.push(account)},_initializePluginPrefs:function(account,
plugin){if(this._checkedPluginInit[account+"|"+plugin])return;var data=this.getPref(account,plugin);if(data===undefined){if(!this._prefData.defaults[plugin])this._prefData.defaults[plugin]={};var defaults=giJson.decode(giJson.encode(this._prefData.defaults[plugin]));this.setPref(account,plugin,defaults)}this._checkedPluginInit[account+"|"+plugin]=true}},{LOADED:"loaded",_prefManager:null,createInstance:function(){if(!giPrefManager._prefManager)giPrefManager._prefManager=new giPrefManager;return giPrefManager._prefManager}});
giPrefManager.implement(giEventDispatcher);
