var glConversationReplyHandler=glUIWidget.extend({replies:null,_eventsContainer:null,_viewRoot:null,_statusTracker:null,_domChangeTimer:null,connect:function(gmail){giLogger.log("st","glConversationReplyHandler.connect",gmail.pageId);this.base(gmail);this._eventsContainer=new giEventsContainer(this);this.replies=[];this._viewRoot=this._gmail.page.getViewRoot();this._eventsContainer.observe(this._viewRoot,"DOMNodeInserted",this._domChange,true);this._refresh(true)},disconnect:function(){if(this._domChangeTimer){clearTimeout(this._domChangeTimer);
this._domChangeTimer=null}this._viewRoot=null;this.replies.length=0;this._statusTracker={};this._eventsContainer.reset();this._eventsContainer=null;this.base()},_refresh:function(){var doc=this._gmail.canvasDocument;this.replies.length=0;var oldStatus=this._statusTracker;this._statusTracker={};var updated=false;var result=doc.evaluate(".//DIV[@class='gA gt']/DIV[@class='gB']",this._gmail.page.getViewRoot(),null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null);if(result.snapshotLength==0)if(this._gmail.page.locationHref().indexOf("#drafts")==
-1)giLogger.error("Could not find reply rows.","glConversationReplyHandler._refresh",this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID);for(var i=0;i<result.snapshotLength;i++){var elRoot=result.snapshotItem(i);var id=elRoot.getAttribute("gtdi-reply-id");if(!id){id=(new Date).valueOf().toString()+Math.floor(Math.random()*100+1);elRoot.setAttribute("gtdi-reply-id",id)}var d=this.createReplyData(elRoot);d.showingFull=!!(d.elFull.innerHTML&&d.elFull.firstChild.nodeName!="TEXTAREA");this.replies.push(d);
this._statusTracker[id]={showingFull:d.showingFull};if(oldStatus)if(oldStatus[id]){if(oldStatus[id].showingFull!=this._statusTracker[id].showingFull){if(this._statusTracker[id].showingFull)this.dispatchEvent({name:glConversationReplyHandler.SHOW_REPLY_FULL,id:id});else this.dispatchEvent({name:glConversationReplyHandler.HIDE_REPLY_FULL,id:id});updated=true}delete oldStatus[id]}else{this.dispatchEvent({name:glConversationReplyHandler.ADD_REPLY_ROW,id:id});updated=true}}if(oldStatus)for(i in oldStatus){this.dispatchEvent({name:glConversationReplyHandler.REMOVE_REPLY_ROW,
id:i});updated=true}if(updated)this.dispatchEvent({name:glConversationReplyHandler.UPDATED})},_domChange:function(evt){this._eventsContainer.stopObserving(this._viewRoot,"DOMNodeInserted",this._domChange,true);var me=this;this._domChangeTimer=setTimeout(function(){me._domChangeTimeout()},500)},_domChangeTimeout:function(){if(!this.isConnected())return;this._domChangeTimer=null;try{this._refresh();this._eventsContainer.observe(this._viewRoot,"DOMNodeInserted",this._domChange,true)}catch(e){giLogger.warn(e,
"glConversationReplyHandler._domChangeTimeout",null,this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID)}},createReplyData:function(el){var elRoot=el;while(elRoot.parentNode&&!elRoot.hasAttribute("gtdi-reply-id"))elRoot=elRoot.parentNode;return{id:elRoot.getAttribute("gtdi-reply-id"),elRoot:elRoot,elHeader:elRoot.childNodes[0],elFull:elRoot.childNodes[1]}},getReplyByEl:function(el){while(el.parentNode){if(el.hasAttribute("gtdi-reply-id"))return this.getReplyById(el.getAttribute("gtdi-reply-id"));
el=el.parentNode}},getReplyById:function(id){for(var i=0;i<this.replies.length;i++)if(this.replies[i].id==id)return this.replies[i]},getSendButton:function(elRoot){var doc=this._gmail.canvasDocument;var result=doc.evaluate("..//div[@class='dX J-Jw']/div[@role='button']",elRoot,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null);var el=this._getSendButton(result);if(!el)giLogger.error("Could not find find send button.","glConversationReplyHandler.getSendButton",this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID);
return el},_getSendButton:function(result){for(var i=0;i<result.snapshotLength;i++){var elSend=result.snapshotItem(i);if(!elSend.getAttribute("gtdimade")){var name=elSend.innerHTML.replace(/<[^>]+?>/g,"");if(!/ \& /.test(name))return elSend}}},getSendButton2:function(elRoot){var doc=this._gmail.canvasDocument;var result=doc.evaluate("..//div[@class='CoUvaf']//div[@class='dX J-Jw']/div[@role='button']",elRoot,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null);var el=this._getSendButton(result);if(!el)giLogger.error("Could not find find send button 2.",
"glConversationReplyHandler.getSendButton2",this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID);return el},getToField:function(elRoot){var doc=this._gmail.canvasDocument;return doc.evaluate("..//textarea[@name='to']",elRoot,null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue},getCcField:function(elRoot){var doc=this._gmail.canvasDocument;return doc.evaluate("..//textarea[@name='cc']",elRoot,null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue},isFullShowing:function(elRoot){if(this.getToField(elRoot))return true;
else return false},isCacheable:function(){return false}},{SHOW_REPLY_FULL:"SHOW_REPLY_FULL",REMOVE_REPLY_FULL:"REMOVE_REPLY_FULL",ADD_REPLY_ROW:"ADD_REPLY_ROW",REMOVE_REPLY_ROW:"REMOVE_REPLY_ROW",UPDATED:"updated"});glConversationReplyHandler.implement(giEventDispatcher);
