var glConversationView=glUIView.extend({actionsHeader:null,_threadId:null,_thread:null,_threadCreatedBool:false,_replyHandler:null,_elTitle:null,_elMain:null,_elAdvertisingContainer:null,connect:function(gmail){giLogger.log("st","glConversationView.connect",gmail.pageId);this.base(gmail);this.actionsHeader=gmail.getUIObject("actionsHeader");this.actionsHeader.load()},disconnect:function(){if(!this._gmail)return;this._gmail.actions.removeEventListener(glActionManager.THREAD_CHANGED,this._threadChanged,
this);if(this._replyHandler){this._replyHandler.disconnect();this._replyHandler=null}this._thread=null;if(this.actionsHeader){this.actionsHeader.disconnect();this.actionsHeader=null}for(p in this)if(this.hasOwnProperty(p)&&this[p]&&this[p].nodeName)this[p]=null;this.base()},getActionsHeader:function(){return this.actionsHeader},isThreadCreated:function(){return this._threadCreatedBool},getThread:function(){if(!this._thread){var m=this._gmail.page.location("hash").match(/\/([^\/]+?)$/);if(m){this._threadId=
m[1]?m[1]:null;giLogger.log("threadId: "+this._threadId,"glConversationView.getThread",this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID)}if(this._threadId&&this._threadId.length>=14){var labels=[];var results=this.getHeaderLabels();for(var i=0;i<results.snapshotLength;i++)labels.push(results.snapshotItem(i).getAttribute("name"));this._thread=glThread.createBasic(this._threadId,labels,this._gmail);this._thread.loadComplete();this._gmail.actions.addEventListener(glActionManager.THREAD_CHANGED,
this._threadChanged,this);this._threadCreatedBool=true;this.dispatchEvent({name:glConversationView.THREAD_CREATED})}else{var url=this._gmail.page.location("hash");var splitter=url.split("/");if(splitter.length==1&&splitter[0]=="#sent"||splitter[0]=="#drafts"){var searchStr=splitter[0].replace("#","in:");var results=this._gmail.canvasDocument.evaluate(".//*[@email]",this._gmail.page.getViewRoot(),null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null);for(var i=0;i<results.snapshotLength;i++)searchStr+=
" "+glSearch.restrictToUser(results.snapshotItem(i).getAttribute("email"),"OR").toString();searchStr+=" subject:"+this.getSubject().innerHTML.replace(/<[^>]+>/g,"");giLogger.log("#GMAILCVISSUE Searching for conversation thread, using query: "+searchStr,"glConversation.getThread",this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID);var search=new glSearch(this._gmail);search.find(searchStr);search.addEventListener(glSearch.COMPLETED,this._getThread_searchComplete,this);search.runBackground()}else giLogger.error("Could not find threadId: "+
this._gmail.page.location("href"),"glConversationView.getThread",this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID)}}return this._thread},_getThread_searchComplete:function(evt){var search=evt.target;var threads=search.getResults();var html=this._gmail.page.getViewRoot().innerHTML;var thread=null;for(var i=0;i<threads.length;i++){var countMatch=0;var tokens=threads[i].bodySnippetHtml.split(" ");for(var j=0;j<tokens.length;j++)if(html.indexOf(tokens[j])>-1)countMatch++;var percentMatch=0;if(countMatch==
0&&tokens.length==0)percentMatch=100;else if(countMatch>0&&tokens.length>0)percentMatch=parseInt(countMatch/tokens.length*100);if(percentMatch>80){thread=threads[i];break}}if(thread){giLogger.log("#GMAILCVISSUE Matched thread with subject: "+thread.subjectSnippetHtml+"\nBody snippet: "+thread.bodySnippetHtml,"glConversationView._getThread_searchComplete",this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID);this._threadId=thread.threadId;this._thread=thread;this._thread.loadComplete();this._gmail.actions.addEventListener(glActionManager.THREAD_CHANGED,
this._threadChanged,this);this._threadCreatedBool;this.dispatchEvent({name:glConversationView.THREAD_CREATED})}},_threadChanged:function(evt){if(this._thread&&this._thread.hasId(evt.thread))this._thread.updateFromEvent(evt)},getOriginalMessageId:function(){return glRequestOriginalMsg.createRequest(this._gmail,this._threadId)},getReplyHandler:function(){if(!this._replyHandler)this._replyHandler=this._gmail.getUIObject("conversationReplyHandler");return this._replyHandler},getTitle:function(){if(!this._elTitle){var doc=
this._gmail.canvasDocument;this._elTitle=doc.evaluate(".//h1[@class='ha']",this._gmail.page.getViewRoot(),null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue;if(!this._elTitle)this._elTitle=doc.evaluate(".//h1[@class='YfMhcb']",this._gmail.page.getViewRoot(),null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue;if(!this._elTitle){var elSpan=doc.evaluate(".//span[@class='hP']",this._gmail.page.getViewRoot(),null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue;if(elSpan)this._elTitle=
elSpan.parentNode}}if(!this._elTitle)giLogger.error("Could not find conversation title element.","glConversationView.getTitle",this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID);return this._elTitle},getSubject:function(){var elSubject=this._gmail.canvasDocument.evaluate(".//span[@class='hP']",this._gmail.page.getViewRoot(),null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue;if(!elSubject)giLogger.error("Could not find conversation subject element.","glConversationView.getSubject",
this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID);return elSubject},getMainPane:function(){if(!this._elMain){var doc=this._gmail.canvasDocument;this._elMain=doc.evaluate("./div/table[contains(@class,'nH iY')]",this._gmail.page.getViewRoot(),null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue}if(!this._elMain)giLogger.error("Could not find conversation main element.","glConversationView.getMainPane",this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID);return this._elMain},getAdvertisingContainer:function(){if(!this._elAdvertisingContainer){var doc=
this._gmail.canvasDocument;this._elAdvertisingContainer=doc.evaluate(".//td//div[@class='u5']",this._gmail.page.getViewRoot(),null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue}if(!this._elAdvertisingContainer)giLogger.error("Could not find conversation advertising element.","glConversationView.getAdvertisingContainer",this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID);return this._elAdvertisingContainer},getPaginationInfo:function(){try{var result=this._gmail.canvasDocument.evaluate(".//div[@class='h0']/b",
this.actionsHeader.pagination,null,XPathResult.FIRST_ORDERED_NODE_TYPE,null);if(!result.singleNodeValue)giLogger.logConcern("Could not find pagination B element.","glConversationView.getPaginationInfo",this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID);if(!result.singleNodeValue)return{currentOffset:0,results:0};var span=result.singleNodeValue.parentNode;var bNodes=span.getElementsByTagName("b");return{currentOffset:parseInt(bNodes[0].textContent),results:parseInt(bNodes[1].textContent)}}catch(e){giLogger.warn(e,
"glConversationView.getPaginationInfo",null,this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID)}},getMovePreviousElement:function(){var pagination=this.getPaginationInfo();if(pagination.results!=0&&pagination.currentOffset==1)return;var elNav=this._gmail.canvasDocument.evaluate(".//div[@class='iG']/div[@class='h0']",this.actionsHeader.root,null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue;var el=null;if(elNav.firstChild.nodeName=="SPAN")el=elNav.firstChild;if(!el)giLogger.logConcern("Could not get conversation move-previous element.",
"glConversationView.getMovePreviousElement",this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID);return el},getMoveNextElement:function(){var pagination=this.getPaginationInfo();if(pagination.results!=0&&pagination.currentOffset==pagination.results)return;var elNav=this._gmail.canvasDocument.evaluate(".//div[@class='iG']/div[@class='h0']",this.actionsHeader.root,null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue;var el=null;if(elNav.childNodes.length>0&&elNav.lastChild.nodeName=="SPAN")el=
elNav.lastChild;if(!el)giLogger.logConcern("Could not get conversation move-previous element.","glConversationView.getMovePreviousElement",this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID);return el},getHeaderLabels:function(){return this._gmail.canvasDocument.evaluate(".//td/span[@class='hN']",this.getTitle(),null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null)}},{THREAD_CREATED:"thread_created"});glConversationView.implement(giEventDispatcher);
