var gtdBrowserThread=gtdBrowser.extend({_eventsContainer:null,_elTitle:null,_elCurrent:null,_threadUI:null,_threads:null,_thread:null,connect:function(main){giLogger.log("st","gtdBrowserThread.connect",main?main.pageId:giLogger.UNKNOWN_PAGE_ID);this.base(main);this._eventsContainer=new giEventsContainer(this);this._threads=[];var doc=this._main.gmail.canvasDocument;var elBreadcrumb=doc.createElement("DIV");elBreadcrumb.className="gtdi-breadcrumb";this.elHeader.appendChild(elBreadcrumb);var elPaging=
doc.createElement("DIV");elPaging.id="gtdi-paging";elPaging.className="gtdi-btngrp";this.elHeader.appendChild(elPaging);elBtnGrp=doc.createElement("DIV");elBtnGrp.className="gtdi-btn-grp";elPaging.appendChild(elBtnGrp);elBtn=doc.createElement("DIV");elBtn.className="gtdi-btn";elBtn.innerHTML='<div class="gtdi-btn"><b class="gtdi-btn-t"></b><b class="gtdi-btn-t2"></b><b class="gtdi-btn-m"></b><b class="gtdi-btn-b2"></b><b class="gtdi-btn-b"></b><span class="gtdi-btn-label"><span class="gtdi-paging-prev">'+
giI18N.getString("Browser.Thread.Paging.prev")+"</span></span></div>";elBtnGrp.appendChild(elBtn);elBtn=doc.createElement("DIV");elBtn.className="gtdi-btn";elBtn.innerHTML='<div class="gtdi-btn"><b class="gtdi-btn-t"></b><b class="gtdi-btn-t2"></b><b class="gtdi-btn-m"></b><b class="gtdi-btn-b2"></b><b class="gtdi-btn-b"></b><span class="gtdi-btn-label"><span class="gtdi-paging-current"></span></span></div>';elBtnGrp.appendChild(elBtn);this._elCurrent=doc.evaluate(".//span[@class='gtdi-paging-current']",
elBtn,null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue;elBtn=doc.createElement("DIV");elBtn.className="gtdi-btn";elBtn.innerHTML='<div class="gtdi-btn"><b class="gtdi-btn-t"></b><b class="gtdi-btn-t2"></b><b class="gtdi-btn-m"></b><b class="gtdi-btn-b2"></b><b class="gtdi-btn-b"></b><span class="gtdi-btn-label"><span class="gtdi-paging-next">'+giI18N.getString("Browser.Thread.Paging.next")+"</span></span></div>";elBtnGrp.appendChild(elBtn);this._threadUI=this._main.getUIObject("thread");
this.elBody.appendChild(this._threadUI.el);this._eventsContainer.observe(this.el,"mousedown",this._click,false);this._threadUI.addEventListener(gtdThread.CLICK_OPEN,this._clickOpen,this);this._threadUI.getLabellingBox().addEventListener(gtdConversationActionAndMove.CLICK_ACTION,this._actionAndMove,this);this._main.gmail.actions.addEventListener(glActionManager.THREAD_CHANGED,this._threadChanged,this)},disconnect:function(){this._main.gmail.actions.removeEventListener(glActionManager.THREAD_CHANGED,
this._threadChanged,this);this._threadUI.getLabellingBox().removeEventListener(gtdConversationActionAndMove.CLICK_ACTION,this._actionAndMove,this);this._threadUI.disconnect();this._threadUI=null;this._elTitle=null;this._elCurrent=null;this._eventsContainer.reset();this._eventsContainer=null;this._threads=null;this._thread=null;this.base()},load:function(type,item){this._threads.length=0;this._loadThread(item)},_loadThread:function(thread){if(!thread)return null;this._thread=thread;this._threadUI.load(thread);
this._setPaging();return thread},setThreads:function(threads){this._threads=threads||[];var elPaging=this.elHeader.ownerDocument.evaluate(".//*[@id='gtdi-paging']",this.elHeader,null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue;elPaging.style.display=this._threads.length==0?"none":"";this._setPaging()},_setPaging:function(){for(var i=0;i<this._threads.length;i++)if(this._threads[i].threadId==this._thread.threadId){this._elCurrent.innerHTML=i+1+" "+giI18N.getString("Browser.Thread.Paging.of")+
" "+this._threads.length;var actionAndMove=this._threadUI.getLabellingBox().getActionAndMove();if(actionAndMove)actionAndMove.setMovePrevNextVisibility(i!=0,i!=this._threads.length-1);break}},_pagingNext:function(){var oldThreadId=this._thread.threadId;for(var i=0;i<this._threads.length;i++)if(this._threads[i].threadId==oldThreadId)if(this._threads[i+1]){this._threads[i+1]=this._loadThread(this._threads[i+1]);this.dispatchEvent({name:gtdBrowserThread.MOVE_NEXT,thread:this._threads[i+1],index:i+1,
oldThreadId:oldThreadId});break}},_pagingPrev:function(){var oldThreadId=this._thread.threadId;for(var i=0;i<this._threads.length;i++)if(this._threads[i].threadId==oldThreadId)if(this._threads[i-1]){this._threads[i-1]=this._loadThread(this._threads[i-1]);this.dispatchEvent({name:gtdBrowserThread.MOVE_PREVIOUS,thread:this._threads[i-1],index:i-1,oldThreadId:oldThreadId});break}},_click:function(event){try{var el=event.target;while(el.parentNode){if(el.className=="gtdi-btn"){giUtil.stopEvent(event);
var elBtn=el.ownerDocument.evaluate(".//*[contains(@class,'gtdi-paging-prev') or contains(@class, 'gtdi-paging-next')]",el,null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue;if(elBtn){if(elBtn.className=="gtdi-paging-prev"){giUtil.stopEvent(event);this._pagingPrev();break}if(elBtn.className=="gtdi-paging-next"){giUtil.stopEvent(event);this._pagingNext();break}}}el=el.parentNode}}catch(e){giLogger.warn(e,"gtdBrowserThread._click",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}},
setServerActionType:function(type){this._threadUI.setServerActionType(type)},_clickOpen:function(evt){this.dispatchEvent({name:gtdBrowser.LOAD_TYPE,type:gtdBrowser.TYPES.THREAD,item:evt.thread,openInGmail:true,newWindow:evt.newWindow})},_actionAndMove:function(evt){var threadId=this._thread.getRecentId();if(evt.button==gtdConversationActionAndMove.BUTTONS.ARCHIVE){if(evt.button==gtdConversationActionAndMove.BUTTONS.ARCHIVE)this._main.gmail.actions.performAction(glActionManager.ARCHIVE,threadId,glActionManager.USE_AJAX)}else if(evt.button==
gtdConversationActionAndMove.BUTTONS.FINISH){this._main.gmail.actions.performAction(glActionManager.ARCHIVE,threadId,glActionManager.USE_AJAX);var statusData=this._main.labelsData.getStatusData();if(this._main.labelsData.hasLabel(statusData.finished))this._main.gmail.actions.performAction(glActionManager.ADD_LABEL,this._thread,glActionManager.USE_AJAX,statusData.finished)}else if(evt.button==gtdConversationActionAndMove.BUTTONS.REPORT_SPAM||evt.button==gtdConversationActionAndMove.BUTTONS.DELETE)if(evt.button==
gtdConversationActionAndMove.BUTTONS.DELETE)this._main.gmail.actions.performAction(glActionManager.DELETE,threadId,glActionManager.USE_AJAX);else if(evt.button==gtdConversationActionAndMove.BUTTONS.REPORT_SPAM)this._main.gmail.actions.performAction(glActionManager.REPORT_SPAM,threadId,glActionManager.USE_AJAX);if(evt.move=="prev")this._pagingPrev();if(evt.move=="next")this._pagingNext()},_threadChanged:function(event){for(var i=0;i<this._threads.length;i++)if(this._threads[i].hasId(event.thread)){this._threads[i].updateFromEvent(event);
break}},getThreads:function(){return this._threads},getThread:function(){return this._thread},getTitle:function(){return this._thread?this._thread.subject:""}},{MOVE_NEXT:"threadNext",MOVE_PREVIOUS:"threadPrevious"});gtdBrowserThread.implement(giEventDispatcher);
