var gtdBrowserPopup=giUIObject.extend({_serverActionType:null,_eventsContainer:null,el:null,elNav:null,_elBack:null,_elContainer:null,_currentBrowser:null,_browserHistory:[],_resizer:null,connect:function(main){giLogger.log("st","gtdBrowserPopup.connect",main?main.pageId:giLogger.UNKNOWN_PAGE_ID);this.base(main);this._eventsContainer=new giEventsContainer(this);this._browserHistory=[];var doc=main.gmail.canvasDocument;this.el=doc.createElement("DIV");this.el.className="gtdi gtdi-popup";this.el.style.position=
"absolute";this._elContainer=doc.createElement("DIV");this._elContainer.id="gtdi-browser-container";this._elContainer.setAttribute("gtdi-resizable","1");this.el.appendChild(this._elContainer);var elClose=doc.createElement("A");elClose.className="gtdi-close";elClose.title=giI18N.getString("Browser.Popup.Close");elClose.innerHTML=giI18N.getString("Browser.Popup.Close");this.el.appendChild(elClose);this.elNav=doc.createElement("DIV");this.elNav.id="gtdi-backhome";var elNavList=doc.createElement("UL");
this.elNav.appendChild(elNavList);this._elBack=doc.createElement("LI");this._elBack.id="gtdi-backbutton";this._elBack.title=giI18N.getString("ThreadViewer.Back");elNavList.appendChild(this._elBack);var elBrand=doc.createElement("LI");elBrand.id="gtdi-homebutton";elBrand.title=giI18N.getString("Browser.Popup.Overview");elNavList.appendChild(elBrand);this._serverActionType=glActionManager.USE_AJAX;this.hide();this._main.gmail.canvasDocument.body.appendChild(this.el);this._eventsContainer.observe(this.el,
"mousedown",this._click,false);this._eventsContainer.observe(elClose,"click",this._clickClose,false)},disconnect:function(){if(this.el&&this.el.parentNode)this.el.parentNode.removeChild(this.el);this.el=null;for(p in this)if(this[p]&&this[p].nodeName&&this[p].nodeType)this[p]=null;if(this._resizer){this._resizer.disconnect();this._resizer=null}if(this._currentBrowser)this._currentBrowser.disconnect();this._currentBrowser=null;for(var i=0;i<this._browserHistory.length;i++)this._browserHistory[i].disconnect();
this._browserHistory.length=0;this._eventsContainer.reset();this._eventsContainer=null;this.base()},load:function(browser){if(this._currentBrowser){this._currentBrowser.removeEventListener(gtdBrowser.LOAD_TYPE,this._loadType,this);this._currentBrowser.removeEventListener(gtdBrowser.RESIZABLE_ELEMENT_CHANGE,this._resizableElementChange,this);this._browserHistory.push(this._currentBrowser);this._rememberScrollPositions(this._currentBrowser.el)}this._refreshBackButton();this._currentBrowser=browser;
if(this._currentBrowser.setServerActionType)this._currentBrowser.setServerActionType(this._serverActionType);this._currentBrowser.elHeader.insertBefore(this.elNav,this._currentBrowser.elHeader.firstChild);this._eventsContainer.observe(this._currentBrowser.elHeader,"mousedown",this._clickHeader,false);this._elContainer.innerHTML="";this._elContainer.appendChild(this._currentBrowser.el);this._currentBrowser.addEventListener(gtdBrowser.LOAD_TYPE,this._loadType,this);this._currentBrowser.addEventListener(gtdBrowser.RESIZABLE_ELEMENT_CHANGE,
this._resizableElementChange,this);if(this.isActive())this._resizableElementChange();else this._show();this._rememberScrollPositions(this._currentBrowser.el,true);this.dispatchEvent({name:gtdBrowserPopup.LOADED_BROWSER,browser:this._currentBrowser})},_refreshBackButton:function(){if(this._browserHistory.length>0){if(!giUIObject.hasClassName(this._elBack,"gtdi-active"))giUIObject.addClassName(this._elBack,"gtdi-active");this._elBack.title=this._browserHistory[this._browserHistory.length-1].getTitle()}else{giUIObject.removeClassName(this._elBack,
"gtdi-active");this._elBack.title=""}},_rememberScrollPositions:function(el,restore){var result=el.ownerDocument.evaluate(".//*[@gtdi-remember-scroll]",el,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null);if(restore){if(el.gtdiScrollData)for(var i=0;i<result.snapshotLength;i++){var elScroll=result.snapshotItem(i);if(elScroll.id&&el.gtdiScrollData[elScroll.id])elScroll.scrollTop=el.gtdiScrollData[elScroll.id]}}else for(var i=0;i<result.snapshotLength;i++){var elScroll=result.snapshotItem(i);if(elScroll.id){if(!el.gtdiScrollData)el.gtdiScrollData=
{};el.gtdiScrollData[elScroll.id]=elScroll.scrollTop}}},_click:function(evt){try{var el=evt.target;if(el==this._currentBrowser.elHeader){this._drag={pointerX:evt.pageX,pointerY:evt.pageY,left:parseInt(this.el.style.left),top:parseInt(this.el.style.top)};this._eventsContainer.observe(this._main.gmail.canvasDocument.body,"mousemove",this._dragMouseMove,false);this._eventsContainer.observe(this._main.gmail.canvasDocument.body,"mouseup",this._dragMouseUp,false)}else while(el.parentNode&&el!=this.el){if(el.id==
"gtdi-homebutton"){this.load(gtdBrowser.createBrowser(this._main));break}else if(el.id=="gtdi-backbutton"){if(this._browserHistory.length>0){var browser=this._browserHistory[this._browserHistory.length-1];this._browserHistory.length=this._browserHistory.length-1;if(this._currentBrowser){this._currentBrowser.disconnect();this._currentBrowser=null}this.load(browser);this._refreshBackButton()}break}el=el.parentNode}}catch(e){giLogger.warn(e,"gtdBrowserPopup._click",null,this._main?this._main.pageId:
giLogger.UNKNOWN_PAGE_ID)}},_clickClose:function(evt){this.hide()},_resizableElementChange:function(){if(this._resizer)this._resizer.initResizableEls();else{this._resizer=new giResizer;this._resizer.connect(this.el,this._main.prefs,"resizer",this._main.gmail)}},_dragMouseMove:function(event){var delta=[event.pageX-this._drag.pointerX,event.pageY-this._drag.pointerY];this.el.style.left=this._drag.left+delta[0]+"px";this.el.style.top=this._drag.top+delta[1]+"px"},_dragMouseUp:function(event){this._eventsContainer.stopObserving(this._main.gmail.canvasDocument.body,
"mousemove",this._dragMouseMove,false);this._eventsContainer.stopObserving(this._main.gmail.canvasDocument.body,"mouseup",this._dragMouseUp,false)},_loadType:function(evt){if(evt.openInGmail){if(evt.type==gtdBrowser.TYPES.SEARCH){var search=this._main.gmail.getUIObject("searchBox");search.setSearch(evt.item);search.submit();this.hide()}if(evt.type==gtdBrowser.TYPES.THREAD){var win=this.el.ownerDocument.defaultView.top;var path=this._main.gmail.page.locationHref();if(evt.newWindow==1){var href=this._main.gmail.page.locationHref();
var url=href.substr(0,href.indexOf("#"));url+="#inbox/"+evt.item.threadId;gBrowser.selectedTab=gBrowser.addTab(url)}else{if(path.indexOf("#search")>-1||path.indexOf("#label")>-1){var m=path.match(/#(.+?)\/(.+?)(\/[^\/]+$|$)/);if(m)path="#"+m[1]+"/"+m[2];else path=""}else{var m=path.match(/#(.+?)(\/[^\/]+$|$)/);if(m)path="#"+m[1];else path=""}if(!path)path="#inbox";var hash=path+"/"+evt.item.threadId;this._main.gmail.page.locationHash(hash);this.hide()}}}else{var browser=gtdBrowser.createBrowser(this._main,
evt.item,evt.type);if(browser){this.load(browser);if(evt.threads)browser.setThreads(evt.threads)}}},_keyPress:function(evt){if(evt.keyCode==27)this.hide()},hide:function(){this.el.style.display="none";this._eventsContainer.stopObserving(this._main.gmail.canvasDocument,"keypress",this._keyPress,false);for(var i=0;i<this._browserHistory.length;i++)this._browserHistory[i].disconnect();this._browserHistory.length=0;if(this._currentBrowser){this._currentBrowser.disconnect();this._currentBrowser=null}this._main.gmail.lightbox.hide();
this.dispatchEvent({name:gtdBrowserPopup.HIDE})},isActive:function(){return this.el.style.display!="none"},_show:function(){if(this.isActive())return;this.el.style.display="";this._resizableElementChange();var popupDims=giUIObject.getDimensions(this._elContainer);var viewport=giUIObject.viewport(this.el.ownerDocument);x=viewport[0]/2-popupDims.width/2;y=viewport[1]/2-popupDims.height/2+this.el.ownerDocument.defaultView.pageYOffset;var xy=giUIObject.boundsCheckXY(this._elContainer,x,y,true,true);x=
xy[0];y=xy[1];if(typeof x!="undefined")this.el.style.left=x+"px";if(typeof y!="undefined")this.el.style.top=y+"px";this._main.gmail.lightbox.show();this._eventsContainer.observe(this._main.gmail.canvasDocument,"keypress",this._keyPress,false)},setServerActionType:function(type){this._serverActionType=type},isCacheable:function(){return true}},{HIDE:"hide",LOADED_BROWSER:"loaded"});gtdBrowserPopup.implement(giEventDispatcher);
