var glActionManager=giBase.extend({actionBuffer:null,actionDOMBuffer:null,_recentActions:null,_gmail:null,connect:function(gmail){this._gmail=gmail;this.actionBuffer=new glActionBuffer(gmail);this.actionBufferSync=new glActionBuffer(gmail);this.actionBufferSync.async=false;this._recentActions=[];this.actionDOMBuffer=new glActionDOMBuffer(gmail);this._gmail.trafficWatcher.addEventListener(glTrafficWatcher.ACTION_REQUEST,this._environmentGeneratedAction,this)},shutdown:function(){this._gmail=null;this.actionBuffer.shutdown();
this._removeAllListeners()},performAction:function(action,threads,serverActionType,label,actionsHeader){if(typeof threads!="array")threads=[threads];for(var i=0;i<threads.length;i++){var threadId=threads[i]instanceof glThread?threads[i].threadId:threads[i];var callback=null;if(serverActionType!=glActionManager.USE_DOM){var performedAction={action:action,serverActionType:serverActionType};if(threadId){performedAction.itemType="thread";performedAction.item=threadId}else performedAction.itemType="environment";
if(label)performedAction.label=label;if(threads[i]instanceof glThread)performedAction.threadObject=threads[i];var me=this;callback=function(){me._distributeAction(performedAction)}}if(this.actionBuffer[action["bufferFunc"]]&&(serverActionType==glActionManager.USE_AJAX||serverActionType==glActionManager.USE_AJAX_SYNC||!this.actionDOMBuffer[action["bufferFunc"]])){var args=[];if(threadId)args.push(threadId);if(label)args.push(label);if(callback)args.push(callback);if(serverActionType==glActionManager.USE_AJAX)this.actionBuffer[action["bufferFunc"]].apply(this.actionBuffer,
args);else this.actionBufferSync[action["bufferFunc"]].apply(this.actionBufferSync,args)}else if(serverActionType==glActionManager.USE_DOM){var args=[];args.push(actionsHeader);if(label)args.push(label);this.actionDOMBuffer[action["bufferFunc"]].apply(this.actionDOMBuffer,args)}}},_environmentGeneratedAction:function(evt){giLogger.log("st","glActionManager._environmentGeneratedAction",this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID);var actions=this._parseURLAndData(evt.url,evt.postData);
for(var i=0;i<actions.length;i++){actions[i].environmentGenerated=true;this._distributeAction(actions[i])}},_distributeAction:function(action){giLogger.log("Notifying listeners that an action took place. Item type: "+action.itemType+", action: "+action.action.eventName+", serverActionType: "+action.serverActionType+", environmentGenerated: "+action.environmentGenerated,"glActionManager._distributeAction",this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID);if(action.itemType=="thread"){this.dispatchEvent({name:"thread_action_"+
action.item,action:action.action,serverActionType:action.serverActionType,threadObject:action.threadObject,environmentGenerated:action.environmentGenerated,performActionRequest:action.performActionRequest,label:action.label});this.dispatchEvent({name:glActionManager.THREAD_CHANGED,action:action.action,thread:action.item,serverActionType:action.serverActionType,threadObject:action.threadObject,environmentGenerated:action.environmentGenerated,performActionRequest:action.performActionRequest,label:action.label})}else if(action.itemType==
"environment"){var evt={name:glActionManager.ENVIRONMENT_CHANGED,action:action.action,label:action.label,newLabel:action.newLabel,serverActionType:action.serverActionType,environmentGenerated:action.environmentGenerated,performActionRequest:action.performActionRequest};this.dispatchEvent(evt)}else{var evt={name:glActionManager.MESSAGE_CHANGED,action:action.action,message:action.item,serverActionType:action.serverActionType,threadObject:action.threadObject,environmentGenerated:action.environmentGenerated,
performActionRequest:action.performActionRequest};if(action.label)evt.label=action.label;this.dispatchEvent(evt)}this.dispatchEvent({name:action.action.eventName,item:action.item,itemType:action.itemType,serverActionType:action.serverActionType,threadObject:action.threadObject,environmentGenerated:action.environmentGenerated,performActionRequest:action.performActionRequest,label:action.label,newLabel:action.newLabel})},_parseURLAndData:function(url,postData){var match=/[?&]act=([^&]+)/.exec(url);
if(!match)return[];var actions=[];var urlAction=match[1];postData=postData.replace(/^&+/,"").replace(/&+$/,"");if(/cc_|nc_|dc_/i.test(urlAction)){var itemType="environment";var items=null}else if(/&?t=/.test(postData)){postData=postData.replace(/(^|&)[^t][^&]+/g,"");var itemType="thread";var items=postData.split(/&?t=/)}else{var itemType="message";var items=postData.split(/&?m=/)}if(items)items.shift();var glGmail=this._gmail;var addActionForItems=function(data){if(items)for(var i=0;i<items.length;i++){var action=
{itemType:itemType,item:items[i]};for(d in data)action[d]=data[d];if(itemType=="thread")if(glGmail.page.getActiveViewType()=="cv"){var conversationView=glGmail.getCurrentViewObject();if(conversationView.isThreadCreated()){var cvThread=conversationView.getThread(true);if(cvThread.hasId(action.item))action.threadObject=cvThread}}actions.push(action)}else{var action={itemType:itemType};for(d in data)action[d]=data[d];actions.push(action)}};if(urlAction=="arl"){var actionsTemp=[];var addLabelRegex=/[&?]acn=([^&]+)/g,
removeLabelRegex=/[&?]rcn=([^&]+)/g,matches=null;url=decodeURIComponent(url);while((matches=addLabelRegex.exec(url))!=null)actionsTemp.push({action:glActionManager.ADD_LABEL,label:matches[1]});while((matches=removeLabelRegex.exec(url))!=null)actionsTemp.push({action:glActionManager.REMOVE_LABEL,label:matches[1]});for(var i=0;i<actionsTemp.length;i++)addActionForItems(actionsTemp[i])}else if(/^ac_/.test(urlAction)){var label=decodeURIComponent(/^ac_(.*)/.exec(urlAction)[1]);addActionForItems({action:glActionManager.ADD_LABEL,
label:label})}else if(/^rc_/.test(urlAction)){var label=decodeURIComponent(/^rc_(.*)/.exec(urlAction)[1]);if(label=="^i")addActionForItems({action:glActionManager.ARCHIVE});else addActionForItems({action:glActionManager.REMOVE_LABEL,label:label})}else if(urlAction=="sp")addActionForItems({action:glActionManager.REPORT_SPAM});else if(urlAction=="us")addActionForItems({action:glActionManager.NOT_SPAM});else if(urlAction=="st")addActionForItems({action:glActionManager.STAR});else if(urlAction=="xst")addActionForItems({action:glActionManager.UNSTAR});
else if(urlAction=="tr")addActionForItems({action:glActionManager.DELETE});else if(urlAction=="ib")addActionForItems({action:glActionManager.MOVE_INBOX});else if(urlAction.substr(0,3)=="cc_")addActionForItems({action:glActionManager.CREATE_LABEL,label:decodeURIComponent(urlAction.substr(3))});else if(urlAction.substr(0,3)=="nc_"){var label=decodeURIComponent(urlAction.substr(3)).split("^");addActionForItems({action:glActionManager.RENAME_LABEL,label:label[0],newLabel:label[1]})}else if(urlAction.substr(0,
3)=="dc_")addActionForItems({action:glActionManager.DELETE_LABEL,label:decodeURIComponent(urlAction.substr(3))});return actions}},{ADD_LABEL:{bufferFunc:"addLabelToThread",eventName:"label_added"},REMOVE_LABEL:{bufferFunc:"removeLabelFromThread",eventName:"label_removed"},STAR:{bufferFunc:"addStarToThread",eventName:"star_added"},UNSTAR:{bufferFunc:"removeStarFromThread",eventName:"star_removed"},ARCHIVE:{bufferFunc:"archiveThread",eventName:"item_archived"},MOVE_INBOX:{bufferFunc:"moveInbox",eventName:"item_move_inbox"},
DELETE:{bufferFunc:"deleteThread",eventName:"item_deleted"},REPORT_SPAM:{bufferFunc:"spamThread",eventName:"item_reported_spam"},NOT_SPAM:{bufferFunc:"notSpamThread",eventName:"item_not_spam"},MARK_AS_READ:{bufferFunc:"markThreadRead",eventName:"item_marked_read"},CREATE_LABEL:{bufferFunc:"createLabel",eventName:"label_created"},RENAME_LABEL:{bufferFunc:"renameLabel",eventName:"label_renamed"},DELETE_LABEL:{bufferFunc:"deleteLabel",eventName:"label_deleted"},ENVIRONMENT_CHANGED:"environment_changed",
THREAD_CHANGED:"thread_changed",MESSAGE_CHANGED:"message_changed",USE_AJAX:"ajax",USE_AJAX_SYNC:"ajax_sync",USE_DOM:"dom"});glActionManager.implement(giEventDispatcher);
