var glActionDOMBuffer=giBase.extend({_queue:null,_currentQItem:null,_queueInterval:null,_gmail:null,_scrollTopRestorer:null,constructor:function(gmail){this._gmail=gmail;this._queue=[];this._scrollTopRestorer=new giScrollTopRestorer(this._gmail)},_addQueueItem:function(fStart){var me=this;var qItem={date:(new Date).valueOf(),fStart:giUtil.bind(this,fStart)};qItem.release=function(){me._releaseQueueItem(qItem)};this._queue.push(qItem);this._tryNextQueue()},_releaseQueueItem:function(qItem){for(var i=
0;i<this._queue.length;i++)if(this._queue[i]===qItem){this._queue.splice(i,1);break}if(this._currentQItem==qItem)this._currentQItem=null;this._scrollTopRestorer.reset();this._tryNextQueue()},_tryNextQueue:function(){if(this._queue.length==0||this._queue[0]==this._currentQItem)return;this._currentQItem=this._queue[0];this._currentQItem.fStart(this._currentQItem);if(!this._queueInterval)this._queueInterval=setInterval(giUtil.bind(this,this._queueIntervalFunction),500)},_queueIntervalFunction:function(){var d=
(new Date).valueOf()-1E3*10;for(var i=this._queue.length-1;i>=0;i--)if(this._queue[i].date<d){if(this._queue[i]==this._currentQItem)this._currentQItem=null;this._queue.splice(i,1)}if(this._queue.length==0){clearInterval(this._queueInterval);this._queueInterval=null}this._tryNextQueue()},addLabelToThread:function(actionsHeader,labelname,fCallback,_qItem){try{if(!_qItem){this._addQueueItem(function(qItem){this.addLabelToThread(actionsHeader,labelname,fCallback,qItem)});return}this._scrollTopRestorer.setRestorePoint();
var actionsHeader=actionsHeader||this._gmail.getCurrentViewObject().getActionsHeader();actionsHeader.setLabelsDropdownLabelState(labelname,true,true);_qItem.release()}catch(e){if(_qItem)_qItem.release();giLogger.warn(e,"glActionDOMBuffer.addLabelToThread",null,this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID);this._testValidateLabelRetrieval()}},_testValidateLabelRetrieval:function(){try{var labels=this._gmail.environment.getUserLabels();if(labels.length>0){var label=labels[0].name;var actionsHeader=
actionsHeader||this._gmail.getCurrentViewObject().getActionsHeader();if(!actionsHeader.checkDropdownHasLabel(label))giLogger.logConcern("Could not find test/validating label ("+label+") in the dropdown","glActionDOMBuffer.addLabelToThread",null,this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID)}}catch(e){giLogger.warn(e,"glActionDOMBuffer._testValidateLabelRetrieval",null,this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID)}},removeLabelFromThread:function(actionsHeader,labelname,fCallback,
_qItem){try{if(!_qItem){this._addQueueItem(function(qItem){this.removeLabelFromThread(actionsHeader,labelname,fCallback,qItem)});return}this._scrollTopRestorer.setRestorePoint();var actionsHeader=actionsHeader||this._gmail.getCurrentViewObject().getActionsHeader();actionsHeader.setLabelsDropdownLabelState(labelname,false);_qItem.release()}catch(e){if(_qItem)_qItem.release();giLogger.warn(e,"glActionDOMBuffer.removeLabelFromThread",null,this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID);this._testValidateLabelRetrieval()}},
addStarToThread:function(actionsHeader,fCallback,_qItem){try{if(!_qItem){this._addQueueItem(function(qItem){this.addStarToThread(actionsHeader,fCallback,qItem)});return}this._scrollTopRestorer.setRestorePoint();var actionsHeader=actionsHeader||this._gmail.getCurrentViewObject().getActionsHeader();actionsHeader.clickDropdownMenuAction(glActionsHeader.MORE_ACTIONS_DROPDOWN,glActionsHeader.ADD_STAR);setTimeout(giUtil.bind(this,function(){if(fCallback)fCallback();_qItem.release()}),750)}catch(e){if(_qItem)_qItem.release();
giLogger.warn(e,"glActionDOMBuffer.addStarToThread",null,this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID)}},removeStarFromThread:function(actionsHeader,fCallback,_qItem){try{if(!_qItem){this._addQueueItem(function(qItem){this.removeStarFromThread(actionsHeader,fCallback,qItem)});return}var actionsHeader=actionsHeader||this._gmail.getCurrentViewObject().getActionsHeader();actionsHeader.clickDropdownMenuAction(glActionsHeader.MORE_ACTIONS_DROPDOWN,glActionsHeader.REMOVE_STAR);setTimeout(giUtil.bind(this,
function(){if(fCallback)fCallback();_qItem.release()}),750)}catch(e){if(_qItem)_qItem.release();giLogger.warn(e,"glActionDOMBuffer.removeStarThread",null,this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID)}},markThreadRead:function(actionsHeader,fCallback,_qItem){try{if(!_qItem){this._addQueueItem(function(qItem){this.markThreadRead(actionsHeader,fCallback,qItem)});return}this._scrollTopRestorer.setRestorePoint();var actionsHeader=actionsHeader||this._gmail.getCurrentViewObject().getActionsHeader();
actionsHeader.clickDropdownMenuAction(glActionsHeader.MORE_ACTIONS_DROPDOWN,glActionsHeader.MARK_AS_READ);setTimeout(giUtil.bind(this,function(){if(fCallback)fCallback();_qItem.release()}),500)}catch(e){if(_qItem)_qItem.release();giLogger.warn(e,"glActionDOMBuffer.markThreadRead",null,this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID)}},spamThread:function(actionsHeader,fCallback,_qItem){try{if(!_qItem){this._addQueueItem(function(qItem){this.spamThread(actionsHeader,fCallback,qItem)});return}this._scrollTopRestorer.setRestorePoint();
var actionsHeader=actionsHeader||this._gmail.getCurrentViewObject().getActionsHeader();var el=actionsHeader.getButton(glActionsHeader.REPORT_SPAM_BUTTON);this._gmail.page.simulateMouseEvent(el,"mousedown",null,null,true);this._gmail.page.simulateMouseEvent(el,"mouseup",null,null,true);setTimeout(giUtil.bind(this,function(){if(fCallback)fCallback();_qItem.release()}),500)}catch(e){if(_qItem)_qItem.release();giLogger.warn(e,"glActionDOMBuffer.spamThread",null,this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID)}},
deleteThread:function(actionsHeader,fCallback,_qItem){try{if(!_qItem){this._addQueueItem(function(qItem){this.deleteThread(actionsHeader,fCallback,qItem)});return}this._scrollTopRestorer.setRestorePoint();var actionsHeader=actionsHeader||this._gmail.getCurrentViewObject().getActionsHeader();if(actionsHeader.hasButton(glActionsHeader.DELETE_BUTTON))var el=actionsHeader.getButton(glActionsHeader.DELETE_BUTTON);else var el=actionsHeader.getButton(glActionsHeader.DELETE_FOREVER_BUTTON);this._gmail.page.simulateMouseEvent(el,
"mousedown",null,null,true);this._gmail.page.simulateMouseEvent(el,"mouseup",null,null,true);setTimeout(giUtil.bind(this,function(){if(fCallback)fCallback();_qItem.release()}),500)}catch(e){if(_qItem)_qItem.release();giLogger.warn(e,"glActionDOMBuffer.deleteThread",null,this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID)}},archiveThread:function(actionsHeader,fCallback,_qItem){try{if(!_qItem){this._addQueueItem(function(qItem){this.archiveThread(actionsHeader,fCallback,qItem)});return}this._scrollTopRestorer.setRestorePoint();
var actionsHeader=actionsHeader||this._gmail.getCurrentViewObject().getActionsHeader();var el=actionsHeader.getButton(glActionsHeader.ARCHIVE_BUTTON);if(el){this._gmail.page.simulateMouseEvent(el,"mousedown",null,null,true);this._gmail.page.simulateMouseEvent(el,"mouseup",null,null,true)}else actionsHeader.clickDropdownMenuAction(glActionsHeader.MORE_ACTIONS_DROPDOWN,glActionsHeader.ARCHIVE);setTimeout(giUtil.bind(this,function(){if(fCallback)fCallback();_qItem.release()}),500)}catch(e){if(_qItem)_qItem.release();
giLogger.warn(e,"glActionDOMBuffer.archiveThread",null,this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID)}},bulkLabel:function(actionsHeader,fLabelTest,_qItem){try{if(!_qItem){this._addQueueItem(function(qItem){this.bulkLabel(actionsHeader,fLabelTest,qItem)});return}var actionsHeader=actionsHeader||this._gmail.getCurrentViewObject().getActionsHeader();actionsHeader.bulkLabel(fLabelTest);_qItem.release()}catch(e){if(_qItem)_qItem.release();giLogger.warn(e,"glActionDOMBuffer.bulkLabel",null,this._gmail?
this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID)}}});
