var glActionDOMBuffer=giBase.extend({_queue:null,_currentQItem:null,_queueInterval:null,_gmail:null,_scrollTopRestorer:null,constructor:function(gmail){this._gmail=gmail;this._queue=[];this._scrollTopRestorer=new giScrollTopRestorer(this._gmail)},_addQueueItem:function(fStart){var me=this;var qItem={date:(new Date).valueOf(),fStart:giUtil.bind(this,fStart)};qItem.release=function(){me._releaseQueueItem(qItem)};this._queue.push(qItem);this._tryNextQueue()},_releaseQueueItem:function(qItem){for(var i=
0;i<this._queue.length;i++)if(this._queue[i]===qItem){this._queue.splice(i,1);break}if(this._currentQItem==qItem)this._currentQItem=null;this._scrollTopRestorer.reset();this._tryNextQueue()},_tryNextQueue:function(){if(this._queue.length==0||this._queue[0]==this._currentQItem)return;this._currentQItem=this._queue[0];this._currentQItem.fStart(this._currentQItem);if(!this._queueInterval)this._queueInterval=setInterval(giUtil.bind(this,this._queueIntervalFunction),500)},_queueIntervalFunction:function(){var d=
(new Date).valueOf()-1E3*10;for(var i=this._queue.length-1;i>=0;i--)if(this._queue[i].date<d){if(this._queue[i]==this._currentQItem)this._currentQItem=null;this._queue.splice(i,1)}if(this._queue.length==0){clearInterval(this._queueInterval);this._queueInterval=null}this._tryNextQueue()},addLabelToThread:function(actionsHeader,labelname,fCallback,_qItem){try{if(!_qItem){this._addQueueItem(function(qItem){this.addLabelToThread(actionsHeader,labelname,fCallback,qItem)});return}this._scrollTopRestorer.setRestorePoint();
var actionsHeader=actionsHeader||this._gmail.getCurrentViewObject().getActionsHeader();actionsHeader.setLabelsDropdownLabelState(labelname,true);_qItem.release()}catch(e){if(_qItem)_qItem.release();giLogger.warn(e,"glActionDOMBuffer.addLabelToThread",null,this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID)}},removeLabelFromThread:function(actionsHeader,labelname,fCallback,_qItem){try{if(!_qItem){this._addQueueItem(function(qItem){this.removeLabelFromThread(actionsHeader,labelname,fCallback,qItem)});
return}this._scrollTopRestorer.setRestorePoint();var actionsHeader=actionsHeader||this._gmail.getCurrentViewObject().getActionsHeader();actionsHeader.setLabelsDropdownLabelState(labelname,false);_qItem.release()}catch(e){if(_qItem)_qItem.release();giLogger.warn(e,"glActionDOMBuffer.removeLabelFromThread",null,this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID)}},addStarToThread:function(actionsHeader,fCallback,_qItem){try{if(!_qItem){this._addQueueItem(function(qItem){this.addStarToThread(actionsHeader,
fCallback,qItem)});return}this._scrollTopRestorer.setRestorePoint();var actionsHeader=actionsHeader||this._gmail.getCurrentViewObject().getActionsHeader();actionsHeader.clickDropdownMenuAction(glActionsHeader.MORE_ACTIONS_DROPDOWN,glActionsHeader.ADD_STAR);setTimeout(giUtil.bind(this,function(){if(fCallback)fCallback();_qItem.release()}),750)}catch(e){if(_qItem)_qItem.release();giLogger.warn(e,"glActionDOMBuffer.addStarToThread",null,this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID)}},removeStarFromThread:function(actionsHeader,
fCallback,_qItem){try{if(!_qItem){this._addQueueItem(function(qItem){this.removeStarFromThread(actionsHeader,fCallback,qItem)});return}var actionsHeader=actionsHeader||this._gmail.getCurrentViewObject().getActionsHeader();actionsHeader.clickDropdownMenuAction(glActionsHeader.MORE_ACTIONS_DROPDOWN,glActionsHeader.REMOVE_STAR);setTimeout(giUtil.bind(this,function(){if(fCallback)fCallback();_qItem.release()}),750)}catch(e){if(_qItem)_qItem.release();giLogger.warn(e,"glActionDOMBuffer.removeStarThread",
null,this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID)}},markThreadRead:function(actionsHeader,fCallback,_qItem){try{if(!_qItem){this._addQueueItem(function(qItem){this.markThreadRead(actionsHeader,fCallback,qItem)});return}this._scrollTopRestorer.setRestorePoint();var actionsHeader=actionsHeader||this._gmail.getCurrentViewObject().getActionsHeader();actionsHeader.clickDropdownMenuAction(glActionsHeader.MORE_ACTIONS_DROPDOWN,glActionsHeader.MARK_AS_READ);setTimeout(giUtil.bind(this,function(){if(fCallback)fCallback();
_qItem.release()}),500)}catch(e){if(_qItem)_qItem.release();giLogger.warn(e,"glActionDOMBuffer.markThreadRead",null,this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID)}},spamThread:function(actionsHeader,fCallback,_qItem){try{if(!_qItem){this._addQueueItem(function(qItem){this.spamThread(actionsHeader,fCallback,qItem)});return}this._scrollTopRestorer.setRestorePoint();var actionsHeader=actionsHeader||this._gmail.getCurrentViewObject().getActionsHeader();var el=actionsHeader.getButton(glActionsHeader.REPORT_SPAM_BUTTON);
giUIObject.simulateMouseEvent(el,"mousedown");giUIObject.simulateMouseEvent(el,"mouseup");setTimeout(giUtil.bind(this,function(){if(fCallback)fCallback();_qItem.release()}),500)}catch(e){if(_qItem)_qItem.release();giLogger.warn(e,"glActionDOMBuffer.spamThread",null,this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID)}},deleteThread:function(actionsHeader,fCallback,_qItem){try{if(!_qItem){this._addQueueItem(function(qItem){this.deleteThread(actionsHeader,fCallback,qItem)});return}this._scrollTopRestorer.setRestorePoint();
var actionsHeader=actionsHeader||this._gmail.getCurrentViewObject().getActionsHeader();var el=actionsHeader.getButton(glActionsHeader.DELETE_BUTTON);giUIObject.simulateMouseEvent(el,"mousedown");giUIObject.simulateMouseEvent(el,"mouseup");setTimeout(giUtil.bind(this,function(){if(fCallback)fCallback();_qItem.release()}),500)}catch(e){if(_qItem)_qItem.release();giLogger.warn(e,"glActionDOMBuffer.deleteThread",null,this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID)}},archiveThread:function(actionsHeader,
fCallback,_qItem){try{if(!_qItem){this._addQueueItem(function(qItem){this.archiveThread(actionsHeader,fCallback,qItem)});return}this._scrollTopRestorer.setRestorePoint();var actionsHeader=actionsHeader||this._gmail.getCurrentViewObject().getActionsHeader();var el=actionsHeader.getButton(glActionsHeader.ARCHIVE_BUTTON);if(el){giUIObject.simulateMouseEvent(el,"mousedown");giUIObject.simulateMouseEvent(el,"mouseup")}else actionsHeader.clickDropdownMenuAction(glActionsHeader.MORE_ACTIONS_DROPDOWN,glActionsHeader.ARCHIVE);
setTimeout(giUtil.bind(this,function(){if(fCallback)fCallback();_qItem.release()}),500)}catch(e){if(_qItem)_qItem.release();giLogger.warn(e,"glActionDOMBuffer.archiveThread",null,this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID)}},createLabel:function(actionsHeader,fCallback,_qItem){try{if(!_qItem){this._addQueueItem(function(qItem){this.createLabel(actionsHeader,fCallback,qItem)});return}this._scrollTopRestorer.setRestorePoint();var actionsHeader=actionsHeader||this._gmail.getCurrentViewObject().getActionsHeader();
actionsHeader.clickDropdownMenuAction(glActionsHeader.LABELS_DROPDOWN,glActionsHeader.CREATE_LABEL);var d={count:0};var me=this;d.interval=setInterval(function(){var elInput=actionsHeader.getCreateLabelInput();if(elInput||d.count++>5){if(d.count>5)giLogger.warn("Could not find Create Label Input.","glActionBuffer.createLabel",null,me._gmail?me._gmail.pageId:giLogger.UNKNOWN_PAGE_ID);clearInterval(d.interval);if(fCallback)fCallback();_qItem.release()}},200)}catch(e){if(fCallback)fCallback();if(_qItem)_qItem.release();
giLogger.warn(e,"glActionDOMBuffer.createLabel",null,this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID)}}});
