var glDataObject=giBase.extend({_rawData:null,_userLabels:null,_userName:null,_internalLabels:null,_additionalAccounts:null,_queryData:null,_threads:null,_threadData:null,_threadMessages:null,_settingsData:null,_gmail:null,constructor:function(gmail){this._rawData={};this._gmail=gmail},getAdditionalAccounts:function(){if(this._additionalAccounts==null){this._additionalAccounts=[];var rawData=this._rawData[glDataObject.ADDITIONAL_ACCOUNTS_TAG];if(rawData)for(var j=0;j<rawData[1].length;j++)this._additionalAccounts.push({name:rawData[1][j][0],
email:rawData[1][j][1]});delete this._rawData[glDataObject.ADDITIONAL_ACCOUNTS_TAG];rawData=null}return this._additionalAccounts},getUserLabels:function(){if(this._userLabels==null){this._userLabels=[];var rawData=this._rawData[glDataObject.LABEL_DATA_TAG];if(rawData){for(var j=0;j<rawData[2].length;j++)if(rawData[2][j])this._userLabels.push({name:rawData[2][j][0],unreadThreads:rawData[2][j][1],threads:rawData[2][j][2]});else giLogger.logConcern("rawData[2][j] not found.\n"+giLogger.dump(rawData[2]),
"glDataObject.getUserLabels",this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID);if(this._internalLabels!==null)delete this._rawData[glDataObject.LABEL_DATA_TAG]}rawData=null}return this._userLabels},getUserName:function(){if(this._userName==null)if(this._rawData[glDataObject.USER_NAME_TAG])this._userName=this._rawData[glDataObject.USER_NAME_TAG][1];return this._userName},getInternalLabels:function(){if(this._internalLabels==null){this._internalLabels=[];var rawData=this._rawData[glDataObject.LABEL_DATA_TAG];
if(rawData){for(var j=0;j<rawData[1].length;j++)this._internalLabels.push({name:rawData[1][j][0],unreadThreads:rawData[1][j][1]});if(this._internalLabels.length==0)giLogger.logConcern("Could not find any internal labels for LABEL_DATA_TAG - but data present\n"+giLogger.dump(rawData),"glDataObject.getInternalLabels",this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID);if(this._userLabels!==null)delete this._rawData[glDataObject.LABEL_DATA_TAG]}else giLogger.logConcern("Could not find rawData for LABEL_DATA_TAG - internal labels.\nTag: "+
glDataObject.LABEL_DATA_TAG+"\n"+giLogger.dump(this._rawData),"glDataObject.getInternalLabels",this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID);rawData=null}return this._internalLabels},getActionResponseData:function(){if(this._actionResponseData==null){this._actionResponseData={};var rawData=this._rawData[glDataObject.ACTIVITY_RESPONSE_TAG];if(rawData){this._actionResponseData.message=rawData[2];this._actionResponseData.affectedThread=rawData.length>3?rawData[3][0]:null}delete this._rawData[glDataObject.ACTIVITY_RESPONSE_TAG];
rawData=null}return this._actionResponseData},getQueryData:function(){if(this._queryData==null){this._queryData={};var rawData=this._rawData[glDataObject.QUERY_DATA_TAG];if(rawData){this._queryData.query=rawData[5];this._queryData.results=rawData[2]}delete this._rawData[glDataObject.QUERY_DATA_TAG];rawData=null}return this._queryData},getThreads:function(){if(this._threads==null){this._threads=[];var rawData=this._rawData[glDataObject.THREAD_DATA_TAG];if(rawData){var re1=/<span[^>]+?email=[^>]+?>[^<]+?<\/span>/gi;
var re2=/<span[^>]+?email=\"([^"]+?)\"[^>]*?>([^<]+?)<\/span>/i;for(var i=0;i<rawData.length;i++){var chunk=rawData[i];for(var j=3;j<chunk.length;j++){var knownContacts=[];if(chunk[j][7]&&chunk[j][7].match)if(m=chunk[j][7].match(re1))for(var k=0;k<m.length;k++){var m2=m[k].match(re2);if(m2)knownContacts.push({name:m2[2],email:giUtil.realEmail(m2[1])});else knownContacts.push({name:"Unknown",email:"unknown@unknown.unknown"})}var t={threadId:chunk[j][2],isRead:chunk[j][3]==1,isStarred:chunk[j][4]==
1,labels:chunk[j][5],contactsSnippetHtml:chunk[j][7],knownContacts:knownContacts,subjectSnippetHtml:chunk[j][9],bodySnippetHtml:chunk[j][10],attachmentsCSV:chunk[j][13],dateSnippetHtml:chunk[j][14],date:chunk[j][15],timestamp:chunk[j][16]};this._threads.push(glThread.createSimpleFromData(t,this._gmail))}}}delete this._rawData[glDataObject.THREAD_DATA_TAG];rawData=null}return this._threads},getThreadData:function(preserveData){if(this._threadData==null){var rawData=this._rawData[glDataObject.THREAD_MESSAGE_DATA_TAG];
if(rawData){var labelsHash={};var emailsHash={};var filesHash={};for(var i=0;i<rawData.length;i++){var chunk=rawData[i];if(chunk[13][9]&&chunk[13][9][1]&&chunk[13][9][1].length>0)for(var j=0;j<chunk[13][9][1].length;j++)emailsHash[giUtil.realEmail(chunk[13][9][1][j][1])]={name:chunk[13][9][1][j][0],email:giUtil.realEmail(chunk[13][9][1][j][1])};else if(chunk[5]&&chunk[6])emailsHash[giUtil.realEmail(chunk[6])]={name:chunk[5],email:giUtil.realEmail(chunk[6])};if(chunk[13][7]&&chunk[13][7][0])for(var j=
0;j<chunk[13][7][0].length;j++)filesHash[chunk[13][7][0][j][1]]=true;for(var j=0;j<chunk[9].length;j++)labelsHash[chunk[9][j]]=true}var knownContacts=[];for(e in emailsHash)knownContacts.push(emailsHash[e]);var chunk=rawData[rawData.length-1];this._threadData={labels:giUtil.hashKeysToArray(labelsHash),subjectSnippetHtml:chunk[12],dateSnippetHtml:chunk[17],date:chunk[24],timestamp:chunk[7],knownContacts:knownContacts,attachmentsCSV:giUtil.hashKeysToArray(filesHash).join(",")}}if(!preserveData){delete this._rawData[glDataObject.THREAD_MESSAGE_DATA_TAG];
rawData=null}}return this._threadData},getThreadMessages:function(){if(this._threadMessages==null){this._threadMessages=[];var rawData=this._rawData[glDataObject.THREAD_MESSAGE_DATA_TAG];if(rawData)for(var i=0;i<rawData.length;i++){var chunk=rawData[i];var recipients=null;if(chunk[13][9]&&chunk[13][9][1]&&chunk[13][9][1].length>0){recipients=[];for(var j=0;j<chunk[13][9][1].length;j++)recipients.push({name:chunk[13][9][1][j][0],email:giUtil.realEmail(chunk[13][9][1][j][1])})}var sender=null;if(chunk[6])sender=
{name:chunk[5],email:giUtil.realEmail(chunk[6])};var files=[];if(chunk[13][7]&&chunk[13][7][0])for(var j=0;j<chunk[13][7][0].length;j++){var f=chunk[13][7][0][j];files.push({attid:f[0],name:f[1],bytes:f[3],icon:f[6],url:f[9],type:f[7],preview:f[8]})}this._threadMessages.push(glThreadMessage.createFromData({messageId:chunk[1],timestamp:chunk[7],message:chunk[13][6],date:chunk[13][10],sender:sender,recipients:recipients,files:files},this._gmail))}delete this._rawData[glDataObject.THREAD_MESSAGE_DATA_TAG];
rawData=null}return this._threadMessages},getSettingsData:function(){if(!this._settingsData){var rawData=this._rawData[glDataObject.SETTINGS_TAG];if(rawData){this._settingsData={multiple_inboxes:{items:[]}};if(typeof rawData[1][0]!="string")rawData=rawData[1];var foundMultipleInboxToken=false;for(var i=0;i<rawData.length;i++)if(rawData[i][0]=="sx_ltl"){foundMultipleInboxToken=true;var tokens=rawData[i][1].split(" ");var idx=0;for(var j=0;j<tokens.length;j++){var query=decodeURIComponent(tokens[j]);
if(query){if(!this._settingsData.multiple_inboxes.items[idx])this._settingsData.multiple_inboxes.items[idx]={};this._settingsData.multiple_inboxes.items[idx].query=query;idx++}}}if(!foundMultipleInboxToken)if(rawData.toString().indexOf("sx_ltl")>-1){giLogger.log("rawData:\n"+giLogger.dump(rawData),"glDataObject.getSettingsData",this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID);giLogger.error("Failed to find multiple inbox entry in settings despite it appearing to exist (sx_ltl).","glDataObject.getSettingsData",
this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID)}}delete this._rawData[glDataObject.SETTINGS_TAG]}return this._settingsData}},{USER_NAME_TAG:"ugn",ADDITIONAL_ACCOUNTS_TAG:"cfs",LABEL_DATA_TAG:"ld",LOGIN_ACTIVITY_TAG:"la",QUERY_DATA_TAG:"ti",THREAD_DATA_TAG:"tb",THREAD_MESSAGE_DATA_TAG:"ms",ACTIVITY_RESPONSE_TAG:"a",SETTINGS_TAG:"p",createFromJSResponse:function(response,url,gmail){var url="https://mail.google.com/";response=response.replace("while(1);","");response=response.replace(/^[\n\r\s\t]+/,
"");if(giPluginManager.browserName=="mozilla"){var evalJS="var result = ("+response+")";var sb=giSafeJS.create(url);var result=giSafeJS.eval(response,sb)}else if(giPluginManager.browserName=="chrome")eval("var result = ("+response+")");if(typeof result!="object")giLogger.error("Parsing JS response does not result in an object. Response:\n"+response,"glDataObject.createFromJSResponse",gmail.pageId);return glDataObject.createFromData(result[0],gmail)},createFromHTMLResponse:function(response,url,gmail){try{response=
response.replace(/top\./g,"giSpecial.").replace(/window\./g,"giBreakOnCall.");response=response.replace(/\<\!--/g,"");response=response.replace(/\/\/--\>/g,"");response=response.replace(/<[^>]+?>/g,"");response=response.replace(/[\r\n]/g,"");var data=null;var realArray=Array;var giSpecial={GG_iframeFn:function(junk,data){if(!giSpecial.data)giSpecial.data=[];giSpecial.data.push(data)},_A:function(){var a;a=arguments.length==1&&typeof arguments[0]=="number"?[arguments[0]]:realArray.apply(null,arguments);
return a}};if(giPluginManager.browserName=="mozilla"){var sb=giSafeJS.create("https://mail.google.com/");var realArray=Array;sb.window=null;sb.top={giSpecial:giSpecial};giSafeJS.eval(response,sb);data=sb.top.giSpecial.data}else if(giPluginManager.browserName=="chrome"){eval(response);var data=giSpecial.data}if(typeof data!="object")throw new Error("Parsing HTML does not result in an object.");var o=glDataObject.createFromData(data,gmail);return o}catch(e){giLogger.warn("Malformed data - "+e+"\n"+
response,"glDataObject.createFromHTMLResponse",gmail.pageId)}},createFromData:function(data,gmail){var viewDataObject=new glDataObject(gmail);for(var i=0;i<data.length;i++){if(!data[i]||!data[i].length)continue;var chunk=data[i];var chunkType=chunk[0];switch(chunkType){case glDataObject.USER_NAME_TAG:case glDataObject.ADDITIONAL_ACCOUNTS_TAG:case glDataObject.LABEL_DATA_TAG:case glDataObject.LOGIN_ACTIVITY_TAG:case glDataObject.QUERY_DATA_TAG:case glDataObject.ACTIVITY_RESPONSE_TAG:case glDataObject.SETTINGS_TAG:viewDataObject._rawData[chunkType]=
chunk;break;case glDataObject.THREAD_DATA_TAG:if(viewDataObject._rawData[chunkType]==undefined)viewDataObject._rawData[chunkType]=[];viewDataObject._rawData[chunkType].push(chunk);break;case glDataObject.THREAD_MESSAGE_DATA_TAG:if(viewDataObject._rawData[chunkType]==undefined)viewDataObject._rawData[chunkType]=[];viewDataObject._rawData[chunkType].push(chunk);break;default:break}}return viewDataObject}});
