var glEnvironment=giBase.extend({lastUpdate:null,_gmail:null,_environmentData:null,threadListCache:null,_requestedRefreshTL:null,_scrollTopRestorer:null,lastSentThreadId:null,connect:function(gmail){this._gmail=gmail;this._environmentData={};this._scrollTopRestorer=new giScrollTopRestorer(this._gmail);var pageViewData=gmail.page.getViewData();if(pageViewData){var viewData=glDataObject.createFromData(pageViewData,this._gmail);this.updateFromData(viewData,true)}this._gmail.trafficWatcher.addEventListener(glTrafficWatcher.SEND_MESSAGE_REQUEST_COMPLETED,
this._handleSendMessageRequest,this);this._gmail.actions.addEventListener(glActionManager.ENVIRONMENT_CHANGED,this._actionManagerEvent,this);this._gmail.actions.addEventListener(glActionManager.ADD_LABEL.eventName,this._actionManagerEvent,this);this._connectToPageWrapper()},shutdown:function(){this._scrollTopRestorer.unload();this._scrollTopRestorer=null;this._environmentData=null;this._gmail=null;this._removeAllListeners()},update:function(){giLogger.log("st","glEnvironment.update",this._gmail?this._gmail.pageId:
giLogger.UNKNOWN_PAGE_ID);var request=glRequest.createSimpleRequest(this._gmail);request.run(false);if(request.errors&&request.errors.length)giLogger.error("Update request had errors:\n"+giLogger.dump(request.errors,true),"glEnvironment.update",this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID);this.updateFromData(request.data)},updateFromData:function(data,full){giLogger.log("st","glEnvironment.updateFromData",this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID);this.lastUpdate=new Date;
if(this.hasEventListener(glEnvironment.ENVIRONMENT_CHANGED)||full){var changed=[];var compare={userName:data.getUserName(),additionalAccounts:data.getAdditionalAccounts(),userLabels:data.getUserLabels(),internalLabels:data.getInternalLabels()};for(var set in compare){if(compare[set]==null)continue;var currentData=this._environmentData[set];var newData=compare[set];var isNew=false;if(currentData&&currentData.length==newData.length)for(var i=0;i<newData.length;i++){for(var prop in newData[i])if(currentData[i][prop]!=
newData[i][prop]){isNew=true;break}if(isNew)break}else isNew=true;if(isNew){changed.push(set);this._environmentData[set]=compare[set]}}if(changed.length)this.dispatchEvent({name:glEnvironment.ENVIRONMENT_CHANGED,changed:changed})}else{this._environmentData["userName"]=data.getUserName();this._environmentData["additionalAccounts"]=data.getAdditionalAccounts();this._environmentData["userLabels"]=data.getUserLabels();this._environmentData["internalLabels"]=data.getInternalLabels()}this.dispatchEvent({name:glEnvironment.ENVIRONMENT_DATA_RECEIVED})},
getAccount:function(){if(typeof this._environmentData["account"]=="undefined")this._environmentData["account"]=this._gmail.page.getGlobal(10);return this._environmentData["account"]},getUserLabels:function(){return this._environmentData.userLabels},getInternalLabels:function(){return this._environmentData.internalLabels},getUserName:function(){return this._environmentData.userName},getIKValue:function(){if(typeof this._environmentData["ikValue"]=="undefined")this._environmentData["ikValue"]=this._gmail.page.getGlobal(9);
return this._environmentData["ikValue"]},getRequestURL:function(){if(typeof this._environmentData["requestURL"]=="undefined")this._environmentData["requestURL"]=this._gmail.page.getGlobal(7);return this._environmentData["requestURL"]},_connectToPageWrapper:function(){this._gmail.page.addEventListener(glPageWrapper.VIEW_CHANGED,this._viewChanged,this)},requestRefreshTL:function(){if(this._gmail.page.getActiveViewType()=="tl"){this._requestedRefreshTL=false;var actionsHeader=this._gmail.getCurrentViewObject().getActionsHeader();
var el=null;var hash=this._gmail.page.locationHash();var useInbox=false;if(hash.indexOf("#inbox")>-1)if(hash.indexOf("#inbox/p")>-1)var el=actionsHeader.getButton(glActionsHeader.REFRESH_BUTTON);else{var el=this._gmail.getUIObject("navBar").getNavLink(glNavBar.INBOX);var useInbox=true}else var el=actionsHeader.getButton(glActionsHeader.REFRESH_BUTTON);if(el)if(useInbox){if(this._requestRefreshDblClickTimer)clearTimeout(this._requestRefreshDblClickTimer);var me=this;this._requestRefreshDblClickTimer=
setTimeout(function(){giUIObject.simulateMouseEvent(el,"click");me._requestRefreshDblClickTimer=null},500)}else{giUIObject.simulateMouseEvent(el,"mousedown");giUIObject.simulateMouseEvent(el,"mouseup");giUIObject.simulateMouseEvent(el,"click")}this._scrollTopRestorer.setRestorePoint()}else this._requestedRefreshTL=true},_viewChanged:function(){if(this._requestedRefreshTL&&this._gmail.page.getActiveViewType()=="tl")this.requestRefreshTL();if(this._requestRefreshDblClickTimer){clearTimeout(this._requestRefreshDblClickTimer);
this._requestRefreshDblClickTimer=null}},_handleSendMessageRequest:function(evt){var actionResponse=evt.responseData.getActionResponseData();if(actionResponse&&actionResponse.affectedThread){this.lastSentThreadId=actionResponse.affectedThread;this.dispatchEvent({name:glEnvironment.EMAIL_SENT,threadId:actionResponse.affectedThread})}this.updateFromData(evt.responseData)},_actionManagerEvent:function(evt){if(!evt.label)return;var events=[];if(evt.action==glActionManager.CREATE_LABEL||evt.name==glActionManager.ADD_LABEL.eventName){var found=
false;for(var i=0;i<this._environmentData.userLabels.length;i++)if(this._environmentData.userLabels[i].name==evt.label){var found=true;break}if(!found){this._addUserLabelInPlace({name:evt.label});events.push({name:glEnvironment.CREATE_LABEL,label:evt.label});events.push({name:glEnvironment.ENVIRONMENT_CHANGED})}}if(evt.action==glActionManager.RENAME_LABEL){var labelData=null;for(var i=0;i<this._environmentData.userLabels.length;i++)if(this._environmentData.userLabels[i].name==evt.label){labelData=
this._environmentData.userLabels[i];labelData.name=evt.newLabel;this._environmentData.userLabels.splice(i,1);break}if(labelData)this._addUserLabelInPlace(labelData);events.push({name:glEnvironment.RENAME_LABEL,label:evt.label,newLabel:evt.newLabel});events.push({name:glEnvironment.ENVIRONMENT_CHANGED})}if(evt.action==glActionManager.DELETE_LABEL){for(var i=this._environmentData.userLabels.length-1;i>=0;i--)if(this._environmentData.userLabels[i].name==evt.label)this._environmentData.userLabels.splice(i,
1);events.push({name:glEnvironment.DELETE_LABEL,label:evt.label});events.push({name:glEnvironment.ENVIRONMENT_CHANGED})}if(events.length>0)try{for(var i=0;i<events.length;i++)this.dispatchEvent(events[i])}catch(e){giLogger.warn(e,"glEnvironment._actionManagerEvent",null,this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID)}},_addUserLabelInPlace:function(newLabelData){var name=newLabelData.name.toLowerCase();var added=false;for(var i=0;i<this._environmentData.userLabels.length;i++)if(this._environmentData.userLabels[i].name.toLowerCase()>
name){this._environmentData.userLabels.splice(i,0,newLabelData);added=true;break}if(!added)this._environmentData.userLabels.push(newLabelData)}},{CREATE_LABEL:"create_label",RENAME_LABEL:"rename_label",DELETE_LABEL:"delete_label",EMAIL_SENT:"email_sent",ACTION_PERFORMED:"action_performed",ENVIRONMENT_CHANGED:"environment_changed",ENVIRONMENT_DATA_RECEIVED:"environment_data_updated"});glEnvironment.implement(giEventDispatcher);
