var glPageWrapper=giBase.extend({_gmail:null,_uiIsReady:false,_injectedElem:null,_injectedCodeElem:null,_testForInjectedInterval:null,_testForInjectedIntervalCount:null,connect:function(gmail){this._gmail=gmail;giLogger.log("st","glPageWrapper.connect",this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID);var me=this;giFileIO.readFile("content/js/gmail/injected-code.js",null,null,function(fileText){me._connect_postReadInjected(fileText)})},_connect_postReadInjected:function(fileText){try{giLogger.log("retrieved injected-code.js from file system",
"glPageWrapper._connect_postReadInjected",this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID);try{this._injectCode(fileText)}catch(e){var doc=this._gmail?this._gmail.doc:null;return giPluginManager.docFail(this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID,doc,"glPageWrapper._connect_postReadInjected.[inject-code]",e.toString())}this._testForInjectedIntervalCount=0;var me=this;this._testForInjectedInterval=setInterval(function(){me._connect_testForInjected()},100);this._connect_testForInjected();
giLogger.log("fn","glPageWrapper._connect_postReadInjected",this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID)}catch(e){giLogger.warn(e,"glPageWrapper._connect_postReadInjected",null,this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID)}},_connect_testForInjected:function(){try{this._injectedElem=this._gmail.doc.getElementById("_gmailInjected");var elemErr=this._gmail.doc.getElementById("_gmailInjectedInitError");if(elemErr)giLogger.error("Error in injected code initialization (pageWrapper.init): "+
elemErr.getAttribute("initError"),"glPageWrapper._connect_testForInjected",this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID);if(this._injectedElem){clearInterval(this._testForInjectedInterval);this._testForInjectedInterval=null;var me=this;this._injectedListener=function(e){me._eventReceived(e)};this._injectedElem.addEventListener("glGmailEventDispatched",this._injectedListener,false,true);this.dispatchEvent({name:glPageWrapper.LOADED});this._runInPage("start")}else if(this._testForInjectedIntervalCount++>
150){clearInterval(this._testForInjectedInterval);this._testForInjectedInterval=null;var doc=this._gmail?this._gmail.doc:null;return giPluginManager.docFail(this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID,doc,"glPageWrapper._connect_testForInjected.[inject-code_no-element-added]","this._injectedElem is null - can't talk to Gmail.\nEither injected-code.js could not be added to page, or it crashed doing so before the element could be created. Or browser can't read DOM correctly.")}}catch(e){giLogger.warn(e,
"glPageWrapper._connect_testForInjected",null,this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID)}},_injectCode:function(code){if(this._injectedCodeElem){this._injectedCodeElem.parentNode.removeChild(this._injectedCodeElem);this._injectedCodeElem=null}this._injectedCodeElem=this._gmail.doc.createElement("SCRIPT");this._injectedCodeElem.setAttribute("type","text/javascript");this._injectedCodeElem.innerHTML=code;this._injectedCodeElem.firebugIgnore=true;var elHead=this._gmail.doc.getElementsByTagName("HEAD")[0];
if(elHead)elHead.appendChild(this._injectedCodeElem);else this._gmail.doc.documentElement.appendChild(this._injectedCodeElem)},isLoaded:function(){return!!this._injectedElem},disconnect:function(){if(this._testForInjectedInterval)clearInterval(this._testForInjectedInterval);if(this._injectedElem){this._injectedElem.removeEventListener("glGmailEventDispatched",this._injectedListener,true);this._injectedElem.parentNode.removeChild(this._injectedElem)}this._injectedElem=null;this._injectedListener=null;
this._gmail=null},reloadGmail:function(){return this._runInPage("reloadGmail")},getGlobal:function(offset){return this._runInPage("getGlobal",offset)},getCookie:function(){if(!this._cookieCache)this._cookieCache=this._runInPage("getCookie");return this._cookieCache},getViewData:function(){return this._runInPage("getViewData")},getActiveViewType:function(){return this._runInPage("getActiveViewType")},locationHref:function(href){if(typeof href!="undefined")this._gmail.doc.defaultView.top.location.href=
href;return this._gmail.doc.defaultView.top.location.href},locationHash:function(hash){if(typeof hash!="undefined")this._gmail.doc.defaultView.top.location.hash=hash;return this._gmail.doc.defaultView.top.location.hash},locationProtocol:function(protocol){if(typeof protocol!="undefined")this._gmail.doc.defaultView.top.location.protocol=protocol;return this._gmail.doc.defaultView.top.location.protocol},locationIsInbox:function(url){if(!url)url=this.locationHash();return/#inbox/.test(url)||/#$/.test(url)},
addCSS:function(cssFile){if(!this._uiIsReady)return;var doc=this._gmail.canvasDocument;var elLink=doc.createElement("link");elLink.type="text/css";elLink.href=cssFile;elLink.rel="stylesheet";doc.getElementsByTagName("head")[0].appendChild(elLink)},getViewRoot:function(){var elems=this._gmail.canvasDocument.getElementsByClassName("glViewRoot");if(!elems.length)return null;else return elems[0]},isUIReady:function(){return this._uiIsReady},_runInPage:function(func){if(!this._injectedElem)giLogger.error("Could not call '"+
func+"' because glPageWrapper not loaded yet (this._injectedElem is null).","glPageWrapper._runInPage",this._gmail.pageId);this._injectedElem.setAttribute("func",func);this._injectedElem.setAttribute("params",arguments.length-1);for(var i=1;i<arguments.length;i++)this._injectedElem.setAttribute("param"+i,arguments[i]);var evt=this._gmail.doc.createEvent("Event");evt.initEvent("glGmailRunFunction",true,false);this._injectedElem.dispatchEvent(evt);var returnValue=null;if(this._injectedElem.hasAttribute("return")){var returnValueString=
this._injectedElem.getAttribute("return");returnValue=giJson.decode(returnValueString).data}this._injectedElem.removeAttribute("func");this._injectedElem.removeAttribute("return");this._injectedElem.removeAttribute("params");for(var i=1;i<arguments.length;i++)this._injectedElem.removeAttribute("param"+i);return returnValue},_eventReceived:function(evt){try{var eventName=this._injectedElem.getAttribute("event");var data=this._injectedElem.getAttribute("eventData");var logMsg="Event: "+eventName+", url: "+
this.locationHref();var event={name:eventName};switch(eventName){case "ui_ready":this._uiIsReady=true;case "view_changed":event.view=this.getActiveViewType();logMsg+=", view: "+event.view;break;case "log":giLogger.log(data,"injected-code.js",this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID);return;case "logConcern":giLogger.logConcern(data,"injected-code.js",this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID);return;case "warn":giLogger.warn(data,"injected-code.js",null,this._gmail?this._gmail.pageId:
giLogger.UNKNOWN_PAGE_ID);return;case "logHTML":var dataObj=giJson.decode(data);giLogger.logHTML(dataObj.html,dataObj.systemLevelInfo,null,dataObj.approved,this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID);return}giLogger.log(logMsg,"glPageWrapper._eventReceived",this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID);this.dispatchEvent(event)}catch(e){giLogger.warn(e,"glPageWrapper._eventReceived",null,this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID)}}},{LOADED:"loaded",UI_READY:"ui_ready",
VIEW_CHANGED:"view_changed",getGlobalStatic:function(doc,pageId,global){if(typeof global=="string")switch(global){case "account":global=10;break;case "url":global=11;break;case "gmailversion":global=2;break}var elBody=doc.getElementsByTagName("BODY")[0];var id=(new Date).valueOf();var el=doc.createElement("DIV");el.id=id;elBody.appendChild(el);var script="var el = document.getElementById('"+id+"');\n";script+="el.setAttribute('account', top.GLOBALS["+global+"]);";var elScript=doc.createElement("SCRIPT");
elScript.innerHTML=script;elBody.appendChild(elScript);var val=el.getAttribute("account");elBody.removeChild(elScript);elBody.removeChild(el);elBody=null;elScript=null;el=null;if(!val)giLogger.logConcern("Could not find GLOBAL value: "+global,"glPageWrapper.getGlobalStatic",pageId);return val}});glPageWrapper.implement(giEventDispatcher);
