var glSearch=giBase.extend({conditions:null,_gmail:null,_request:null,_searchType:null,_isBackgroundRunning:false,constructor:function(gmail){this._gmail=gmail;this.setSearchType();this.conditions=new glSearchConditions},unload:function(){this._reset();this._removeAllListeners()},find:function(condition){return this.addCondition(condition)},addCondition:function(condition){this.conditions.addCondition(condition);return this},setSearchType:function(t){if(typeof t=="undefined")t="search";this._searchType=
t},run:function(){var searchBox=this._gmail.getUIObject("searchBox");searchBox.setSearch(this.getQuery());searchBox.submit()},runBackground:function(start,num,contextData){if(typeof start!="number")start=0;if(typeof num!="number")num=25;this._reset();this._isBackgroundRunning=true;if(this._searchType=="search")this._request=new glRequest(this._gmail,{start:start,num:num,search:"query",view:"tl",q:this.getQuery()},null,contextData);else this._request=new glRequest(this._gmail,{start:start,num:num,
search:this._searchType,view:"tl"},null,contextData);this._request.addEventListener(glRequest.COMPLETED,this._backgroundSearchCallback,this);this._request.run()},_backgroundSearchCallback:function(event){this._isBackgroundRunning=false;this.dispatchEvent({name:glSearch.COMPLETED,contextData:event.contextData})},runCount:function(){this.runBackground(0,0)},getNumberResults:function(){if(!this._request)giLogger.error("this._request not defined","glSearch.getNumberResults",this._gmail?this._gmail.pageId:
giLogger.UNKNOWN_PAGE_ID);if(this._request.data){var queryData=this._request.data.getQueryData();return queryData.results}else return 0},getResults:function(){if(!this._request)giLogger.error("this._request not defined","glSearch.getResults",this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID);if(this._request.data){var threads=this._request.data.getThreads();if(!threads||threads.length==0)giLogger.logConcern("No threads in search results - current query: "+this.getQuery(),"glSearch.getResults",
this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID);return threads}else{giLogger.logConcern("No data in search results - current query: "+this.getQuery(),"glSearch.getResults",this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID);return[]}},getQuery:function(){return this.conditions.toString()},matchThread:function(thread){return this.conditions.matchThread(thread)},isBackgroundRunning:function(){return this._isBackgroundRunning},_reset:function(){this._isBackgroundRunning=false;if(this._request){this._request.removeEventListener(glRequest.COMPLETED,
this._backgroundSearchCallback);this._request=null}}},{COMPLETED:"completed",l:function(label,inhibitEncode){return"label:"+label.toLowerCase().replace(/[\/\s\(\)\&\|]/g,"-")},getQueryFromUrl:function(gmail){var url=gmail.page.locationHref();url=url.replace(/\+/g," ");if(/(#search)/.test(url)){var match=url.match(/\/#search\/(.+?)($|\/\w+$)/);if(match)return decodeURIComponent(match[1])}else if(/(#label)/.test(url)){var match=url.match(/#label\/(.+?)($|\/\w+$)/);if(match)return glSearch.l(decodeURIComponent(match[1]))}else if(/#create-filter/.test(url)){var match=
url.match(/#create-filter\/(.+?)($|\/\w+$)/);if(match){var query=match[1];query=decodeURIComponent(query.replace(/=/g,":"));return query}}else{if(/#inbox/.test(url)||/#$/.test(url))return"in:inbox";if(/#sent/.test(url))return"in:sent";if(/#spam/.test(url))return"in:spam";if(/#chats/.test(url))return"is:chat";if(/#starred/.test(url))return"is:starred"}return""},restrictToUser:function(userids,fromOrTo){if(typeof userids=="string")userids=[userids];var cFrom=new glSearchOrConditions;var cTo=new glSearchOrConditions;
if(userids instanceof Array)for(var i=0;i<userids.length;i++){cFrom.addCondition("from:"+userids[i]);cTo.addCondition("to:"+userids[i])}else for(e in userids){cFrom.addCondition("from:"+e);cTo.addCondition("to:"+e)}var c=null;if(fromOrTo&&fromOrTo=="OR")c=new glSearchOrConditions;else c=new glSearchAndConditions;c.addCondition(cFrom);c.addCondition(cTo);return c},searchDate:function(ms){var d=new Date(ms);return d.getFullYear()+"/"+(d.getMonth()+1)+"/"+d.getDate()},joinLabels:function(labels,joinType,
incBrackets){var c=null;if(!joinType||joinType.toLowerCase()=="or")c=new glSearchOrConditions;else c=new glSearchAndConditions;if(labels)for(var i=0;i<labels.length;i++)c.addCondition(glSearch.l(labels[i]));return c}});glSearch.implement(giEventDispatcher);
var glSearchConditions=giBase.extend({conditions:null,_queryString:null,_strictMode:true,constructor:function(){if(arguments.length)this.conditions=arguments;else this.conditions=[]},strictMode:function(mode,incChildren){if(typeof mode!="undefined")this._strictMode=mode;if(incChildren)for(var i=0;i<this.conditions.length;i++)if(this.conditions[i]instanceof glSearchConditions)this.conditions[i].strictMode(mode,incChildren);return this._strictMode},addCondition:function(condition){this.conditions.push(condition);
this._queryString=null},removeCondition:function(condition){for(var i=this.conditions.length-1;i>=0;i--)if(this.conditions[i]==condition){this.conditions.splice(i,1);break}},toString:function(){if(this._queryString===null)this._queryString=this._toQueryString();return this._queryString},matchThread:function(thread,type){if(typeof type=="undefined")type="and";var pass=null;if(this.conditions.length==0)pass=true;else for(var i=0;i<this.conditions.length;i++){if(pass!==null){if(type=="and"&&pass===false)return false;
if(type=="or"&&pass===true)return true}pass=null;if(this.conditions[i]instanceof glSearchConditions)pass=this.conditions[i].matchThread(thread);else if(typeof this.conditions[i]=="string"){var term=this.conditions[i];var negOffset=0;if(term.indexOf("-")==0&&term.indexOf(":")>0)negOffset=1;if(term=="")pass=true;else if(/^-?label:/.test(term)){var re=RegExp("(^|[^A-Z0-9-])"+term.substr(6+negOffset)+"([^A-Z0-9-]|$)","i");pass=re.test(thread.labels.toString().replace(/[\/\s\(\)]/g,"-"))}else if(/^-?has:attachment/.test(term))pass=
!!thread.attachmentsCSV;else if(/^-?in:inbox/.test(term))pass=/\^i/.test(thread.labels.toString());else if(/^-?in:anywhere/.test(term))pass=true;else if(/^-?in:trash/.test(term))pass=/\^k/.test(thread.labels.toString());else if(/^-?in:spam/.test(term))pass=/\^s/.test(thread.labels.toString());else if(/^-?is:starred/.test(term))pass=thread.isStarred;else if(/^-?is:unread/.test(term))pass=!thread.isRead;else if(/^-?is:read/.test(term))pass=thread.isRead;else if(/^-?is:chat/.test(term))pass=/\^b/.test(thread.labels.toString());
else if(/^-?filename:/.test(term))pass=thread.attachmentsCSV&&thread.attachmentsCSV.indexOf(term.substr(9+negOffset))>-1;else if(/^-?after:/.test(term)){var d=new Date(term.substr(6+negOffset));var dThread=new Date(thread.timestampJS);pass=dThread.valueOf()>d.valueOf()}else if(/^-?before:/.test(term)){var d=new Date(term.substr(7+negOffset));var dThread=new Date(thread.timestampJS);pass=dThread.valueOf()<d.valueOf()}else if(/^-?subject:/.test(term)){var term=term.substr(8+negOffset);pass=this._matchThread_handleComplexTermValue(thread,
"subject:",term,function(thread,value){if(m=/^\"([^"]+)\"$/.exec(value))value=m[1];return thread.subjectSnippetHtml.indexOf(value)>-1})}else if(/^-?to:/.test(term)){term=term.substr(3+negOffset);if(thread.isCompleteLoaded())pass=this._matchThread_handleComplexTermValue(thread,"to:",term,function(thread,value){return thread.hasContact(value,false,true)});else if(!this._strictMode)pass=thread.hasContact([term])}else if(/^-?from:/.test(term)){term=term.substr(5+negOffset);if(thread.isCompleteLoaded())pass=
this._matchThread_handleComplexTermValue(thread,"from:",term,function(thread,value){return thread.hasContact(value,true,false)});else if(!this._strictMode)pass=thread.hasContact([term])}else if(thread.isCompleteLoaded()||!this._strictMode){term=term.replace(/\"/g,"");if(m=/^\(([^)]+)\)$/.exec(term))term=m[1];pass=thread.hasSearchTerm(term)}if(pass===null)throw new Error("Impossible match - could not match individual condition ("+this.conditions[i]+")");if(negOffset==1)pass=!pass}else throw new Error("Impossible match - unknown condition type");
}return pass},_matchThread_handleComplexTermValue:function(thread,term,value,testFunction){var pass=false;if(m=/^\"([^"]+)\"$/.exec(value))if(/\([^)]+\)/.test(value)||/ OR /i.test(value)){var searchConditions=glSearchConditions.createFromSearchString(m[1],term);pass=searchConditions.matchThread(thread)}else pass=testFunction(thread,value);else if(m=/^\(([^)]+)\)$/.exec(value)){var searchConditions=glSearchConditions.createFromSearchString(m[1],term);pass=searchConditions.matchThread(thread)}else pass=
testFunction(thread,value);return pass},canMatchThreads:function(testThread,gmail){if(!testThread){testThread=new glThread(gmail);testThread.labels=[];testThread.knownContacts=[]}try{this.matchThread(testThread)}catch(e){return false}return true},_toQueryString:function(seperator){var queryString=seperator?"(":"";for(var i=0;i<this.conditions.length;i++){if(!this.conditions[i])continue;if(typeof this.conditions[i]=="string")queryString+=this.conditions[i];else if(this.conditions[i].toString)queryString+=
this.conditions[i].toString();else giLogger.error("Invalid condition","glSearchConditions._toQueryString",this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID);if(i<this.conditions.length-1)queryString+=seperator?seperator:" "}if(seperator)queryString+=")";return queryString}},{createFromSearchString:function(str,prefix,substitutions){if(typeof prefix!="string")prefix="";var searchConditions=null;var substitutions=substitutions||{_idx:0};str=str.replace(/ AND /gi," ");while(m=str.match(/(\"[^"]+\")/)){var code=
String.fromCharCode(250)+substitutions._idx++;substitutions[code]=m[1];str=str.replace(m[1],code)}var bracketItems=glSearchConditions.extractBrackets(str,function(s,i){if(i-1>=0&&s[i-1]==":")return true;return false});for(var i=0;i<bracketItems.length;i++){var code=String.fromCharCode(250)+substitutions._idx++;substitutions[code]=bracketItems[i];str=str.replace(bracketItems[i],code)}var bracketItems=glSearchConditions.extractBrackets(str);for(var i=0;i<bracketItems.length;i++){var code=String.fromCharCode(251)+
substitutions._idx++;substitutions[code]=bracketItems[i];str=str.replace(bracketItems[i],code)}if(/\sOR\s/i.test(str)){searchConditions=new glSearchOrConditions;var tokens=str.split(/\sOR\s/i);for(var i=0;i<tokens.length;i++){var childSearchConditions=glSearchConditions.createFromSearchString(tokens[i],prefix,substitutions);if(childSearchConditions)searchConditions.addCondition(childSearchConditions)}}else{searchConditions=new glSearchAndConditions;var tokens=str.split(" ");for(var i=0;i<tokens.length;i++){var re=
new RegExp("("+String.fromCharCode(251)+"\\d+)");if(m=re.exec(tokens[i])){tokens[i]=tokens[i].replace(m[1],substitutions[m[1]]);tokens[i]=tokens[i].substr(1,tokens[i].length-2);var childSearchConditions=glSearchConditions.createFromSearchString(tokens[i],prefix,substitutions);if(childSearchConditions)searchConditions.addCondition(childSearchConditions)}else{var re=new RegExp("("+String.fromCharCode(250)+"\\d+)");while(m=re.exec(tokens[i]))tokens[i]=tokens[i].replace(m[1],substitutions[m[1]]);searchConditions.addCondition(prefix+
tokens[i])}}}return searchConditions},extractBrackets:function(str,openCondition){var container={start:-1,end:-1,pdepth:0};var containedItems=[];for(var i=0;i<str.length;i++)if(str[i]=="(")if(container.pdepth==0){if(!openCondition||openCondition(str,i)){container.start=i;container.pdepth=container.pdepth+1}}else container.pdepth=container.pdepth+1;else if(str[i]==")"&&container.pdepth>0){container.pdepth=container.pdepth-1;if(container.pdepth==0){container.end=i+1;containedItems.push(str.substring(container.start,
container.end))}}return containedItems}});var glSearchAndConditions=glSearchConditions.extend({matchThread:function(thread){return this.base(thread,"and")},toString:function(){if(this._queryString===null)this._queryString=this._toQueryString(" AND ");return this._queryString}});var glSearchOrConditions=glSearchConditions.extend({matchThread:function(thread){return this.base(thread,"or")},toString:function(){if(this._queryString===null)this._queryString=this._toQueryString(" OR ");return this._queryString}});
