var glThreadContainer=giBase.extend({threads:null,preventUnload:false,_main:null,_search:null,_searching:false,_complete:false,_cancel:null,_totalDesired:null,_updateTimeout:null,constructor:function(main,search){this._main=main;this._search=search;this.threads=[];this._main.gmail.actions.addEventListener(glActionManager.THREAD_CHANGED,this._threadChanged,this);this._main.gmail.actions.addEventListener(glActionManager.MESSAGE_CHANGED,this._messageChanged,this);this._main.gmail.environment.addEventListener(glEnvironment.RENAME_LABEL,
this._environmentLabelChanged,this);this._main.gmail.environment.addEventListener(glEnvironment.DELETE_LABEL,this._environmentLabelChanged,this);this._search.addEventListener(glSearch.COMPLETED,this._searchComplete,this)},unload:function(){if(this.preventUnload)return;if(this.threads)this.threads=null;this._main.gmail.actions.removeEventListener(glActionManager.THREAD_CHANGED,this._threadChanged,this);this._main.gmail.actions.removeEventListener(glActionManager.MESSAGE_CHANGED,this._messageChanged,
this);this._main.gmail.environment.removeEventListener(glEnvironment.RENAME_LABEL,this._environmentLabelChanged,this);this._main.gmail.environment.removeEventListener(glEnvironment.DELETE_LABEL,this._environmentLabelChanged,this);if(this._search){this._search.removeEventListener(glSearch.COMPLETED,this._searchComplete,this);this._search=null}},search:function(total,num){num=num||25;total=total||glThreadContainer.MAX_THREADS_ALLOWED;if(num>total)num=total;if(this._searching)return;if(this._complete||
this.threads.length>=total)return;if(this._adjustThreadsQueue){for(var i=0;i<this._adjustThreadsQueue.length;i++)this._adjustThreadsQueue[i].cancelled=true;this._adjustThreadsQueue.length=0}this._totalDesired=total;this._cancel=false;this._searching=true;this.dispatchEvent({name:glThreadContainer.NEW_SEARCH});this._search.runBackground(this.threads.length,num,{num:num})},_searchComplete:function(event){var threads=this._search.getResults();var num=event.contextData.num;this.threads=this.threads.concat(threads);
if(threads.length<num||this.threads.length>=this._totalDesired||this._cancel){this._searching=false;if(threads.length<num)this._complete=true;this.dispatchEvent({name:glThreadContainer.LOADED,newThreads:threads})}else{this.dispatchEvent({name:glThreadContainer.LOADING_UPDATE,newThreads:threads});var me=this;setTimeout(function(){me._searchCompleteRunNext(num,{num:num})},500)}this._cancel=false},_searchCompleteRunNext:function(num,contextData){this._search.runBackground(this.threads.length,num,contextData)},
getNumberThreads:function(type){switch(type){case glThreadContainer.COUNT_TOTAL_DESIRED:return this._totalDesired;break;case glThreadContainer.COUNT_TOTAL_CALCULATED:return this._search.getNumberResults();break;default:return this.threads.length}},cancelSearch:function(){this._cancel=true},isSearching:function(){return this._searching},isComplete:function(){return this._complete},update:function(newSearch){if(newSearch){if(this._search){this._search.removeEventListener(glSearch.COMPLETED,this._searchComplete,
this);this._search=null}this._search=newSearch;this._search.addEventListener(glSearch.COMPLETED,this._searchComplete,this)}var me=this;clearTimeout(this._updateTimeout);this._updateTimeout=setTimeout(giUtil.bind(this,function(){try{this.threads.length=0;this._complete=false;this.search()}catch(e){giLogger.warn(e,"glThreadContainer.update",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}}),100)},_threadChanged:function(evt){try{if(!(evt.thread||evt.item))return;var addedThreads=[];var updatedThreads=
[];var removedThreads=[];var thread=null;if(evt.threadObject)for(var i=0;i<this.threads.length;i++){if(evt.threadObject.hasId(this.threads[i].threadId)){thread=this.threads[i];break}}else for(var i=0;i<this.threads.length;i++)if(this.threads[i].hasId(evt.thread)){thread=this.threads[i];break}if(thread){var matchError=false;if(thread.updateFromEvent(evt)){updatedThreads.push(thread);try{if(thread.isDeleted()||!this._search.matchThread(thread)){this.threads.splice(i--,1);removedThreads.push(thread)}}catch(e){matchError=
e.toString()}}if(updatedThreads.length>0)if(matchError){giLogger.logConcern("#PERFWATCH matchError causes big update: "+e,"glThreadContainer._threadChanged",this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID);this.update()}else this.dispatchEvent({name:glThreadContainer.CHANGED,addedThreads:addedThreads,updatedThreads:updatedThreads,removedThreads:removedThreads,actionEvent:evt})}else{var inhibit=false;if(evt.action===glActionManager.ADD_LABEL||evt.action===glActionManager.REMOVE_LABEL){if(this._search.getQuery().indexOf(glSearch.l(evt.label))==
-1)inhibit=true}else if(evt.action==glActionManager.ARCHIVE||evt.action==glActionManager.MOVE_INBOX){if(this._search.getQuery().indexOf("in:inbox")==-1)inhibit=true}else if(evt.action==glActionManager.DELETE){if(this._search.getQuery().indexOf("in:trash")==-1)inhibit=true}else if(evt.action==glActionManager.REPORT_SPAM||evt.action==glActionManager.NOT_SPAM){if(this._search.getQuery().indexOf("in:spam")==-1)inhibit=true}else if(evt.action==glActionManager.MARK_AS_READ){if(this._search.getQuery().indexOf("is:unread")==
-1&&this._search.getQuery().indexOf("is:read")==-1)inhibit=true}else if(evt.action==glActionManager.STAR||evt.action==glActionManager.UNSTAR)if(this._search.getQuery().indexOf("is:starred")==-1)inhibit=true;if(!inhibit){thread=evt.threadObject;if(thread){thread.updateFromEvent(evt);this._threadChanged_NewThread(thread,evt,addedThreads,updatedThreads,removedThreads)}else{giLogger.logConcern("#PERFWATCH - Downloading from server: "+evt.thread,"glThreadContainer._threadChanged",this._main?this._main.pageId:
giLogger.UNKNOWN_PAGE_ID);var thread=glThread.createCompleteFromId(evt.thread,this._main.gmail);var me=this;thread.addEventListener(glThread.THREAD_LOADED,function(tEvt){me._threadChanged_NewThread(tEvt.target,evt,addedThreads,updatedThreads,removedThreads)},this)}}}}catch(e){giLogger.warn(e,"glThreadContainer._threadChanged",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}},_threadChanged_NewThread:function(thread,evt,addedThreads,updatedThreads,removedThreads){try{if(this._search.matchThread(thread)){this.threads.push(thread);
updatedThreads.push(thread);addedThreads.push(thread)}}catch(e){this.update()}if(updatedThreads.length>0)this.dispatchEvent({name:glThreadContainer.CHANGED,addedThreads:addedThreads,updatedThreads:updatedThreads,removedThreads:removedThreads,actionEvent:evt})},_environmentLabelChanged:function(evt){try{if(this._search.getQuery().indexOf(glSearch.l(evt.label))>-1){this.update();return}else if(evt.name==glEnvironment.RENAME_LABEL)if(this._search.getQuery().indexOf(glSearch.l(evt.newLabel))>-1){this.update();
return}var updatedThreads=[];var idx=-1;for(var i=0;i<this.threads.length;i++)if((idx=this.threads[i].labels.indexOf(evt.label))>-1){if(evt.name==glEnvironment.RENAME_LABEL)this.threads[i].labels[idx]=evt.newLabel;else this.threads[i].labels.splice(idx,1);updatedThreads.push(this.threads[i])}if(updatedThreads.length>0)this.dispatchEvent({name:glThreadContainer.CHANGED,addedThreads:[],updatedThreads:updatedThreads,removedThreads:[],actionEvent:evt})}catch(e){giLogger.warn(e,"glThreadContainer._envLabelChanged",
null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}},getThreadById:function(id,full){if(full)for(var i=0;i<this.threads.length;i++){if(this.threads[i].hasId(id))return this.threads[i]}else for(var i=0;i<this.threads.length;i++)if(this.threads[i].threadId==id)return this.threads[i]},_messageChanged:function(evt){for(var i=0;i<this.threads.length;i++)this.threads[i].updateFromEvent(evt)}},{NEW_SEARCH:"newSearch",LOADING_UPDATE:"loadingUpdate",LOADED:"loaded",CHANGED:"changed",COUNT_TOTAL_DESIRED:"countTotalDesired",
COUNT_TOTAL_CALCULATED:"countTotalCalculated",MAX_THREADS_ALLOWED:1E3,createWithSearch:function(gtd,search){giLogger.log("st","glThreadContainer.createWithSearch",this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID);var container=new glThreadContainer(gtd,search);return container}},{MAX_THREADS_ALLOWED:1E3});glThreadContainer.implement(giEventDispatcher);
