var glTrafficWatcher=giBase.extend({_gmail:null,_trafficWatcherTracer:null,connect:function(gmail){this._gmail=gmail;giLogger.log("st","glTrafficWatcher.connect",this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID);this._trafficWatcherTracer=new glTrafficWatcherTracer;this._trafficWatcherTracer.connect(this._gmail);this._trafficWatcherTracer.addEventListener(glTrafficWatcherTracer.NEW_REQUEST,this._examineRequest,this);this._trafficWatcherTracer.addEventListener(glTrafficWatcherTracer.REQUEST_COMPLETE,
this._receiveXhrResponse,this)},shutdown:function(){this._trafficWatcherTracer.shutdown();this._removeAllListeners();this._trafficWatcherTracer=null;this._gmail=null},_examineRequest:function(evt){try{if(this._urlHasListeners(evt.url))this.dispatchEvent({name:this._urlEventName(evt.url),url:evt.url,postData:evt.postData,responseDataId:evt.responseDataId});if(this._urlHasListeners(evt.url,true))evt.listenForComplete=true}catch(e){giLogger.warn(e,"glTrafficWatcher._examineRequest",null,this._gmail?
this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID)}},_receiveXhrResponse:function(evt){try{var eventName=this._urlEventName(evt.url,true);if(!eventName)return;if(!this.hasEventListener(eventName))return;var data=null;if(evt.responseData){data=this.getResponseData(null,null,evt.responseData);if(!data)giLogger.warn("data was null","glTrafficWatcher._receiveXhrResponse [process evt.responseData]",null,this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID)}else if(evt.responseDataId);else try{var responseType=
/[?&]rt=([^&]+)/.exec(evt.url)[1];switch(responseType){case "j":data=glDataObject.createFromJSResponse(evt.responseText,evt.url,this._gmail);break;case "h":throw new Error("Should not be processing HTML response anymore. Url: "+evt.url);break;default:throw new Error('Invalid response type for url "'+evt.url+'": "'+responseType+'"');}}catch(e){giLogger.warn(e,"glTrafficWatcher._receiveXhrResponse[inner data extraction with evt.responseText]",null,this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID);
return}this.dispatchEvent({name:eventName,url:evt.url,responseData:data,responseDataId:evt.responseDataId})}catch(e){giLogger.warn(e,"glTrafficWatcher._receiveXhrResponse",null,this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID)}},getResponseData:function(responseDataId,previous,responseData){if(!responseData)responseData=this._trafficWatcherTracer.getResponseData(responseDataId,previous);if(!responseData)return null;try{return glDataObject.createFromData(responseData,this._gmail)}catch(e){giLogger.warn(e,
"glTrafficWatcher.getResponseData",null,this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID);return}},_urlHasListeners:function(url,completed){if(typeof completed=="undefined")completed=false;if(!/[?&]view=/.test(url))return false;if(!/[?&]rt=/.test(url))return false;var eventName=this._urlEventName(url,completed);if(!eventName)return false;if(!this.hasEventListener(eventName))return false;return true},_urlEventName:function(url,completed){if(typeof completed=="undefined")completed=false;var eventName=
false;try{var viewType=/[?&]view=([^&]+)/.exec(url)[1];switch(viewType){case "up":var actionType=/[?&]act=([^&]+)/.exec(url)[1];switch(actionType){case "sm":eventName="send_message_request"+(completed?"_completed":"");break;default:eventName="action_request"+(completed?"_completed":"");break}break;case "tl":var m=/[?&]act=([^&]+)/.exec(url);if(m){var actionType=m[1];switch(actionType){case "sm":eventName="send_message_request"+(completed?"_completed":"");break;default:eventName="action_request"+(completed?
"_completed":"");break}}else eventName="thread_list_request"+(completed?"_completed":"");break;case "cv":if(/[?&]t=[^&]/.test(url))eventName="conversation_request"+(completed?"_completed":"");break;case "cd":eventName="conversation_data_request";break}}catch(e){giLogger.warn("Error calculating event name: "+e,"glTrafficWatcher",null,this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID)}return eventName}},{SEND_MESSAGE_REQUEST:"send_message_request",SEND_MESSAGE_REQUEST_COMPLETED:"send_message_request_completed",
ACTION_REQUEST:"action_request",ACTION_REQUEST_COMPLETED:"action_request_completed",THREAD_LIST_REQUEST:"thread_list_request",THREAD_LIST_REQUEST_COMPLETED:"thread_list_request_completed",CONVERSATION_REQUEST:"conversation_request",CONVERSATION_REQUEST_COMPLETED:"conversation_request_completed",CONVERSATION_DATA_REQUEST:"conversation_data_request"});glTrafficWatcher.implement(giEventDispatcher);
