var glTrafficWatcherTracer=giBase.extend({_registered:false,_gmail:null,connect:function(gmail){if(this._registered)return;this._gmail=gmail;giLogger.log("st","glTrafficWatcherTracer.connect",this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID);if(!Components.interfaces.nsITraceableChannel)throw new Error("glTrafficWatcherTracer will not work without nsITraceableChannel (available in Firefox 3.0.4)");glTrafficWatcherTracer.OBSERVER_SERVICE.addObserver(this,"glgmail-http-event",false);this._registered=
true},shutdown:function(){if(!this._registered)return;glTrafficWatcherTracer.OBSERVER_SERVICE.removeObserver(this,"glgmail-http-event");this._registered=false;this._removeAllListeners();this._gmail=false},observe:function(subject,topic,data){try{if(!(subject instanceof Components.interfaces.nsIHttpChannel))return;var win=glTrafficWatcherTracer._getWindowForRequest(subject);if(!win)return;var rootWin=win;while(rootWin!=this._gmail.window&&rootWin.parent&&rootWin!=rootWin.parent)rootWin=rootWin.parent;
if(rootWin!=this._gmail.window)return;if(topic=="http-on-examine-response")this.onExamineResponse(subject)}catch(e){giLogger.warn(e,"glTrafficWatcherTracer.observe",null,this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID)}},onExamineResponse:function(request){try{var url=request.URI.asciiSpec;var postData=glTrafficWatcherTracer._getRequestPostData(request);var evt={name:glTrafficWatcherTracer.NEW_REQUEST,url:url,postData:postData};this.dispatchEvent(evt);if(evt.listenForComplete)try{request.QueryInterface(Components.interfaces.nsITraceableChannel);
var newListener=new glTrafficWatcherTracer.TracingListener(this);newListener.originalListener=request.setNewListener(newListener)}catch(e){}}catch(e){giLogger.warn(e,"glTrafficWatcherTracer.onExamineResponse",null,this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID)}},stopRequest:function(request,responseData){try{if(!this._registered)return;var url=null;try{url=request.name}catch(e){return}var evt={name:glTrafficWatcherTracer.REQUEST_COMPLETE,url:url,responseText:responseData};this.dispatchEvent(evt)}catch(e){giLogger.warn(e,
"glTrafficWatcherTracer.stopRequest",null,this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID)}},QueryInterface:function(iid){if(iid.equals(Components.interfaces.nsISupports)||iid.equals(Components.interfaces.nsIObserver))return this;throw Components.results.NS_ERROR_NO_INTERFACE;}},{NEW_REQUEST:"new_request",REQUEST_COMPLETE:"request_complete",OBSERVER_SERVICE:Components.classes["@gtdinbox.com/glgmail-http-observer;1"].getService(Components.interfaces["nsIObserverService"]),_getRequestPostData:function(request){var postData=
"";try{var is=request.QueryInterface(Components.interfaces.nsIUploadChannel).uploadStream;if(is){var ss=is.QueryInterface(Components.interfaces.nsISeekableStream);if(ss)ss.seek(Components.interfaces.nsISeekableStream.NS_SEEK_SET,0);var binaryInputStream=Components.classes["@mozilla.org/binaryinputstream;1"].createInstance(Components.interfaces.nsIBinaryInputStream);binaryInputStream.setInputStream(is);var segments=[];for(var count=is.available();count;count=is.available())segments.push(binaryInputStream.readBytes(count));
postData=segments.join("");if(postData){var conv=Components.classes["@mozilla.org/intl/scriptableunicodeconverter"].getService(Components.interfaces.nsIScriptableUnicodeConverter);conv.charset="UTF-8";postData=conv.ConvertToUnicode(postData)}if(ss)ss.seek(Components.interfaces.nsISeekableStream.NS_SEEK_SET,0)}}catch(e){}return postData},_getWindowForRequest:function(request){var webProgress=glTrafficWatcherTracer._getRequestWebProgress(request);try{if(webProgress)return webProgress.DOMWindow}catch(e){}return null},
_getRequestWebProgress:function(request){try{if(request.notificationCallbacks)return request.notificationCallbacks.getInterface(Components.interfaces.nsIWebProgress)}catch(e){}try{if(request.loadGroup&&request.loadGroup.groupObserver)return request.loadGroup.groupObserver.QueryInterface(Components.interfaces.nsIWebProgress)}catch(e){}return null}});glTrafficWatcherTracer.implement(giEventDispatcher);
glTrafficWatcherTracer.TracingListener=giBase.extend({originalListener:null,_trafficWatcher:null,_receivedData:null,constructor:function(trafficWatcher){this._trafficWatcher=trafficWatcher;this._receivedData=[]},onCollectData:function(request,inputStream,offset,count){try{var binaryInputStream=Components.classes["@mozilla.org/binaryinputstream;1"].createInstance(Components.interfaces.nsIBinaryInputStream);var storageStream=Components.classes["@mozilla.org/storagestream;1"].createInstance(Components.interfaces.nsIStorageStream);
var binaryOutputStream=Components.classes["@mozilla.org/binaryoutputstream;1"].createInstance(Components.interfaces.nsIBinaryOutputStream);binaryInputStream.setInputStream(inputStream);storageStream.init(8192,count,null);binaryOutputStream.setOutputStream(storageStream.getOutputStream(0));var data=binaryInputStream.readBytes(count);this._receivedData.push(data);binaryOutputStream.writeBytes(data,count);return storageStream.newInputStream(0)}catch(e){giLogger.log("Exception caught in onCollectData: "+
e,"glTrafficWatcherTracer.TracingListener",this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID)}return null},onDataAvailable:function(request,requestContext,inputStream,offset,count){try{var newStream=this.onCollectData(request,inputStream,offset,count);if(newStream)inputStream=newStream;if(this.originalListener)this.originalListener.onDataAvailable(request,requestContext,inputStream,offset,count)}catch(e){giLogger.log("Exception caught in onDataAvailable: "+e,"glTrafficWatcherTracer.TracingListener",
this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID)}},onStartRequest:function(request,requestContext){try{if(this.originalListener)this.originalListener.onStartRequest(request,requestContext)}catch(e){giLogger.log("Exception caught in onStartRequest: "+e,"glTrafficWatcherTracer.TracingListener",this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID)}},onStopRequest:function(request,requestContext,statusCode){if(this.originalListener)this.originalListener.onStopRequest(request,requestContext,
statusCode);return;try{this._trafficWatcher.stopRequest(request,this._receivedData.join());if(this.originalListener)this.originalListener.onStopRequest(request,requestContext,statusCode)}catch(e){giLogger.log("Exception caught in onStopRequest: "+e,"glTrafficWatcherTracer.TracingListener",this._gmail?this._gmail.pageId:giLogger.UNKNOWN_PAGE_ID)}},QueryInterface:function(iid){if(iid.equals(Components.interfaces.nsIStreamListener)||iid.equals(Components.interfaces.nsISupportsWeakReference)||iid.equals(Components.interfaces.nsISupports))return this;
throw Components.results.NS_NOINTERFACE;}});
