(function(){var pageWrapper={_ik:null,_noGmonkey:false,_noGmonkeyActiveViewType:null,_noGmonkeyActiveLastViewType:null,_viewChanged_broadcast_timer:null,_viewChanged_broadcast_timerCount:null,_noGmonkeyDocUrl:null,_uiReadyFired:false,_gmonkeyLoaded:false,_gmonkey:null,init:function(){try{var elem=pageWrapper._getElem();elem.addEventListener("glGmailRunFunction",pageWrapper._runFunctionListener,false)}catch(e){var elemErr=document.createElement();elemErr.setAttribute("id","_gmailInjectedInitError");
elemErr.firebugIgnore=true;elemErr.setAttribute("style","display:none");elemErr.setAttribute("initError",e.toString());if(document&&document.body)document.body.appendChild(elemErr);else document.documentElement.appendChild(elemErr)}},start:function(){pageWrapper._startNoGmonkey()},_loadGreasemonkey:function(count){if(!count)count=0;try{if(pageWrapper._gmonkey)return;if(!top.gmonkey){if(count>50)pageWrapper._warn("Could not find top.gmonkey.","_loadGreasemonkey");else setTimeout(function(){pageWrapper._loadGreasemonkey(count++)},
200);return}if(!pageWrapper._calledGmonkeyLoad){pageWrapper._calledGmonkeyLoad=true;top.gmonkey.load("1.0",function(gm){})}else if(top.gmonkey.isLoaded("1.0")){pageWrapper._greasemonkeyLoaded(top.gmonkey.get("1.0"));return}}catch(e){pageWrapper._warn(e,"_loadGreasemonkey")}if(count>50)pageWrapper._warn("Could not load greasemonkey. Gmonkey exists, never loaded.","_loadGreasemonkey");else setTimeout(function(){pageWrapper._loadGreasemonkey(count++)},200)},_greasemonkeyLoaded:function(gmonkey){pageWrapper._gmonkey=
gmonkey;pageWrapper._tryNotifyGreasemonkeyLoaded()},_tryNotifyGreasemonkeyLoaded:function(){try{pageWrapper._gmonkey.getActiveViewElement()}catch(e){if(e.toString().toLowerCase().indexOf("not registered")>-1){pageWrapper._log("Gmonkey failing.","_tryNotifyGreasemonkeyLoaded");pageWrapper._startNoGmonkey()}else setTimeout(function(){pageWrapper._tryNotifyGreasemonkeyLoaded()},100);return}pageWrapper._gmonkeyLoaded=true;pageWrapper._testUiReady(pageWrapper._tryNotifyGreasemonkeyLoadedAddViewChange)},
_startNoGmonkey:function(){pageWrapper._log("st","_startNoGmonkey");pageWrapper._noGmonkey=true;if(pageWrapper._uiReadyFired){pageWrapper._log("uiReady already fired","_startNoGmonkey");pageWrapper._noGmonkeyCreateViewChange()}else{pageWrapper._log("uiReady not fired","_startNoGmonkey");pageWrapper._testUiReady()}},_noGmonkeyCreateViewChange:function(){try{var useOnHashChange="onhashchange"in window;if(useOnHashChange){pageWrapper._log("Adding view change handler using hashchange","_noGmonkeyCreateViewChange_Finish");
top.addEventListener("hashchange",pageWrapper._noGmonkeyCreateViewChange_fire,false)}else{pageWrapper._log("Adding view change handler using document.title","_noGmonkeyCreateViewChange_Finish");top.document.addEventListener("DOMTitleChanged",function(evt){try{var title=evt.target.title;title=title.replace(/ \(\d+\)/,"");if(!/\s\.\.\.$/.test(title))setTimeout(pageWrapper._noGmonkeyCreateViewChange_fire,50)}catch(e){pageWrapper._warn(e,"_noGmonkeyCreateViewChange -> viewchange function")}return newVal},
true)}}catch(e){pageWrapper._warn(e,"_noGmonkeyCreateViewChange")}},_noGmonkeyCreateViewChange_fire:function(){pageWrapper._log("view changing, previous url: "+pageWrapper._noGmonkeyDocUrl+"\nnew url: "+top.location.href,"_noGmonkeyCreateViewChange_fire");if(top.location.href!=pageWrapper._noGmonkeyDocUrl){pageWrapper._noGmonkeyDocUrl=top.location.href;pageWrapper._noGmonkeyActiveViewType=null;pageWrapper._viewChanged(pageWrapper.getActiveViewType())}},_viewChanged:function(view){try{if(pageWrapper._viewChanged_broadcast_timer){clearInterval(pageWrapper._viewChanged_broadcast_timer);
pageWrapper._viewChanged_broadcast_timer=null}var doc=top.document.getElementById("canvas_frame").contentDocument;var elems=doc.getElementsByClassName("glViewRoot");for(var i=0;i<elems.length;i++)elems[i].className=elems[i].className.replace(/\s*glViewRoot\s*/,"");try{var elRoot=null;if(pageWrapper._noGmonkey){var elRoot=doc.evaluate(".//div[@class='nH mq']",doc.body,null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue;if(elRoot){elRoot=elRoot.parentNode.nextSibling;elRoot=elRoot.firstChild;
for(var i=0;i<elRoot.childNodes.length;i++)if(elRoot.childNodes[i].nodeType==1&&elRoot.childNodes[i].style.display!="none"){elRoot=elRoot.childNodes[i];break}}else pageWrapper._warn("Could not establish glViewRoot - nH mq gone.","_viewChanged")}else elRoot=pageWrapper._gmonkey.getActiveViewElement();if(!elRoot)pageWrapper._warn("Could not find elRoot (for view root). noGmonkey: "+pageWrapper._noGmonkey,"_viewChanged");if(elRoot.className=="")elRoot.className="glViewRoot";else elRoot.className+=" glViewRoot"}catch(e){pageWrapper._warn("Error while looking for glViewRoot: "+
e,"_viewChanged")}if(!(view=="co"&&pageWrapper._noGmonkeyActiveLastViewType==view))pageWrapper._viewChanged_broadcast(view,elRoot);pageWrapper._noGmonkeyActiveLastViewType=view}catch(e){pageWrapper._warn(e,"_viewChanged")}},_viewChanged_broadcast:function(view,elRoot){try{if(elRoot){var result=null;if(view=="tl")result=elRoot.ownerDocument.evaluate('.//div[contains(@class,"A1 D")]/div[@class="nH"][1]',elRoot,null,XPathResult.FIRST_ORDERED_NODE_TYPE,null);else if(view=="cv")result=elRoot.ownerDocument.evaluate('.//div[@class="nH"]/div[contains(@class, "iI D")]',
elRoot,null,XPathResult.FIRST_ORDERED_NODE_TYPE,null);if(!result||result.singleNodeValue){if(pageWrapper._viewChanged_broadcast_timer){pageWrapper._log("Found the actionsHeader after delay (clearing interval). Now broadcast.","_viewChanged_broadcast");clearInterval(pageWrapper._viewChanged_broadcast_timer);pageWrapper._viewChanged_broadcast_timer=null}pageWrapper._dispatchEvent("view_changed")}else if(pageWrapper._viewChanged_broadcast_timer){if(pageWrapper._viewChanged_broadcast_timerCount++>5){pageWrapper._logConcern("Gave up trying to wait for the actionsHeader. Will proceed to fire viewChange event anyway.",
"_viewChanged_broadcast");clearInterval(pageWrapper._viewChanged_broadcast_timer);pageWrapper._viewChanged_broadcast_timer=null;pageWrapper._dispatchEvent("view_changed")}}else{pageWrapper._logConcern("Could not find the actionsHeader to complete view change. Set up interval to try again.","_viewChanged_broadcast");pageWrapper._viewChanged_broadcast_timerCount=0;pageWrapper._viewChanged_broadcast_timer=setInterval(function(){pageWrapper._viewChanged_broadcast(view,elRoot)},200)}}else pageWrapper._dispatchEvent("view_changed")}catch(e){pageWrapper._warn("Error: "+
e.toString(),"_viewChanged_broadcast")}},_testUiReady:function(){try{var doc=top.document.getElementById("canvas_frame").contentDocument;var isReady=/cf zt|cf zq|cf HmCP1d/.test(doc.body.innerHTML);if(!isReady)if(doc.evaluate(".//DIV[@class='nH pp ps']/DIV/DIV[@class='nH s']",doc.body,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength==1)isReady=true;if(isReady)pageWrapper._log("HTML/CSS found","_testUiReady");pageWrapper._log("isReady: "+isReady+", noGmonkey: "+pageWrapper._noGmonkey,
"_testUiReady");if(isReady){pageWrapper._noGmonkeyDocUrl=top.location.href;pageWrapper._dispatchEvent("ui_ready");pageWrapper._uiReadyFired=true;if(pageWrapper._noGmonkey)pageWrapper._noGmonkeyCreateViewChange();else pageWrapper._gmonkey.registerViewChangeCallback(function(view){pageWrapper._viewChanged(view)});pageWrapper._viewChanged(pageWrapper.getActiveViewType())}else{if(!pageWrapper._testUiReadyCount)pageWrapper._testUiReadyCount=0;if(pageWrapper._testUiReadyCount++<40)setTimeout(pageWrapper._testUiReady,
500);else{var len=-1;var html=null;if(doc&&doc.body&&doc.body.innerHTML){html=doc.body.innerHTML;len=doc.body.innerHTML.length}pageWrapper._logHTML(html,"injected-code._testUiReady - could not find HTML/CSS required to load.",false);pageWrapper._warn("Could not find HTML/CSS needed to confidently fire ui_ready. Length of canvas_frame doc.body: "+len,"_testUiReady")}}}catch(e){pageWrapper._warn("Critical error trying to test Gmail load:\n"+e,"_testUiReady")}},reloadGmail:function(){top.location.reload(true)},
getGlobal:function(offset){return top.GLOBALS[parseInt(offset)]},getCookie:function(){return document.cookie},getViewData:function(){return top.VIEW_DATA},getActiveViewType:function(href){if(pageWrapper._noGmonkey){if(!pageWrapper._noGmonkeyActiveViewType){if(!href)href=top.location.href;var viewType="";var inhibitViewChangeFire=false;if(/#contacts/.test(href))viewType="ct";else if(/#settings/.test(href))viewType="s";else if(/#compose/.test(href))viewType="co";else if(/#buzz/.test(href))viewType=
"buzz";if(!viewType){var splitter=href.split("#");var h=splitter[1];var splitter=h.split("/");if(h.indexOf("create-filter")==0);else if(h.indexOf("search")==0){if(splitter.length==3&&splitter[2][0]!="p")viewType="cv"}else if(h.indexOf("advanced-search")==0){if(splitter.length==3&&splitter[2][0]!="p")viewType="cv"}else if(h.indexOf("label")==0){if(splitter.length==3&&splitter[2][0]!="p")viewType="cv"}else if(splitter.length==2&&splitter[1]&&splitter[1][0]!="p")viewType="cv";if(splitter.length==2&&
splitter[0]=="drafts"&&splitter[1][0]!="p")if(pageWrapper._noGmonkeyActiveLastViewType=="co")viewType="co";if(splitter.length==1&&(splitter[0]=="sent"||splitter[0]=="drafts")){var doc=top.document.getElementById("canvas_frame").contentDocument;var result=doc.evaluate(".//DIV[starts-with(@class, 'gA')]/DIV[@class='gB']",doc.body,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null);if(result.snapshotLength>0)for(var i=0;i<result.snapshotLength;i++){var elTo=result.snapshotItem(i);while(elTo.parentNode&&
elTo.style.display!="none")elTo=elTo.parentNode;if(!elTo.parentNode){viewType="cv";break}}}}if(!viewType)viewType="tl";pageWrapper._noGmonkeyActiveViewType=viewType}return pageWrapper._noGmonkeyActiveViewType}else if(!pageWrapper._gmonkeyLoaded)return null;else return pageWrapper._gmonkey.getActiveViewType()},_dispatchEvent:function(eventName,data){var elem=pageWrapper._getElem();elem.setAttribute("event",eventName);if(data)elem.setAttribute("eventData",data);var evt=document.createEvent("Event");
evt.initEvent("glGmailEventDispatched",true,false);elem.dispatchEvent(evt);elem.removeAttribute("event");if(data)elem.removeAttribute("eventData")},_runFunctionListener:function(evt){var elem=pageWrapper._getElem();var func=elem.getAttribute("func");var numParams=parseInt(elem.getAttribute("params"));var params=[];for(var i=0;i<numParams;i++)params.push(elem.getAttribute("param"+(i+1)));try{var returnValue=pageWrapper[func].apply(null,params)}catch(e){pageWrapper._warn("Error in runFunctionListener call ("+
func+"):\n"+e,"_runFunctionListener")}if(func=="getViewData"&&returnValue!==undefined)pageWrapper._log("Return length of "+func+": "+returnValue.length,"_runFunctionListener");else pageWrapper._log("Return value of "+func+": "+returnValue,"_runFunctionListener");if(returnValue!==undefined)try{elem.setAttribute("return",pageWrapper.JSON.stringify({data:returnValue}))}catch(e){pageWrapper._warn("Error in JSON encoding:"+"\n"+e,"_runFunctionListener")}},_getElem:function(){if(!pageWrapper._elem){var elem=
document.createElement("DIV");elem.id="_gmailInjected";elem.setAttribute("id","_gmailInjected");elem.firebugIgnore=true;elem.setAttribute("style","display:none");document.documentElement.appendChild(elem);pageWrapper._elem=elem}return pageWrapper._elem},_log:function(msg,context){pageWrapper._dispatchEvent("log",msg+(context?" ["+context+"]":""))},_logConcern:function(msg,context){pageWrapper._dispatchEvent("logConcern",msg+(context?" ["+context+"]":""))},_warn:function(msg,context){pageWrapper._dispatchEvent("warn",
msg+(context?" ["+context+"]":""))},_logHTML:function(html,systemLevelInfo,approved){var dataObj={html:html,systemLevelInfo:systemLevelInfo,approved:approved};var data=pageWrapper.JSON.stringify(dataObj);pageWrapper._dispatchEvent("logHTML",data)}};if(window.JSON&&window.JSON.stringify)pageWrapper.JSON=window.JSON;else{pageWrapper.JSON={};var cx=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,escapable=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
gap,indent,meta={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},rep;function quote(string){escapable.lastIndex=0;return escapable.test(string)?'"'+string.replace(escapable,function(a){var c=meta[a];return typeof c==="string"?c:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+string+'"'}function str(key,holder){var i,k,v,length,mind=gap,partial,value=holder[key];if(typeof rep==="function")value=rep.call(holder,key,value);switch(typeof value){case "string":return quote(value);
case "number":return isFinite(value)?String(value):"null";case "boolean":case "null":return String(value);case "object":if(!value)return"null";gap+=indent;partial=[];if(typeof value.length=="number"&&typeof value.splice!="undefined"){length=value.length;for(i=0;i<length;i+=1)partial[i]=str(i,value)||"null";v=partial.length===0?"[]":gap?"[\n"+gap+partial.join(",\n"+gap)+"\n"+mind+"]":"["+partial.join(",")+"]";gap=mind;return v}if(rep&&typeof rep==="object"){length=rep.length;for(i=0;i<length;i+=1){k=
rep[i];if(typeof k==="string"){v=str(k,value);if(v)partial.push(quote(k)+(gap?": ":":")+v)}}}else for(k in value)if(Object.hasOwnProperty.call(value,k)){v=str(k,value);if(v)partial.push(quote(k)+(gap?": ":":")+v)}v=partial.length===0?"{}":gap?"{\n"+gap+partial.join(",\n"+gap)+"\n"+mind+"}":"{"+partial.join(",")+"}";gap=mind;return v}}if(typeof pageWrapper.JSON.stringify!=="function")pageWrapper.JSON.stringify=function(value,replacer,space){var i;gap="";indent="";if(typeof space==="number")for(i=0;i<
space;i+=1)indent+=" ";else if(typeof space==="string")indent=space;rep=replacer;if(replacer&&typeof replacer!=="function"&&(typeof replacer!=="object"||typeof replacer.length!=="number"))throw new Error("JSON.stringify");return str("",{"":value})};if(typeof pageWrapper.JSON.parse!=="function")pageWrapper.JSON.parse=function(text,reviver){var j;function walk(holder,key){var k,v,value=holder[key];if(value&&typeof value==="object")for(k in value)if(Object.hasOwnProperty.call(value,k)){v=walk(value,
k);if(v!==undefined)value[k]=v;else delete value[k]}return reviver.call(holder,key,value)}cx.lastIndex=0;if(cx.test(text))text=text.replace(cx,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)});if(/^[\],:{}\s]*$/.test(text.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){j=eval("("+text+")");return typeof reviver==="function"?walk({"":j},""):j}throw new SyntaxError("JSON.parse");
}}pageWrapper.init()})();
