var gtdBoxTypes=boxSection.extend({_gtd:null,_searchBuilders:null,connect:function(gtd){giLogger.log("st","gtdBoxTypes.connect",gtd?gtd.pageId:giLogger.UNKNOWN_PAGE_ID);this._gtd=gtd;var box=giPluginManager.getPluginInstance(boxMain,this._gtd.gmail);this._searchBuilders={};this.id="gtdtypes";this.base(box);this._refresh();this.addEventListener(boxSection.POPOUT,this._popout,this);this._gtd.gmail.environment.addEventListener(glEnvironment.CREATE_LABEL,this._createLabelEvent,this);this._gtd.statusThreadsContainer.addEventListener(glThreadContainer.LOADED,
this._refreshTypeCounts,this);this._gtd.statusThreadsContainer.addEventListener(glThreadContainer.CHANGED,this._refreshTypeCounts,this);this._gtd.labelsData.addEventListener(gtdLabelsData.LABEL_CHANGED,this._labelChanged,this);this._isExpandable(true)},disconnect:function(){this._gtd.statusThreadsContainer.removeEventListener(glThreadContainer.LOADED,this._refreshTypeCounts,this);this._gtd.statusThreadsContainer.removeEventListener(glThreadContainer.CHANGED,this._refreshTypeCounts,this);this._gtd.gmail.environment.removeEventListener(glEnvironment.CREATE_LABEL,
this._createLabelEvent,this);this._gtd.labelsData.removeEventListener(gtdLabelsData.LABEL_CHANGED,this._labelChanged,this);for(t in this._searchBuilders){this._searchBuilders[t].disconnect();delete this._searchBuilders[t]}this.base()},_refresh:function(){for(var i=this.el.childNodes.length-1;i>=0;i--)if(!this._elExpand||this.el.childNodes[i]!=this._elExpand)this.el.removeChild(this.el.childNodes[i]);var elRow=this._main.gmail.canvasDocument.createElement("DIV");elRow.setAttribute("gtdi-box-row-type",
"statuses");elRow.innerHTML="<span>"+giI18N.getString("Box.gtdtypes.statuses")+"</span>";elRow.title=giI18N.getString("Box.gtdtypes.statuses.tooltip");giUIObject.addClassName(elRow,"gtdi-box-row-gtdtypes-statuses");var elDash=this._main.gmail.canvasDocument.createElement("IMG");elDash.id="gtdi-box-row-type-statuses-popout";elDash.src=giUrl.getURL("skin/gtd/popout.PNG");elDash.title=giI18N.getString("Box.DashboardShortcut.title");elRow.appendChild(elDash);var elPopup=this._main.gmail.doc.createElement("DIV");
this._addRow("statuses",elRow,elPopup,true);var typeSettings=this._gtd.prefs.getPref("labels.types");var statusData=this._gtd.labelsData.getStatusData();var foundOne=false;for(t in typeSettings)if(t!="statuses"){var elRow=this._main.gmail.doc.createElement("DIV");elRow.setAttribute("gtdi-box-row-type",t);elRow.title=giI18N.getString("Box.gtdtypes.row.tooltip").replace("%1",giI18N.getString("Labels.Types."+t,t));elRow.innerHTML=giI18N.getString("Labels.Types."+t,t);giUIObject.addClassName(elRow,"gtdi-box-row-gtdtypes");
var elPopup=this._main.gmail.doc.createElement("DIV");this._addRow(t,elRow,elPopup,true);foundOne=true}this.el.style.display=foundOne?"":"none";this._refreshTypeCounts();this._refreshExpanded()},_refreshTypeCounts:function(evt){for(var i=0;i<this._rows.length;i++){var el=this._rows[i].elContent;if(this._rows[i].id=="statuses"){var count=this._gtd.statusThreadsContainer.getTotalCount();if(count>0){el.getElementsByTagName("SPAN")[0].innerHTML=giI18N.getString("Box.gtdtypes.statuses")+" ("+count+")";
el.style.fontWeight="bold"}else{el.getElementsByTagName("SPAN")[0].innerHTML=giI18N.getString("Box.gtdtypes.statuses");el.style.fontWeight=""}}else if(el.getAttribute("gtdi-box-row-label")){var count=this._gtd.statusThreadsContainer.getLabelCount(el.getAttribute("gtdi-box-row-label"));var elSpan=el.getElementsByTagName("SPAN")[0];if(count>0){elSpan.innerHTML=elSpan.innerHTML.replace(/\s\(\d+\)$/,"")+" ("+count+")";el.style.fontWeight="bold"}else{elSpan.innerHTML=elSpan.innerHTML.replace(/\s\(\d+\)$/,
"");el.style.fontWeight=""}}else if(this._gtd.statusThreadsContainer.isTypeActive(this._rows[i].id))giUIObject.addClassName(el,"gtdi-box-row-gtdtypes-hasitems");else giUIObject.removeClassName(el,"gtdi-box-row-gtdtypes-hasitems")}},_labelChanged:function(evt){this._refreshTypeCounts();for(r in this._rows)if(this._rows[r].elPopout)this._rows[r].elPopout.innerHTML=""},_popout:function(evt){try{var el=evt.elPopout;var doc=this._main.gmail.canvasDocument;var type=evt.elRow.getAttribute("gtdi-box-row-id");
if(el.innerHTML==""){this._searchBuilders[type]=this._gtd.getUIObject("searchBuilderSidebarLabelsTree");this._searchBuilders[type].load(null,type);el.appendChild(this._searchBuilders[type].el);this._searchBuilders[type].addEventListener(gtdSearchBuilder.OPEN_CHILD,this._sbOpenChild,this);this._searchBuilders[type].addEventListener(gtdSearchBuilder.CLOSE,this._sbClose,this);if(this._gtd.labelsData.getLabelsArray(type).length==0)if(type=="statuses")this._searchBuilders[type].el.innerHTML="<button id='gtdi-box-popout-nolabels-setupgtd'>"+
giI18N.getString("Box.setup.install")+"</button>";else{var info=giI18N.getString("LabelsInfo.desc."+type);if(info){var elInfo=doc.createElement("DIV");elInfo.className="gtdi-box-popout-nolabels-info";elInfo.innerHTML=info;this._searchBuilders[type].el.appendChild(elInfo)}var typeSettings=this._gtd.prefs.getPref("labels.types");var elNotice=doc.createElement("DIV");elNotice.className="gtdi-box-popout-nolabels-createinfo";elNotice.innerHTML=giI18N.getString("NoLabels").replace("%1",typeSettings[type].prefix);
this._searchBuilders[type].el.appendChild(elNotice);if(type!="old"){var navBar=this._gtd.gmail.getUIObject("navBar");if(navBar.createLabelLink){var elButton=doc.createElement("BUTTON");elButton.innerHTML=giI18N.getString("NoLabels.Create");elButton.className="gtdi-box-popup-nolabels-create";elButton.setAttribute("gtdi-newlabel-typeName",giI18N.getString("Labels.Types."+type,type));elButton.setAttribute("gtdi-newlabel-prefix",typeSettings[type].prefix);this._searchBuilders[type].el.appendChild(elButton);
this._eventsContainer.observe(elButton,"click",this._clickCreateLabel,false)}var elManageLabels=doc.createElement("DIV");elManageLabels.innerHTML="<a href='#' class='gtdi-manage-labels'>"+giI18N.getString("NoLabels.Manage")+"</a>";this._searchBuilders[type].el.appendChild(elManageLabels)}}if(type=="statuses"){var elOverview=doc.createElement("DIV");elOverview.innerHTML=giI18N.getString("Box.gtdtypes.statuses.overview");elOverview.title=giI18N.getString("Box.gtdtypes.statuses.overview.tooltip");elOverview.id=
"gtdi-box-popup-types-statuses-overview";this._searchBuilders[type].el.appendChild(elOverview)}this._eventsContainer.stopObserving(this._searchBuilders[type].el,"click",this._clickPopout,false);this._eventsContainer.observe(this._searchBuilders[type].el,"click",this._clickPopout,false)}else this._searchBuilders[type].load()}catch(e){giLogger.warn("types error: "+e,"gtdBox.popout",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}},_sbOpenChild:function(evt){evt.child.addEventListener(gtdSearchBuilder.OPEN_CHILD,
this._sbOpenChild,this);evt.child.addEventListener(gtdSearchBuilder.HIDE,this._sbClose,this);this._main.gmail.canvasDocument.body.appendChild(evt.child.el);var borderWidth=giUIObject.getBorderWidth(evt.elSpawn);var offset=giUIObject.cumulativeOffset(evt.elSpawn);offset[1]=offset[1]+parseInt(borderWidth[3])+parseInt(borderWidth[1]);var dims=giUIObject.getDimensions(evt.elSpawn);var xy=[offset[0]+dims.width+20,offset[1]];evt.child.el.style.left=xy[0]+"px";evt.child.el.style.top=xy[1]+"px";xy=giUIObject.boundsCheckXY(evt.child.el,
xy[0],xy[1]);evt.child.el.style.left=xy[0]+"px";evt.child.el.style.top=xy[1]+"px";evt.child.el.style.maxHeight=xy[3]+"px"},_sbClose:function(evt){if(evt.target.parent){evt.target.el.parentNode.removeChild(evt.target.el);evt.target.disconnect()}else this._hidePopout(true)},_hidePopout:function(inhibitHide){if(!inhibitHide&&this._currentPopoutRow){var type=this._currentPopoutRow.getAttribute("gtdi-box-row-id");if(type&&this._searchBuilders[type])this._searchBuilders[type].hide()}this.base()},_click:function(evt){if(evt.target.id==
"gtdi-box-row-type-statuses-popout"){var popup=this._gtd.getUIObject("browserPopup");popup.load(gtdBrowser.createBrowser(this._gtd));return}this.base(evt)},_clickPopout:function(evt){try{var el=evt.target;if(el.id=="gtdi-box-popup-types-statuses-overview"){var popup=this._gtd.getUIObject("browserPopup");popup.load(gtdBrowser.createBrowser(this._gtd));this._hidePopout()}else if(el.id=="gtdi-box-popout-nolabels-setupgtd"){try{this._gtd.getUIObject("setup")}catch(e){giLogger.warn(e,"gtdBoxSetup._click",
null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID);gBrowser.selectedTab=gBrowser.addTab("http://www.gtdinbox.com/faq.htm#gtdsetup")}this._hidePopout()}else if(el.className=="gtdi-manage-labels"){this._main.gmail.page.location("hash","#settings/labels");this._hidePopout()}else if(el.className.indexOf("gtdi-box-popup-nolabels-create")>-1){var typeName=el.getAttribute("gtdi-newlabel-typeName");var prefix=el.getAttribute("gtdi-newlabel-prefix");var navBar=this._gtd.gmail.getUIObject("navBar");
giUIObject.simulateMouseEvent(navBar.moreLabelsLink,"mousedown");giUIObject.simulateMouseEvent(navBar.moreLabelsLink,"mouseup");giUIObject.simulateMouseEvent(navBar.createLabelLink,"mousedown");giUIObject.simulateMouseEvent(navBar.createLabelLink,"mouseup");giUIObject.simulateMouseEvent(navBar.createLabelLink,"click");var actionsHeader=this._gtd.gmail.getCurrentViewObject().getActionsHeader();setTimeout(function(){actionsHeader.getCreateLabelInput().value=prefix},750)}}catch(e){giLogger.warn(e,"gtdBoxTypes._clickPopup",
null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}},_createLabelEvent:function(evt){this._hidePopout()},expanded:function(v){if(v)for(var i=0;i<this._rows.length;i++)this._rows[i].el.style.display="";else if(typeof v!="undefined")for(var i=0;i<this._rows.length;i++)this._rows[i].el.style.display="none";return this.base(v)}});
var gtdBoxSetup=boxSection.extend({_gtd:null,connect:function(gtd){giLogger.log("st","gtdBoxSetup.connect",gtd?gtd.pageId:giLogger.UNKNOWN_PAGE_ID);this._gtd=gtd;var box=giPluginManager.getPluginInstance(boxMain,this._gtd.gmail);this.id="gtdsetup";this.base(box);var doc=this._main.gmail.canvasDocument;var elMsg=doc.createElement("DIV");elMsg.id="gtdi-gtd-setup-msg";elMsg.innerHTML=giI18N.getString("Box.setup.msg");this.el.appendChild(elMsg);var elInstall=doc.createElement("BUTTON");elInstall.id="gtdi-gtd-setup-install";
elInstall.innerHTML=giI18N.getString("Box.setup.install");this.el.appendChild(elInstall);this._eventsContainer.observe(this.el,"click",this._click,false);this._gtd.labelsData.addEventListener(gtdLabelsData.LABEL_CHANGED,this._labelsChanged,this)},disconnect:function(){this._gtd.labelsData.removeEventListener(gtdLabelsData.LABEL_CHANGED,this._labelsChanged,this);this.base()},_labelsChanged:function(evt){var sd=this._gtd.labelsData.getStatusData();var statuses=this._gtd.labelsData.getLabelsHash("statuses");
if(statuses[sd["next_action"]]&&statuses[sd["waiting_on"]]&&statuses[sd["some_day"]])this.disconnect()},_click:function(evt){try{var el=evt.target;if(el.id=="gtdi-gtd-setup-install")try{this._gtd.getUIObject("setup")}catch(e){giLogger.warn(e,"gtdBoxSetup._click",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID);gBrowser.selectedTab=gBrowser.addTab("http://www.gtdinbox.com/faq.htm#gtdsetup")}}catch(e){giLogger.warn(e,"gtdBoxSetup._click",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}}});
var gtdBoxPrefsWarning=boxSection.extend({_gtd:null,connect:function(gtd){giLogger.log("st","gtdBoxCvWarning.connect",gtd?gtd.pageId:giLogger.UNKNOWN_PAGE_ID);this._gtd=gtd;var box=giPluginManager.getPluginInstance(boxMain,this._gtd.gmail);this.id="gtdcvwarning";this.base(box);var doc=this._main.gmail.canvasDocument;var elMsg=doc.createElement("DIV");elMsg.id="gtdi-gtd-prefs-warning";elMsg.innerHTML=giI18N.getString("Box.prefswarning.msg");this.el.appendChild(elMsg);var elFAQ=doc.createElement("A");
elFAQ.id="gtdi-gtd-prefs-warning-faq";elFAQ.href="http://www.gtdinbox.com/faq.htm#prefswarning";elFAQ.innerHTML=giI18N.getString("Box.prefswarning.faq");this.el.appendChild(elFAQ)},disconnect:function(){this.base()},_click:function(evt){try{this.disconnect()}catch(e){giLogger.warn(e,"gtdBoxCvWarning._click",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}}});
