var gtdConversationSendButton=giUIObject.extend({_replyHandler:null,_eventsContainer:null,_sendButtons:null,_elPopup:null,_currentReplyId:null,_requestMoveAfterReply:null,_dropdown:null,_actionAndMove:null,connect:function(main){giLogger.log("st","gtdConversationSendButton.connect",main?main.pageId:giLogger.UNKNOWN_PAGE_ID);this.base(main);try{this._sendButtons={};this._eventsContainer=new giEventsContainer(this);this._replyHandler=this._main.gmail.getCurrentViewObject().getReplyHandler();var doc=
this._main.gmail.canvasDocument;this._elPopup=doc.createElement("DIV");this._elPopup.className="gtdi-send-popup";this._elPopupModifiers=doc.createElement("DIV");this._elPopupModifiers.className="gtdi-send-popup-modifiers";this._elPopup.appendChild(this._elPopupModifiers);this._elPopupModifiersArchive=doc.createElement("DIV");this._elPopupModifiers.appendChild(this._elPopupModifiersArchive);var elArchiveCheck=doc.createElement("INPUT");elArchiveCheck.id="gtdi-send-popup-modifiers-archive";elArchiveCheck.setAttribute("type",
"checkbox");elArchiveCheck.checked=this._main.prefs.getPref("components.conversation.sendbutton.archive");this._elPopupModifiersArchive.innerHTML="<label for='gtdi-send-popup-modifiers-archive'>"+giI18N.getString("ConversationSendButton.Archive")+"</label>";this._elPopupModifiersArchive.insertBefore(elArchiveCheck,this._elPopupModifiersArchive.firstChild);var elPopupStatus=doc.createElement("DIV");elPopupStatus.className="gtdi-send-popup-status";this._elPopup.appendChild(elPopupStatus);this._dropdown=
this._main.gmail.getUIObject("dropdown");this._dropdown.addEventListener(glDropdown.HIDE_DROPDOWN,this._hideStatusSelectDropdown,this);elPopupStatus.appendChild(this._dropdown.elButton);this._dropdown.elButton.title=giI18N.getString("ConversationSendButton.Statuses.tooltip");this._eventsContainer.observe(this._dropdown.elList,"click",this._clickStatusSelectList,false);this._actionAndMove=this._main.getUIObject("conversationActionAndMove");this._actionAndMove.load([{name:gtdConversationActionAndMove.BUTTONS.SEND,
visible:true},{name:gtdConversationActionAndMove.BUTTONS.SEND_EOM,visible:true}]);this._actionAndMove.addEventListener(gtdConversationActionAndMove.CLICK_ACTION,this._clickActionAndMove,this);this._elPopup.appendChild(this._actionAndMove.el);this._loadStatusSelect(true);this._replyHandler.addEventListener(glConversationReplyHandler.SHOW_REPLY_FULL,this._showReply,this);this._replyHandler.addEventListener(glConversationReplyHandler.HIDE_REPLY_FULL,this._hideReply,this);this._replyHandler.addEventListener(glConversationReplyHandler.ADD_ROW,
this._addRow,this);this._main.gmail.environment.addEventListener(glEnvironment.CREATE_LABEL,this._envLabelChange,this);this._main.gmail.environment.addEventListener(glEnvironment.RENAME_LABEL,this._envLabelChange,this);this._main.gmail.environment.addEventListener(glEnvironment.DELETE_LABEL,this._envLabelChange,this);this._integrateSend()}catch(e){giLogger.warn(e,"gtdConversationSendButton.connect",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}},disconnect:function(){this._hidePopup();
this._main.gmail.environment.removeEventListener(glEnvironment.CREATE_LABEL,this._envLabelChange,this);this._main.gmail.environment.removeEventListener(glEnvironment.RENAME_LABEL,this._envLabelChange,this);this._main.gmail.environment.removeEventListener(glEnvironment.DELETE_LABEL,this._envLabelChange,this);this._sendButtons=null;this._thread=null;this._replyHandler.removeEventListener(glConversationReplyHandler.SHOW_REPLY_FULL,this._showReply,this);this._replyHandler.removeEventListener(glConversationReplyHandler.HIDE_REPLY_FULL,
this._hideReply,this);this._replyHandler.removeEventListener(glConversationReplyHandler.ADD_ROW,this._addRow,this);if(this._actionAndMove)this._actionAndMove.disconnect();this._actionAndMove=null;this._replyHandler=null;this._eventsContainer.reset();this._eventsContainer=null;this._dropdown.disconnect();this._dropdown=null;for(p in this)if(this.hasOwnProperty(p)&&this[p]&&this[p].nodeName&&this[p].nodeType)this[p]=null;this.base()},load:function(thread){this._thread=thread;this._loadStatusSelect()},
_loadStatusSelect:function(complete){var doc=this._main.gmail.canvasDocument;var statusData=this._main.labelsData.getStatusData();if(complete){this._dropdown.elList.innerHTML="";var statuses=this._main.labelsData.getLabelsArray("statuses",true);statuses.splice(0,0,giI18N.getString("ConversationSendButton.Statuses.None"));for(var i=0;i<statuses.length;i++){var elLi=doc.createElement("DIV");elLi.className="gtdi-send-popup-status-item";var name=Math.round((new Date).valueOf()*Math.random());elLi.innerHTML=
"<input type='checkbox' id='"+name+"'/>"+gtdLabelsData.removePrefix(statuses[i],statusData.prefix);if(i>0){elLi.setAttribute("isStatus","1");elLi.setAttribute("label",statuses[i])}this._dropdown.elList.appendChild(elLi)}}var options=this._dropdown.elList.getElementsByTagName("DIV");for(var i=0;i<options.length;i++){giUIObject.removeClassName(options[i],"gtdi-active");options[i].getElementsByTagName("INPUT")[0].checked=false}var currentSelected=[];if(this._thread)for(var i=0;i<this._thread.labels.length;i++)if(gtdLabelsData.testPrefix(this._thread.labels[i],
statusData.prefix)){var label=this._thread.labels[i];currentSelected.push(label);var options=this._dropdown.elList.getElementsByTagName("DIV");for(var j=1;j<options.length;j++)if(options[j].getAttribute("label")==label){giUIObject.addClassName(options[j],"gtdi-active");options[j].getElementsByTagName("INPUT")[0].checked=true}}if(currentSelected.length==0){var elOption=this._dropdown.elList.getElementsByTagName("DIV")[0];giUIObject.addClassName(elOption,"gtdi-active");elOption.getElementsByTagName("INPUT")[0].checked=
true}this._updateStatusSelectTitle(currentSelected)},_updateStatusSelectTitle:function(currentSelected){if(!currentSelected)currentSelected=this._getStatusSelectActive();if(currentSelected.length>1)this._dropdown.elButtonTitle.innerHTML=currentSelected.length+" "+giI18N.getString("ConversationSendButton.Statuses.selected");else if(currentSelected.length==1){var statusData=this._main.labelsData.getStatusData();this._dropdown.elButtonTitle.innerHTML=gtdLabelsData.removePrefix(currentSelected[0],statusData.prefix)}else this._dropdown.elButtonTitle.innerHTML=
giI18N.getString("ConversationSendButton.Statuses.None")},_getStatusSelectActive:function(){var currentSelected=[];var options=this._dropdown.elList.getElementsByTagName("DIV");for(var i=0;i<options.length;i++)if(giUIObject.hasClassName(options[i],"gtdi-active"))if(options[i].getAttribute("label"))currentSelected.push(options[i].getAttribute("label"));return currentSelected},_clickStatusSelectList:function(evt){try{var elOption=evt.target;while(!giUIObject.hasClassName(elOption,"gtdi-send-popup-status-item"))elOption=
elOption.parentNode;var clickOff=false;var label=elOption.getAttribute("label");if(giUIObject.hasClassName(elOption,"gtdi-active")){elOption.getElementsByTagName("INPUT")[0].checked=false;giUIObject.removeClassName(elOption,"gtdi-active")}else{giLogger("add status","gtdConversationSendButton._clickStatusSelectList");var unselectActive=false;if(label){if(!this._main.labelsData.allowMultipleStatuses(label)){unselectActive=true;clickOff=true}}else{unselectActive=true;clickOff=true}if(unselectActive){var options=
this._dropdown.elList.getElementsByTagName("DIV");for(var i=0;i<options.length;i++)if(giUIObject.hasClassName(options[i],"gtdi-active")){options[i].getElementsByTagName("INPUT")[0].checked=false;giUIObject.removeClassName(options[i],"gtdi-active")}}elOption.getElementsByTagName("INPUT")[0].checked=true;giUIObject.addClassName(elOption,"gtdi-active")}if(clickOff)this._dropdown.hideDropdown();this._updateStatusSelectTitle()}catch(e){giLogger.warn(e,"gtdConversationSendButton._clickStatusSelectList",
null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}},_hideStatusSelectDropdown:function(evt){var currentSelected=this._getStatusSelectActive();if(currentSelected.length==0){var elOption=this._dropdown.elList.getElementsByTagName("DIV")[0];giUIObject.addClassName(elOption,"gtdi-active");elOption.getElementsByTagName("INPUT")[0].checked=true;this._updateStatusSelectTitle(currentSelected)}},_envLabelChange:function(evt){this._loadStatusSelect(true)},_integrateSend:function(){try{var doc=this._main.gmail.canvasDocument;
for(var i=0;i<this._replyHandler.replies.length;i++){var reply=this._replyHandler.replies[i];if(!this._sendButtons[reply.id]&&this._replyHandler.isFullShowing(reply.elRoot))if(doc.getElementById("sendAnd"+reply.id+"1"))giLogger.warn("Trying to add SendAnd button second time.","gtdConversationSendButton._integrateSend",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID);else{var elSend1=this._replyHandler.getSendButton(reply.elRoot);var elSend2=this._replyHandler.getSendButton2(reply.elRoot);
var sendButtons=[elSend1,elSend2];var elSendNew1=null;var elSendNew2=null;for(var i=0;i<sendButtons.length;i++){var elSend=sendButtons[i];var elSendNew=giUIObject.createGmailButton("gmail-send-button",giI18N.getString("ConversationSendButton.SendNew"),null,this._main.gmail);elSendNew.id="sendAnd"+reply.id+i;elSend.parentNode.insertBefore(elSendNew,elSend);this._eventsContainer.observe(elSendNew,"click",this._clickSend,false);if(i==0)elSendNew1=elSend;else elSendNew2=elSend}this._sendButtons[reply.id]=
{elSend1:elSendNew1,elSend2:elSendNew2}}}}catch(e){giLogger.warn(e,"gtdConversationSendButton._integrateSend",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}},_clickSend:function(evt){try{var elButton=evt.target;while(elButton.parentNode&&(!elButton.getAttribute||elButton.getAttribute("role")!="button"))elButton=elButton.parentNode;if(elButton.getAttribute("role")=="button"){var reply=this._replyHandler.getReplyByEl(elButton);this._currentReplyId=reply.id;this._main.gmail.canvasDocument.body.appendChild(this._elPopup);
var borderWidth=giUIObject.getBorderWidth(elButton);var offset=giUIObject.cumulativeOffset(elButton);offset[1]=offset[1]+parseInt(borderWidth[3])+parseInt(borderWidth[1]);var dims=giUIObject.getDimensions(elButton);var xy=[offset[0]+dims.width,offset[1]];this._elPopup.style.position="absolute";this._elPopup.style.left=xy[0]+"px";this._elPopup.style.top=xy[1]+"px";this._eventsContainer.observe(this._main.gmail.canvasDocument.body,"click",this._clickWindow,true);this._loadStatusSelect();this._elPopupModifiersArchive.style.display=
this._thread.hasLabel("^i")?"":"none"}else giLogger.error("Could not find Send button on clickSend","gtdConversationSendButton._clickSend",this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}catch(e){giLogger.warn(e,"gtdConversationSendButton._clickSend",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}},_hidePopup:function(){this._eventsContainer.stopObserving(this._main.gmail.canvasDocument.body,"click",this._clickWindow,true);if(this._elPopup.parentNode)this._elPopup.parentNode.removeChild(this._elPopup)},
_clickWindow:function(evt){try{var buttons=this._sendButtons[this._currentReplyId];if(buttons){var found=false;var el=evt.target;var i=8;while(el.parentNode&&--i>=0){if(el==buttons.elSend1||el==buttons.elSend2||el==this._elPopup){found=true;break}el=el.parentNode}if(!found)this._hidePopup()}else this._hidePopup()}catch(e){giLogger.warn(e,"gtdConversationSendButton._mousemoveWindow",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}},_showReply:function(evt){this._integrateSend()},_hideReply:function(evt){if(this._sendButtons[evt.id])this._sendButtons[evt.id]=
null},_clickActionAndMove:function(evt){try{var reply=this._replyHandler.getReplyById(this._currentReplyId);var statusData=this._main.labelsData.getStatusData();var conversationView=this._main.getCurrentViewObject();var statuses=this._main.labelsData.getLabelsArray("statuses");var currentSelected=this._getStatusSelectActive();for(var i=0;i<currentSelected.length;i++){var idx=statuses.indexOf(currentSelected[i]);if(idx>-1)statuses.splice(idx,1)}conversationView.stripLabels(statuses);for(var i=0;i<
currentSelected.length;i++){var label=currentSelected[i];if(!this._thread.hasLabel(label))this._main.gmail.actions.performAction(glActionManager.ADD_LABEL,this._thread,glActionManager.USE_DOM,label)}if(this._elPopupModifiersArchive.style.display!="none")if(this._elPopupModifiersArchive.getElementsByTagName("INPUT")[0].checked){conversationView.stripLabels(["^i"]);this._main.prefs.setPref("components.conversation.sendbutton.archive",true)}else this._main.prefs.setPref("components.conversation.sendbutton.archive",
false);if(evt.button==gtdConversationActionAndMove.BUTTONS.SEND_EOM){var composeBox=this._main.gmail.getUIObject("composeBox");composeBox.setScope(reply.elRoot);var text=composeBox.getText();var lines=[];if(composeBox.getType()=="rich")lines=text.split(/\<br\/?\>/i);else lines=text.split("\n");var found=false;for(var i=0;i<lines.length;i++)if(giUtil.testEmailAddress(lines[i],false,true))if(/\s(\d+)\:(\d+)\s/.test(lines[i])){found=true;i-=1;while(i>0&&lines[i].length<3)i-=1;lines.splice(i+1,0,"");
lines.splice(i+1,0,giI18N.getString("ConversationSendButton.EOM"));lines.splice(i+1,0,"");break}if(!found){lines.push("");lines.push(giI18N.getString("ConversationSendButton.EOM"))}if(composeBox.getType()=="rich")composeBox.setText(lines.join("<br>"));else composeBox.setText(lines.join("\n"))}giUIObject.simulateMouseEvent(this._replyHandler.getSendButton(reply.elRoot),"mousedown");giUIObject.simulateMouseEvent(this._replyHandler.getSendButton(reply.elRoot),"mouseup");this._requestMoveAfterReply=evt.move}catch(e){giLogger.warn(e,
"gtdConversationSendButton._clickActionAndMove",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}},_addRow:function(evt){if(this._requestMoveAfterReply){var conversationViewGl=this._main.gmail.getCurrentViewObject();if(this._requestMoveAfterReply=="up"){var elUp=conversationViewGl.actionsHeader.getButton(glActionsHeader.BACK_TO_TL);giUIObject.simulateMouseEvent(elUp,"mousedown");giUIObject.simulateMouseEvent(elUp,"mouseup")}else if(this._requestMoveAfterReply=="prev"){var elPrev=conversationViewGl.getMovePreviousElement();
giUIObject.simulateMouseEvent(elPrev,"click")}else if(this._requestMoveAfterReply=="next"){var elNext=conversationViewGl.getMoveNextElement();giUIObject.simulateMouseEvent(elNext,"click")}this._requestMoveAfterReply=null}}});
