var gtdConversationAlerts=giUIObject.extend({_conversationLabels:null,_interval:null,_lastIntervalStart:null,_eventsContainer:null,connect:function(main){giLogger.log("st","gtdConversationAlert.connect",main?main.pageId:giLogger.UNKNOWN_PAGE_ID);this.base(main);this._eventsContainer=new giEventsContainer(this);this._main.gmail.trafficWatcher.addEventListener(glTrafficWatcher.SEND_MESSAGE_REQUEST_COMPLETED,this._sendMessage,this)},disconnect:function(){if(this._conversationLabels){this._conversationLabels.disconnect();
this._conversationLabels=null}this._eventsContainer.reset();if(this._interval){clearInterval(this._interval);this._interval=null}this.base()},_sendMessage:function(evt){if(!this._interval){var me=this;this._interval=setInterval(function(){me._intervalEvent()},500)}this._lastIntervalStart=(new Date).valueOf()},_removeNode:function(event){try{var elRemoved=event.target;var i=3;var el=this._elAlert;while(--i>=0&&el!=elRemoved)el=el.parentNode;if(el==elRemoved){if(this._conversationLabels)this._conversationLabels.el.style.display=
"none";var elContainer=this._elAlert.ownerDocument.evaluate(".//*[@class='gtdi-labelreminder-container']",this._elAlert,null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue;if(elContainer)elContainer.parentNode.removeChild(elContainer);this._eventsContainer.stopObserving(this._main.gmail.page.getViewRoot(),"DOMNodeRemoved",this._removeNode,false)}}catch(e){giLogger.warn(e,"gtdConversationAlerts._removeNode",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}},_intervalEvent:function(){try{var doc=
this._main.gmail.canvasDocument;this._elAlert=doc.evaluate(".//table[@role='alert']",this._main.gmail.page.getViewRoot(),null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue;if(this._elAlert){var elContainer=doc.evaluate(".//*[@class='gtdi-labelreminder-container']",this._elAlert,null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue;if(elContainer)elContainer.parentNode.removeChild(elContainer);var statusData=this._main.labelsData.getStatusData(true);var thread=this._main.gmail.getCurrentViewObject().getThread();
var hasStatus=null;for(var i=0;i<thread.labels.length;i++)if(statusData.reverseLookup[thread.labels[i]]){hasStatus=thread.labels[i];break}var elText=doc.evaluate(".//td[@class='vh']",this._elAlert,null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue;if(hasStatus)elText.innerHTML+="<div class='gtdi-labelreminder-container'>"+giI18N.getString("Conversation.alerts.labelreminder.hasStatus.prefix")+": "+hasStatus+" (<a href='#' class='gtdi-labelreminder'>"+giI18N.getString("Conversation.alerts.labelreminder.hasStatus.link")+
"</a>)</div>";else elText.innerHTML+="<div class='gtdi-labelreminder-container'>"+giI18N.getString("Conversation.alerts.labelreminder.noStatus.prefix")+" (<a href='#' class='gtdi-labelreminder'>"+giI18N.getString("Conversation.alerts.labelreminder.noStatus.link")+"</a>)</div>";this._eventsContainer.stopObserving(this._elAlert,"click",this._click,false);this._eventsContainer.observe(this._elAlert,"click",this._click,false);this._eventsContainer.stopObserving(this._main.gmail.page.getViewRoot(),"DOMNodeRemoved",
this._removeNode,false);this._eventsContainer.observe(this._main.gmail.page.getViewRoot(),"DOMNodeRemoved",this._removeNode,false);clearInterval(this._interval);this._interval=null}else if((new Date).valueOf()-this._lastIntervalStart>3E4){clearInterval(this._interval);this._interval=null}}catch(e){clearInterval(this._interval);this._interval=null;giLogger.warn(e,"gtdConversationAlerts._intervalEvent",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}},_click:function(event){try{var el=event.target;
if(el.className=="gtdi-labelreminder"){giUtil.stopEvent(event);if(!this._conversationLabels){this._conversationLabels=this._main.getUIObject("labellingBox");this._conversationLabels.setServerActionType(glActionManager.USE_DOM);this._conversationLabels.load(this._main.gmail.getCurrentViewObject().getThread(),true);var elCmdButtons=this._conversationLabels.getCmdButtons();var elHide=elCmdButtons.ownerDocument.createElement("DIV");elHide.className="gtdi-btn";elHide.innerHTML="<b class='gtdi-btn-t'></b><b class='gtdi-btn-t2'></b><b class='gtdi-btn-m'></b><b class='gtdi-btn-b2'></b><b class='gtdi-btn-b'></b><span class='gtdi-btn-label'><span class='gtdi-hide'>"+
giI18N.getString("Labelling.buttons.hide")+"</span></span>";elCmdButtons.appendChild(elHide);this._eventsContainer.observe(elHide,"click",this._click,false)}var elSpace=this._main.gmail.canvasDocument.createElement("BR");elSpace.setAttribute("clear","both");this._conversationLabels.el.appendChild(elSpace);var elRow=el;while(elRow.parentNode&&elRow.className!="nH")if(elRow.className=="gtdi-labelreminder-container"){var elC=elRow;elRow=elRow.parentNode;elRow.removeChild(elC)}else elRow=elRow.parentNode;
if(elRow.className=="nH")if(elRow.nextSibling)elRow.parentNode.insertBefore(this._conversationLabels.el,elRow.nextSibling);else elRow.parentNode.appendChild(this._conversationLabels.el);this._conversationLabels.el.style.display=""}if(el.className=="gtdi-hide")this._conversationLabels.el.style.display="none"}catch(e){giLogger.warn(e,"gtdConversationAlerts._click",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}}});
