var gtdConversationView=giUIObject.extend({_conversationLabels:null,_requestFinish:null,_replyToSelf:null,_sendButton:null,connect:function(main){giLogger.log("st","gtdConversationView.connect",main?main.pageId:giLogger.UNKNOWN_PAGE_ID);this.base(main);try{var conversationView=this._main.gmail.getCurrentViewObject();if(this._main.prefs.getPref("components.conversation.reply_to_self.enabled"))if(this._main.serverAccount.getAccountType()==giServerAccount.TYPES.PLUS)this._replyToSelf=main.getUIObject("conversationReplyToSelf");
if(this._main.prefs.getPref("components.conversation.send_and.enabled"))if(this._main.serverAccount.getAccountType()==giServerAccount.TYPES.PLUS)this._sendButton=main.getUIObject("conversationSendButton");if(this._main.prefs.getPref("components.conversation.labelling_box.enabled")){this._conversationLabels=this._main.getUIObject("labellingBox");this._conversationLabels.setServerActionType(glActionManager.USE_DOM);giUIObject.addClassName(this._conversationLabels.el,"conversation-labels");this._conversationLabels.addEventListener(gtdConversationActionAndMove.CLICK_ACTION,
this._actionAndMove,this);conversationView.getTitle().parentNode.appendChild(this._conversationLabels.el)}conversationView.getThread();if(conversationView.isThreadCreated())this._threadCreated();else conversationView.addEventListener(glConversationView.THREAD_CREATED,this._threadCreated,this);this._main.gmail.actions.addEventListener(glActionManager.THREAD_CHANGED,this._threadChanged,this)}catch(e){giLogger.warn(e,"gtdConversationView.connect",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}},
disconnect:function(){this._main.gmail.actions.removeEventListener(glActionManager.THREAD_CHANGED,this._threadChanged,this);this._requestFinish=null;if(this._conversationLabels){this._conversationLabels.removeEventListener(gtdConversationActionAndMove.CLICK_ACTION,this._actionAndMove,this);this._conversationLabels.disconnect();this._conversationLabels=null}if(this._replyToSelf){this._replyToSelf.disconnect();this._replyToSelf=null}if(this._sendButton){this._sendButton.disconnect();this._sendButton=
null}this.base()},_threadCreated:function(evt){if(!this._main)return;var conversationView=this._main.gmail.getCurrentViewObject();var thread=conversationView.getThread();if(this._sendButton)this._sendButton.load(thread);if(this._conversationLabels){this._conversationLabels.load(thread,true,null,"cv1");var actionAndMove=this._conversationLabels.getActionAndMove();if(actionAndMove){var elPrev=conversationView.getMovePreviousElement();var elNext=conversationView.getMoveNextElement();actionAndMove.setMovePrevNextVisibility(!!elPrev,
!!elNext)}}if(gtdConversationView.THREADS_SEEN_CACHE.indexOf(thread.threadId)==-1){giLogger.log("Test bad sync for thread with labels: "+thread.labels,"gtdConversationView._threadCreated",this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID);gtdConversationView.THREADS_SEEN_CACHE.push(thread.threadId);var results=conversationView.getHeaderLabels();var badSync=false;var labelname=null;for(var i=0;i<results.snapshotLength;i++){labelname=results.snapshotItem(i).getAttribute("name");if(thread.labels.indexOf(labelname)==
-1){badSync=true;break}}if(badSync)giLogger.warn("Bad sync on conversation","gtdConversationView._threadCreated","ThreadId: "+thread.threadId+"\nFailed on label: "+labelname,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}else{var removedLabels=[];if(removedLabels.length>0)giLogger.logConcern("Automatically removed labels that are out of sync: \n"+removedLabels.join(", ")+"\nThread labels: "+thread.labels.join(", "),"gtdConversationView._threadCreated",this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}},
stripLabels:function(remove,conversationView,count){if(!count)count=1;if(!conversationView)conversationView=this._main.gmail.getCurrentViewObject();var results=conversationView.getHeaderLabels();for(var i=0;i<results.snapshotLength;i++){var elLabel=results.snapshotItem(i);var name=elLabel.getAttribute("name");if(remove.indexOf(name)>-1){while(elLabel.parentNode&&elLabel.nodeName!="TR")elLabel=elLabel.parentNode;if(elLabel.nodeName=="TR"){var elX=this._main.gmail.canvasDocument.evaluate(".//td/span[@class='hO']",
elLabel,null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue;giUIObject.simulateMouseEvent(elX,"click");if(++count<50)this.stripLabels(remove,conversationView,count);break}}}},_actionAndMove:function(evt){var conversationView=this._main.gmail.getCurrentViewObject();var thread=conversationView.getThread();if(thread.hasId(evt.threadId)){var elUp=conversationView.actionsHeader.getButton(glActionsHeader.BACK_TO_TL);var elPrev=conversationView.getMovePreviousElement();var elNext=conversationView.getMoveNextElement();
switch(evt.button){case gtdConversationActionAndMove.BUTTONS.FINISH:var statusData=this._main.labelsData.getStatusData();if(!thread.hasLabel(statusData.finished)&&this._main.labelsData.hasLabel(statusData.finished)){this._requestFinish={thread:thread,move:evt.move};this._main.gmail.actions.performAction(glActionManager.ADD_LABEL,thread,glActionManager.USE_DOM,statusData.finished);break}case gtdConversationActionAndMove.BUTTONS.ARCHIVE:this.stripLabels(["^i"]);case gtdConversationActionAndMove.BUTTONS.MOVE:if(evt.move==
"up"){giUIObject.simulateMouseEvent(elUp,"mousedown");giUIObject.simulateMouseEvent(elUp,"mouseup")}if(evt.move=="prev")giUIObject.simulateMouseEvent(elPrev,"click");if(evt.move=="next")giUIObject.simulateMouseEvent(elNext,"click");break;case gtdConversationActionAndMove.BUTTONS.REPORT_SPAM:case gtdConversationActionAndMove.BUTTONS.DELETE:var messages=thread.messages;var lastMessageID=messages[messages.length-1].messageId;var serverType=evt.move=="up"?glActionManager.USE_DOM:glActionManager.USE_AJAX;
if(evt.button==gtdConversationActionAndMove.BUTTONS.DELETE)this._main.gmail.actions.performAction(glActionManager.DELETE,lastMessageID,serverType);else if(evt.button==gtdConversationActionAndMove.BUTTONS.REPORT_SPAM)this._main.gmail.actions.performAction(glActionManager.REPORT_SPAM,lastMessageID,serverType);if(evt.move=="prev")giUIObject.simulateMouseEvent(elPrev,"click");if(evt.move=="next")giUIObject.simulateMouseEvent(elNext,"click");break}}},_threadChanged:function(event){try{var thread=this._main.gmail.getCurrentViewObject().getThread();
if(thread&&thread.hasId(event.thread))switch(event.action){case glActionManager.ADD_LABEL:var typeSettings=this._main.prefs.getPref("labels.types");if(gtdLabelsData.testPrefix(event.label,typeSettings.statuses.prefix)){var statusData=this._main.labelsData.getStatusData(true);var labels=[];if(!this._main.labelsData.allowMultipleStatuses(event.label,statusData,typeSettings)){var labels=this._main.labelsData.getLabelsArray("statuses");for(var i=labels.length-1;i>=0;i--){var key=statusData.reverseLookup[labels[i]];
if(event.label==labels[i]||key&&typeSettings.statuses.core[key].notExclusive)labels.splice(i,1)}}var requestFinish=this._requestFinish;if(requestFinish&&event.label==statusData.finished&&requestFinish.thread.hasId(event.thread)){this._requestFinish=null;labels.push("^i");this.stripLabels(labels);var conversationView=this._main.gmail.getCurrentViewObject();if(requestFinish.move=="up"){var elUp=conversationView.actionsHeader.getButton(glActionsHeader.BACK_TO_TL);giUIObject.simulateMouseEvent(elUp,"mousedown");
giUIObject.simulateMouseEvent(elUp,"mouseup")}if(requestFinish.move=="prev")giUIObject.simulateMouseEvent(conversationView.getMovePreviousElement(),"click");if(requestFinish.move=="next")giUIObject.simulateMouseEvent(conversationView.getMoveNextElement(),"click")}else this.stripLabels(labels)}break}}catch(e){giLogger.warn(e,"gtdConversationView._threadChanged",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}}},{THREADS_SEEN_CACHE:[]});
