var gtdConversationActionAndMove=giUIObject.extend({el:null,_elContainer:null,_elPopup:null,_buttons:null,_popupTimeout:null,_incPrev:true,_incNext:true,connect:function(main){giLogger.log("st","gtdConversationActionAndMove.connect",main?main.pageId:giLogger.UNKNOWN_PAGE_ID);this.base(main);this._eventsContainer=new giEventsContainer(this);this._buttons={};var doc=main.gmail.canvasDocument;this.el=doc.createElement("DIV");this.el.className="gtdi-actionandmove";this._elContainer=doc.createElement("DIV");
this._elContainer.className="gtdi-actionandmove-container";this.el.appendChild(this._elContainer);this._elPopup=doc.createElement("DIV");this._elPopup.className="gtdi-actionandmove-popup";this._elPopup.style.display="none";this.el.appendChild(this._elPopup);this._eventsContainer.observe(this.el,"click",this._click,false)},disconnect:function(){if(this._popupTimeout){clearTimeout(this._popupTimeout);this._popupTimeout=null}this._main=null;this.thread=null;if(this.el&&this.el.parentNode)this.el.parentNode.removeChild(this.el);
if(this._elPopup&&this._elPopup.parentNode)this._elPopup.parentNode.removeChild(this._elPopup);this._buttons=null;this.el=null;this._elContainer=null;this._elPopup=null;this._eventsContainer.reset();this._eventsContainer=null;this.base()},load:function(buttons){this._buttons={};this._elContainer.innerHTML="";this._elPopup.innerHTML="";var doc=this._main.gmail.canvasDocument;for(var i=0;i<buttons.length;i++){var elButton=this._createCmdButton(doc,buttons[i].name,giI18N.getString("ActionAndMove.button."+
buttons[i].name),giI18N.getString("ActionAndMove.button.tooltip."+buttons[i].name),true,true,giI18N.getString("ActionAndMove.button.tooltip.prev."+buttons[i].name),giI18N.getString("ActionAndMove.button.tooltip.next."+buttons[i].name)).container;if(buttons[i].visible)this._elContainer.appendChild(elButton);else this._elPopup.appendChild(elButton);this._buttons[buttons[i].name]={el:elButton}}if(this._elPopup.innerHTML=="")this._eventsContainer.stopObserving(this._elContainer,"mouseover",this._mouseover,
false);else if(this._main.serverAccount.getAccountType()==giServerAccount.TYPES.PLUS)this._eventsContainer.observe(this._elContainer,"mouseover",this._mouseover,false);this.setMovePrevNextVisibility()},setMovePrevNextVisibility:function(incPrev,incNext){if(typeof incPrev!="undefined")this._incPrev=incPrev;if(typeof incNext!="undefined")this._incNext=incNext;var doc=this._main.gmail.canvasDocument;var result=doc.evaluate(".//div[contains(@class,'gtdi-prev')]",this.el,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,
null);for(var i=0;i<result.snapshotLength;i++)result.snapshotItem(i).style.display=this._incPrev?"":"none";var result=doc.evaluate(".//div[contains(@class,'gtdi-next')]",this.el,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null);for(var i=0;i<result.snapshotLength;i++)result.snapshotItem(i).style.display=this._incNext?"":"none"},_showPopup:function(){if(this._elPopup.style.display!="none")return;if(this._elPopup.innerHTML=="")return;this._elPopup.style.display="";this._eventsContainer.observe(this.el.ownerDocument.body,
"mousemove",this._mousemoveWindow,true)},_hidePopup:function(){if(this._popupTimeout){clearTimeout(this._popupTimeout);this._popupTimeout=null}this._eventsContainer.stopObserving(this.el.ownerDocument.body,"mousemove",this._mousemoveWindow,true);this._elPopup.style.display="none"},_click:function(event){try{var el=event.target;var i=7;var move="up";while(el.parentNode&&--i>=0){if(giUIObject.hasClassName(el,"gtdi-next"))move="next";if(giUIObject.hasClassName(el,"gtdi-prev"))move="prev";if(el.hasAttribute("gtdi-button-name")){this.dispatchEvent({name:gtdConversationActionAndMove.CLICK_ACTION,
button:el.getAttribute("gtdi-button-name"),move:move});break}el=el.parentNode}}catch(e){giLogger.warn(e,"gtdConversationActionAndMove._click",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}},_mouseover:function(evt){this._showPopup()},_mousemoveWindow:function(event){try{var found=false;var el=event.target;var i=8;while(el.parentNode&&--i>=0){if(el==this.el||el==this._elPopup){found=true;break}el=el.parentNode}if(found){if(this._popupTimeout){clearTimeout(this._popupTimeout);this._popupTimeout=
null}}else if(!this._popupTimeout)this._popupTimeout=setTimeout(giUtil.bind(this,this._hidePopup),750)}catch(e){giLogger.warn(e,"gtdConversationActionAndMove._mousemoveWindow",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}},_createCmdButton:function(doc,id,name,tooltip,incBack,incNext,tooltipBack,tooltipNext){var elContainer=doc.createElement("DIV");elContainer.className="gtdi-btn-grp";elContainer.setAttribute("gtdi-button-name",id);var elMain=doc.createElement("DIV");elMain.className=
"gtdi-btn gtdi-"+id;elMain.innerHTML="<b class='gtdi-btn-t'></b><b class='gtdi-btn-t2'></b><b class='gtdi-btn-m'></b><b class='gtdi-btn-b2'></b><b class='gtdi-btn-b'></b><span class='gtdi-btn-label' title='"+tooltip+"'><span class='' >"+name+"</span></span>";elContainer.appendChild(elMain);var elPrev=null;if(incBack){elPrev=doc.createElement("DIV");elPrev.className="gtdi-btn  gtdi-prev";elPrev.title=tooltipBack;elPrev.innerHTML="<b class='gtdi-btn-t'></b><b class='gtdi-btn-t2'></b><b class='gtdi-btn-m'></b><b class='gtdi-btn-b2'></b><b class='gtdi-btn-b'></b><span class='gtdi-btn-label'><span class='' ><img src='"+
giUrl.getURL("skin/gtd/i/gtdi-prev.png")+"'/></span></span>";elContainer.appendChild(elPrev)}var elNext=null;if(incNext){elNext=doc.createElement("DIV");elNext.className="gtdi-btn  gtdi-next";elNext.title=tooltipNext;elNext.innerHTML="<b class='gtdi-btn-t'></b><b class='gtdi-btn-t2'></b><b class='gtdi-btn-m'></b><b class='gtdi-btn-b2'></b><b class='gtdi-btn-b'></b><span class='gtdi-btn-label'><span class='' ><img src='"+giUrl.getURL("skin/gtd/i/gtdi-next.png")+"'/></span></span>";elContainer.appendChild(elNext)}return{container:elContainer,
main:elMain,prev:elPrev,next:elNext}}},{CLICK_ACTION:"CLICK_ACTION",BUTTONS:{ARCHIVE:"archive",FINISH:"finish",DELETE:"delete",REPORT_SPAM:"report_spam",MOVE:"move",SEND:"send",SEND_EOM:"send_eom"}});gtdConversationActionAndMove.implement(giEventDispatcher);
