var gtdDeadlineButton=giUIObject.extend({el:null,_elMenu:null,_elTextBox:null,_elSave:null,_eventsContainer:null,_dropdown:null,_actionsHeader:null,connect:function(main){giLogger.log("st","gtdDeadlineButton.connect",main?main.pageId:giLogger.UNKNOWN_PAGE_ID);this.base(main);this._eventsContainer=new giEventsContainer(this);var doc=this._main.gmail.canvasDocument;var button=giUIObject.createGmailButton("gmail-header-button",giI18N.getString("Deadline.ActionsHeaderButton"),{collapseLeft:true,dropdown:true},
this._main.gmail);this.el=button.el;this._elMenu=doc.createElement("DIV");this._elMenu.className="gtdi-deadlinebutton-menu";var menuItems=[[giI18N.getString("Deadline.ActionsHeaderButton.menuItems.days.none"),"none"],[giI18N.getString("Deadline.ActionsHeaderButton.menuItems.days.0"),"0"],[giI18N.getString("Deadline.ActionsHeaderButton.menuItems.days.1"),"1"],[giI18N.getString("Deadline.ActionsHeaderButton.menuItems.weeks.1"),"7"]];for(var i=0;i<menuItems.length;i++){var elLi=doc.createElement("DIV");
elLi.className="gtdi-deadlinebutton-menu-item gtdi-deadlinebutton-menu-item-button";elLi.innerHTML=menuItems[i][0];elLi.setAttribute("gtdi-deadlinebutton-menu-days",menuItems[i][1]);this._elMenu.appendChild(elLi)}var elLi=doc.createElement("DIV");elLi.className="gtdi-deadlinebutton-menu-item gtdi-deadlinebutton-menu-item-input";elLi.innerHTML="<input type='text' value='"+giI18N.getString("Deadline.DefaultDate")+"'/><button>"+giI18N.getString("Deadline.ActionsHeaderButton.menuItems.save")+"</button>";
this._elMenu.appendChild(elLi);this._elTextBox=elLi.getElementsByTagName("INPUT")[0];this._elSave=elLi.getElementsByTagName("BUTTON")[0];this._dropdown=this._main.gmail.getUIObject("dropdown");this._dropdown.init(this.el,button.elTitle,this._elMenu);this._eventsContainer.observe(this._elMenu,"click",this._click,false)},disconnect:function(){this._dropdown.disconnect();this._actionsHeader=null;if(this.el&&this.el.parentNode)this.el.parentNode.removeChild(this.el);this.el=null;this._eventsContainer.reset();
this.base()},setActionsHeader:function(actionsHeader){this._actionsHeader=actionsHeader},_setDeadline:function(month,day){try{var prefix=this._main.prefs.getPref("labels.types.deadlines.prefix");var toAdd=[];if(month==0);else toAdd=[this._main.labelsData.getDeadlineLabel(),this._main.labelsData.getDeadlineMonth(month),this._main.labelsData.getDeadlineDay(day)];var me=this;for(var i=toAdd.length-1;i>=0;i--)if(!this._main.labelsData.hasLabel(toAdd[i])){var label=toAdd[i];this._main.gmail.actions.performAction(glActionManager.ADD_LABEL,
null,glActionManager.USE_DOM,label,this._actionsHeader);setTimeout(function(){me._main.gmail.actions.performAction(glActionManager.HIDE_LABEL,null,glActionManager.USE_AJAX,label)},2E3)}var fLabelTest=function(label,state){if((idx=toAdd.indexOf(label))>-1){toAdd.splice(idx,1);return 2}else if(label.indexOf(prefix)==0)return 0;return-1};this._main.gmail.actions.actionDOMBuffer.bulkLabel(this._actionsHeader,fLabelTest);for(var i=0;i<toAdd.length;i++){var label=toAdd[i];this._main.gmail.actions.performAction(glActionManager.ADD_LABEL,
null,glActionManager.USE_DOM,label,this._actionsHeader);setTimeout(function(){me._main.gmail.actions.performAction(glActionManager.HIDE_LABEL,null,glActionManager.USE_AJAX,label)},2E3)}}catch(e){giLogger.warn(e,"gtdDeadlineButton._setDeadline","month: "+month+", "+"day: "+day,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}},_click:function(evt){try{var el=evt.target;while(el.parentNode){if(el.hasAttribute("gtdi-deadlinebutton-menu-days")){var days=el.getAttribute("gtdi-deadlinebutton-menu-days");
if(days=="none")this._setDeadline(0,0);else{var today=new Date;var futureDate=new Date(today.valueOf()+1E3*60*60*24*days);this._setDeadline(futureDate.getMonth()+1,futureDate.getDate())}this._dropdown.hideDropdown();break}else if(el==this._elSave){var date=gtdDeadlineEventSet.getDateFromTextBox(this._elTextBox.value);if(!date.isValid){alert(giI18N.getString("Deadline.invalidInput"));break}this._setDeadline(date.month,date.day);this._dropdown.hideDropdown();break}el=el.parentNode}}catch(e){giLogger.warn(e,
"gtdDeadlineButton._click",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}}});
