var gtdLabellingDropdown=giUIObject.extend({_labellingBox:null,_dropdown:null,el:null,_elRecent:null,_elRecentTitle:null,_elCreate:null,_type:null,_typeLabelDOM:null,_eventsContainer:null,connect:function(main){giLogger.log("st","gtdLabellingDropdown.connect",main?main.pageId:giLogger.UNKNOWN_PAGE_ID);this.base(main);this._eventsContainer=new giEventsContainer(this);this._dropdown=this._main.gmail.getUIObject("dropdown");this._dropdown.addEventListener(glDropdown.SHOW_BUTTON,this._showDropdown,this);
this.el=this._dropdown.elButton},setType:function(type){this._type=type;this.refreshTitle();this._dropdown.elList.innerHTML="";var doc=this._main.gmail.canvasDocument;this._elRecentTitle=doc.createElement("DIV");this._elRecentTitle.className="gtdi-droppeddown-recent-title";this._elRecentTitle.innerHTML=giI18N.getString("Labelling.dropdown.recent");this._dropdown.elList.appendChild(this._elRecentTitle);this._elRecent=doc.createElement("DIV");this._elRecent.className="gtdi-droppeddown-recent";this._dropdown.elList.appendChild(this._elRecent);
this._typeLabelDOM=this._main.labelsData.getLabelsEl(this._type);this._dropdown.elList.appendChild(this._typeLabelDOM.el);if(this._main.labelsData.getLabelsArray(this._type).length==0){var info=giI18N.getString("LabelsInfo.desc."+type);if(info){var elInfo=doc.createElement("DIV");elInfo.className="gtdi-droppeddown-nolabels";elInfo.innerHTML=info;this._dropdown.elList.appendChild(elInfo)}}this._elCreate=doc.createElement("DIV");this._elCreate.className="gtdi-droppeddown-create";this._elCreate.setAttribute("gtdLabelType",
type);this._elCreate.innerHTML="<img src='"+giUrl.getURL("skin/gtd/add.png")+"'/><span>"+giI18N.getString("Labelling.dropdown.create")+"</span>";this._dropdown.elList.appendChild(this._elCreate);this._dropdown.hideDropdown()},_showDropdown:function(evt){this._refreshRecent();this._typeLabelDOM.close();var labels=this._typeLabelDOM.getSelectedLabelNames();for(var i=0;i<labels.length;i++)this._typeLabelDOM.open(labels[i]);if(this._main.gmail.offline.isUnstable())this._elCreate.style.display="none";
else this._elCreate.style.display="";var popup=this._main.getUIObject("browserPopup");if(popup.isActive()){var dimsPopup=giUIObject.getDimensions(popup.el);var offsetInPopup=giUIObject.cumulativeOffset(this._elDropdown,popup.el);var padding=giUIObject.getPadding(this._elDropdown);height=dimsPopup.height-offsetInPopup[1]-parseInt(padding[0])-parseInt(padding[2]);if(height>400)height=400;this._dropdown.elList.style.maxHeight=height+"px"}else this._dropdown.elList.style.maxHeight=""},_refreshRecent:function(activeLabels){if(!activeLabels)activeLabels=
this._typeLabelDOM.getSelectedLabelNames();var doc=this.el.ownerDocument;this._elRecent.innerHTML="";var recent=this._main.recent.getLabels(this._type);if(recent.length>3)recent.length=3;recent.sort();if(recent.length==0)this._elRecentTitle.style.display="none";else{this._elRecentTitle.style.display="";for(var i=0;i<recent.length;i++){var elRecent=doc.createElement("DIV");elRecent.className="gtdi-droppeddown-recent-item";if(activeLabels.indexOf(recent[i][0])>-1)elRecent.className+=" gtdi-active";
elRecent.innerHTML=recent[i][0];elRecent.setAttribute("gtdLabelName",recent[i][0]);this._elRecent.appendChild(elRecent)}}},refreshTitle:function(activeLabels){var activeLabelCount=0;if(this._typeLabelDOM){if(!activeLabels)activeLabels=this._typeLabelDOM.getSelectedLabelNames();activeLabelCount=activeLabels.length}this._dropdown.elButtonTitle.innerHTML=giI18N.getString("Labelling.dropdown."+this._type+".title",giI18N.getString("Labels.Types."+this._type,this._type));if(activeLabelCount>0){this._dropdown.elButtonTitle.innerHTML+=
" ("+activeLabelCount+")";giUIObject.addClassName(this._dropdown.elButton,"gtdi-dropdown-hasSelections")}else giUIObject.removeClassName(this._dropdown.elButton,"gtdi-dropdown-hasSelections")},setLabel:function(labelname,isOn){this._typeLabelDOM.selected(labelname,isOn);var activeLabels=this._typeLabelDOM.getSelectedLabelNames();this.refreshTitle(activeLabels);if(this._elRecent.childNodes.length>0){var elRecent=this._elRecent.ownerDocument.evaluate(".//DIV[@gtdLabelName='"+labelname+"']",this._elRecent,
null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue;if(elRecent)if(isOn)giUIObject.addClassName(elRecent,"gtdi-active");else giUIObject.removeClassName(elRecent,"gtdi-active");else if(isOn)this._refreshRecent(activeLabels)}},disconnect:function(){if(this._typeLabelDOM)this._typeLabelDOM.disconnect();this._main=null;this.thread=null;this._dropdown.disconnect();this._dropdown=null;this.el=null;this._eventsContainer.reset();this._eventsContainer=null;this.base()}},{});gtdLabellingDropdown.implement(giEventDispatcher);
