var gtdLabelingBox=giUIObject.extend({_autoUpdate:null,_hideCmds:null,_labellingDropdowns:null,_eventsContainer:null,_thread:null,_serverActionType:null,_elCmdButtons:null,_elNotify:null,_actionAndMove:null,connect:function(main){giLogger.log("st","gtdLabelingBox.connect",main?main.pageId:giLogger.UNKNOWN_PAGE_ID);this.base(main);this._eventsContainer=new giEventsContainer(this);this._labellingDropdowns={};this._main.labelsData.addEventListener(gtdLabelsData.LABEL_CHANGED,this._initStructure,this);
this._main.gmail.actions.addEventListener(glActionManager.THREAD_CHANGED,this._threadUpdated,this)},disconnect:function(){if(this._thread){this._thread.removeEventListener(glThread.THREAD_LOADED,this._refresh,this);this._thread=null}for(t in this._labellingDropdowns)this._labellingDropdowns[t].disconnect();this._main.labelsData.removeEventListener(gtdLabelsData.LABEL_CHANGED,this._initStructure,this);this._main.gmail.actions.removeEventListener(glActionManager.THREAD_CHANGED,this._threadUpdated,this);
this._elCmdButtons=null;this._elNotify=null;if(this._actionAndMove)this._actionAndMove.disconnect();this._actionAndMove=null;this._eventsContainer.reset();this._eventsContainer=null;this.base()},init:function(actionBox){this._actionBox=actionBox;this.elStatusesRow=this._main.gmail.canvasDocument.createElement("DIV");this._actionBox.addRow("labelingBox_statuses",this.elStatusesRow);this._eventsContainer.observe(this.elStatusesRow,"click",this._click,false);this.elLabelsRow=this._main.gmail.canvasDocument.createElement("DIV");
this.elLabelsRow.className="gtdi-row";this._actionBox.addRow("labelingBox_labels",this.elLabelsRow);this._eventsContainer.observe(this.elLabelsRow,"click",this._click,false);this._initStructure()},_initStructure:function(){try{var currentLabels=this._getCurrentLabels();for(t in this._labellingDropdowns)this._labellingDropdowns[t].disconnect();this._labellingDropdowns={};if(this._actionAndMove){this._actionAndMove.disconnect();this._actionAndMove=null}this.elStatusesRow.innerHTML="";this.elLabelsRow.innerHTML=
"";var doc=this._main.gmail.canvasDocument;var typeSettings=this._main.prefs.getPref("labels.types");labelsData=this._main.labelsData;this.elStatusesRow.className="gtdi-row-actions";var elUL=doc.createElement("UL");this.elStatusesRow.appendChild(elUL);var statuses=labelsData.getLabelsArray("statuses",true,true);var statusData=this._main.labelsData.getStatusData(true);var isPlus=this._main.serverAccount.getAccountType()==giServerAccount.TYPES.PLUS;if(statuses.length>0)for(var i=0;i<statuses.length;i++){var key=
statusData.reverseLookup[statuses[i]];if(key=="today"){var elLi=doc.createElement("LI");elLi.className="gtdi-label-status gtdi-label-"+key;elLi.setAttribute("gtdi-item",statuses[i]);elLi.innerHTML="<a href='#'>"+statuses[i].replace(statusData.prefix,"")+"</a>";elUL.appendChild(elLi)}else if(key!="finished"||!isPlus){var elLi=doc.createElement("LI");elLi.className="gtdi-label-status gtdi-label-"+key;elLi.setAttribute("gtdi-item",statuses[i]);elLi.innerHTML="<a href='#' onclick='return false;'><b><span class='gtdi-labelname'>"+
statuses[i].replace(statusData.prefix,"")+"</span></b></a>";elUL.appendChild(elLi)}}else if(!this._main.prefs.getPref("components.conversation.labelling_box.setupHide")){var elSetup=doc.createElement("LI");elSetup.className="gtdi-labelingbox-setup";elSetup.innerHTML="<span>"+giI18N.getString("Labelling.setup.noStatus")+"</span> <span class='gtdi-labelingbox-setuplink'>"+giI18N.getString("Labelling.setup.setupLink")+"</span> (<span class='gtdi-labelingbox-setuphide'>"+giI18N.getString("Labelling.setup.setupHide")+
"</span>)";elUL.appendChild(elSetup)}this._elCmdButtons=doc.createElement("LI");this._elCmdButtons.id="gtdi-arcfin";this._elCmdButtons.className="gtdi-btn-grp";elUL.appendChild(this._elCmdButtons);this._actionAndMove=this._main.getUIObject("conversationActionAndMove");this._elCmdButtons.appendChild(this._actionAndMove.el);this._actionAndMove.addEventListener(gtdConversationActionAndMove.CLICK_ACTION,this._clickActionAndMove,this);this._elNotify=doc.createElement("DIV");this._elNotify.id="gtdi-notify";
this.elStatusesRow.appendChild(this._elNotify);for(t in typeSettings)if(t!="statuses"&&t!="old"&&!typeSettings[t].isHidden){this._labellingDropdowns[t]=this._main.getUIObject("labellingDropdown");this._labellingDropdowns[t].setType(t);this.elLabelsRow.appendChild(this._labellingDropdowns[t].el)}this._testCmdButtons();if(this._thread)this.uiSelectLabels(this._thread.labels);else if(currentLabels.length>0)this.uiSelectLabels(currentLabels)}catch(e){giLogger.warn(e,"gtdLabelingBox._initStructure",null,
this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}},load:function(thread,autoUpdate,hideCmds){if(this._thread){this._thread.removeEventListener(glThread.THREAD_LOADED,this._refresh,this);this._thread=null}this._thread=thread;this._autoUpdate=autoUpdate;this._hideCmds=hideCmds;if(this._hideCmds)this._elCmdButtons.style.display="none";else this._elCmdButtons.style.display="";this._elNotify.innerHTML="";if(this._thread){this._thread.addEventListener(glThread.THREAD_LOADED,this._refresh,this);if(this._thread.isBasicLoaded())this._refresh()}},
_refresh:function(){if(this._thread){if(this._thread.isBasicLoaded()){this.uiSelectLabels(this._thread.labels);this._testCmdButtons()}if(this._thread.isSimpleLoaded())if(this._thread.isDeleted())this._elNotify.innerHTML=giI18N.getString("Labelling.notify.deleted");else if(this._thread.isSpam())this._elNotify.innerHTML=giI18N.getString("Labelling.notify.spam")}else;},uiSelectLabels:function(labels){var doc=this._main.gmail.canvasDocument;var currentLabels=this._getCurrentLabels();for(var i=currentLabels.length-
1;i>=0;i--)if(labels.indexOf(currentLabels[i])>-1)currentLabels.splice(i,1);for(var i=0;i<currentLabels.length;i++)this._setLabel(currentLabels[i],false);for(var i=0;i<labels.length;i++)if(labels[i]&&labels[i].indexOf("^")==-1)this._setLabel(labels[i],true)},_getCurrentLabels:function(){var currentLabels=[];if(this.elStatusesRow){var result=this._main.gmail.canvasDocument.evaluate(".//*[contains(@class,'gtdi-active')]",this.elStatusesRow,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null);for(var i=
0;i<result.snapshotLength;i++)currentLabels.push(result.snapshotItem(i).getAttribute("gtdi-item"))}if(this.elLabelsRow){var result=this._main.gmail.canvasDocument.evaluate(".//*[contains(@class,'gtdi-active')]",this.elLabelsRow,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null);for(var i=0;i<result.snapshotLength;i++)currentLabels.push(result.snapshotItem(i).getAttribute("gtdi-item"))}return currentLabels},_setLabel:function(labelname,isOn){if(!labelname)return;var foundType=this._main.labelsData.getLabelType(labelname);
if(!foundType||foundType!="statuses"&&!this._labellingDropdowns[foundType])return;var doc=this._main.gmail.canvasDocument;if(foundType=="statuses"){var elLabel=null;if(labelname.indexOf("'")>-1){var result=doc.evaluate("./li[@gtdi-item]",this.elStatusesRow,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null);for(var i=0;i<result.snapshotLength;i++)if(result.snapshotItem(i).getAttribute("gtdi-item")==labelname){elLabel=result.snapshotItem(i);break}}else elLabel=doc.evaluate(".//li[@gtdi-item='"+labelname+
"']",this.elStatusesRow,null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue;if(elLabel)if(isOn)giUIObject.addClassName(elLabel,"gtdi-active");else giUIObject.removeClassName(elLabel,"gtdi-active")}else this._labellingDropdowns[foundType].setLabel(labelname,isOn)},setServerActionType:function(type){this._serverActionType=type},_click:function(event){try{var el=event.target;while(el.parentNode){if(el.className=="gtdi-treelist-expander")break;else if(el.className=="gtdi-labelremove"){var labelname=
el.parentNode.getAttribute("gtdi-item");this._removeLabel(labelname);break}else if(el.className=="gtdi-labelingbox-setuplink"){var setup=this._main.getUIObject("setup");setup.hideHide();break}else if(el.className=="gtdi-labelingbox-setuphide"){this._main.prefs.setPref("components.conversation.labelling_box.setupHide",true);var elTree=el;while(elTree.parentNode&&!giUIObject.hasClassName(elTree,"gtdi-labelingbox-setup"))elTree=elTree.parentNode;if(giUIObject.hasClassName(elTree,"gtdi-labelingbox-setup"))elTree.parentNode.removeChild(elTree);
break}else if(el.getAttribute("gtdi-item")&&!el.hasAttribute("gtdi-placeholder")){if(giUIObject.hasClassName(el,"gtdi-active"))this._removeLabel(el.getAttribute("gtdi-item"));else this._addLabel(el.getAttribute("gtdi-item"));break}else if(giUIObject.hasClassName(el,"gtdi-dropdown-content-create")){var doc=el.ownerDocument;var type=el.getAttribute("gtdLabelType");var prefix=this._main.prefs.getPref("labels.types."+type+".prefix");var typeName=giI18N.getString("Labels.Types."+type,this._type);var label=
prompt(giI18N.getString("Labelling.dropdown.create.prompt").replace("%1",typeName),prefix);if(label&&label!=prefix)if(this._thread)this._main.gmail.actions.performAction(glActionManager.ADD_LABEL,this._thread,this._serverActionType,label);else{this._main.gmail.actions.performAction(glActionManager.CREATE_LABEL,null,glActionManager.USE_AJAX_SYNC,label);this._addLabel(label)}}else if(el.className.indexOf("gtdi-archive")>-1){if(this._thread.hasLabel("^i")){var isNext=el.className.indexOf("gtdi-archive-next")>
-1;this.dispatchEvent({name:gtdLabelingBox.CLICK_ARCHIVE,moveNext:isNext,threadId:this._thread.threadId})}}else if(el.className.indexOf("gtdi-label-status")>-1){giUtil.stopEvent(event);var labelname=el.getAttribute("gtdi-item");if(giUIObject.hasClassName(el,"gtdi-active"))this._removeLabel(labelname);else this._addLabel(labelname);break}el=el.parentNode}return false}catch(e){giLogger.warn(e,"gtdLabelingBox._click",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}},_addLabel:function(event){var labelname=
typeof event=="string"?event:event.label;if(this._thread&&this._autoUpdate)this._main.gmail.actions.performAction(glActionManager.ADD_LABEL,this._thread,this._serverActionType,labelname);this._setLabel(labelname,true);if(this.hasEventListener(gtdLabelingBox.SELECT_LABEL))this.dispatchEvent({name:gtdLabelingBox.SELECT_LABEL,label:labelname})},_removeLabel:function(event){var labelname=typeof event=="string"?event:event.label;if(this._thread&&this._autoUpdate)this._main.gmail.actions.performAction(glActionManager.REMOVE_LABEL,
this._thread,this._serverActionType,labelname);this._setLabel(labelname,false);if(this.hasEventListener(gtdLabelingBox.UNSELECT_LABEL))this.dispatchEvent({name:gtdLabelingBox.UNSELECT_LABEL,label:labelname})},_threadUpdated:function(event){var statusData=this._main.labelsData.getStatusData();if(this._thread&&this._thread.hasId(event.thread)){if(event.label&&event.label==statusData.finished)this._testCmdButtons();if(event.action==glActionManager.ADD_LABEL)this._setLabel(event.label,true);else if(event.action==
glActionManager.REMOVE_LABEL)this._setLabel(event.label,false);else if(event.action==glActionManager.ARCHIVE)this._testCmdButtons()}},_testCmdButtons:function(){if(!this._thread)return;if(!this._actionAndMove)return;var buttons=[];var statusData=this._main.labelsData.getStatusData();var exclude={};exclude[gtdConversationActionAndMove.BUTTONS.SEND]=true;exclude[gtdConversationActionAndMove.BUTTONS.SEND_EOM]=true;var isArchiveable=false;if(this._thread.hasLabel("^i")){buttons.push({name:gtdConversationActionAndMove.BUTTONS.ARCHIVE,
visible:true});exclude[gtdConversationActionAndMove.BUTTONS.ARCHIVE]=true;isArchiveable=true}else if(!this._thread.hasLabel(statusData.finished)){buttons.push({name:gtdConversationActionAndMove.BUTTONS.FINISH,visible:true});exclude[gtdConversationActionAndMove.BUTTONS.ARCHIVE]=true;exclude[gtdConversationActionAndMove.BUTTONS.FINISH]=true}else{buttons.push({name:gtdConversationActionAndMove.BUTTONS.MOVE,visible:true});exclude[gtdConversationActionAndMove.BUTTONS.ARCHIVE]=true;exclude[gtdConversationActionAndMove.BUTTONS.FINISH]=
true;exclude[gtdConversationActionAndMove.BUTTONS.MOVE]=true}if(this._thread.hasLabel(statusData.finished))exclude[gtdConversationActionAndMove.BUTTONS.FINISH]=true;var hash=this._main.gmail.page.location("hash");if(hash.indexOf("#spam")==0){exclude[gtdConversationActionAndMove.BUTTONS.REPORT_SPAM]=true;exclude[gtdConversationActionAndMove.BUTTONS.DELETE]=true}if(hash.indexOf("#trash")==0){exclude[gtdConversationActionAndMove.BUTTONS.REPORT_SPAM]=true;exclude[gtdConversationActionAndMove.BUTTONS.DELETE]=
true}for(b in gtdConversationActionAndMove.BUTTONS)if(!exclude[gtdConversationActionAndMove.BUTTONS[b]])buttons.push({name:gtdConversationActionAndMove.BUTTONS[b],visible:false});if(this._main.serverAccount.getAccountType()==giServerAccount.TYPES.PLUS)this._actionAndMove.load(buttons);else if(isArchiveable){this._actionAndMove.el.style.display="";this._actionAndMove.load(buttons)}else this._actionAndMove.el.style.display="none"},_clickActionAndMove:function(evt){evt.threadId=this._thread.threadId;
this.dispatchEvent(evt)},getActionAndMove:function(){return this._actionAndMove}},{SELECT_LABEL:"select_label",UNSELECT_LABEL:"unselect_label"});gtdLabelingBox.implement(giEventDispatcher);
