var gtdLabelsMenu=giUIObject.extend({_eventsContainer:null,el:null,_elDropdown:null,_elDropdownList:null,_threads:null,_serverActionType:null,connect:function(main){giLogger.log("st","gtdLabelsMenu.connect",main?main.pageId:giLogger.UNKNOWN_PAGE_ID);this.base(main);this._eventsContainer=new giEventsContainer(this);this._threads=[];var doc=main.gmail.canvasDocument;this.el=doc.createElement("DIV");this.el.className="gtdi-btn gtdi-dropdown";this.el.innerHTML="<b class='gtdi-btn-t'></b><b class='gtdi-btn-t2'></b><b class='gtdi-btn-m'></b><b class='gtdi-btn-b2'></b><b class='gtdi-btn-b'></b><span class='gtdi-btn-label'>"+
giI18N.getString("LabelsMenu.Title")+"</span>";this._elDropdown=doc.createElement("DIV");this._elDropdown.className="gtdi-dropdown-content";this._elDropdown.style.display="none";this.el.appendChild(this._elDropdown);var elDropdownItems=doc.createElement("DIV");elDropdownItems.className="gtdi-dropdown-items";this._elDropdown.appendChild(elDropdownItems);this._elDropdownList=doc.createElement("UL");elDropdownItems.appendChild(this._elDropdownList);this._reloadLabels();this._main.labelsData.addEventListener(gtdLabelsData.LABEL_CHANGED,
this._reloadLabels,this);this._main.gmail.actions.addEventListener(glActionManager.THREAD_CHANGED,this._threadChanged,this);this._showDropdownList(false)},disconnect:function(){if(this.el&&this.el.parentNode)this.el.parentNode.removeChild(this.el);this.el=null;for(p in this)if(this[p]&&this[p].nodeName&&this[p].nodeType)this[p]=null;this._eventsContainer.reset();this._eventsContainer=null;this._threads=null;this._main.labelsData.removeEventListener(gtdLabelsData.LABEL_CHANGED,this._reloadLabels,this);
this._main.gmail.actions.removeEventListener(glActionManager.THREAD_CHANGED,this._threadChanged,this);this.base()},loadThreads:function(threads){this._threads=threads;this._reorderLabels()},_reorderLabels:function(){var activeLabelsHash={};for(var i=0;i<this._threads.length;i++)for(var j=0;j<this._threads[i].labels.length;j++)activeLabelsHash[this._threads[i].labels[j]]=true;var activeLabelEls=[];var newActiveLabelEls=[];while(this._elDropdownList.childNodes.length>0&&this._elDropdownList.childNodes[0].getElementsByTagName("INPUT")[0].checked){var elLi=
this._elDropdownList.childNodes[0];elLi.getElementsByTagName("INPUT")[0].checked=false;if(activeLabelsHash[elLi.getAttribute("gtdi-labelname")])newActiveLabelEls.push(elLi);else activeLabelEls.push(elLi);this._elDropdownList.removeChild(elLi)}var firstInactiveNode=null;for(var i=0;i<this._elDropdownList.childNodes.length;i++)if(!activeLabelsHash[this._elDropdownList.childNodes[i].getAttribute("gtdi-labelname")]){firstInactiveNode=this._elDropdownList.childNodes[i];break}for(var i=0;i<this._elDropdownList.childNodes.length;i++){var elLi=
this._elDropdownList.childNodes[i];if(activeLabelEls.length>0){if(!elLi.getAttribute("gtdi-labelname"))giLogger.error("Could not find 'gtdi-labelname' attribute on label element","gtdLabelsMenu._reorderLabel",this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID);var labelname=elLi.getAttribute("gtdi-labelname").toLowerCase();var matches=[];for(var j=activeLabelEls.length-1;j>=0;j--){if(!activeLabelEls[j].getAttribute("gtdi-labelname"))giLogger.error("Could not find 'gtdi-labelname' attribute on 'active' label element in loop",
"gtdLabelsMenu._reorderLabel",this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID);if(activeLabelEls[j].getAttribute("gtdi-labelname").toLowerCase()<labelname){matches.push(activeLabelEls[j]);activeLabelEls.splice(j,1)}}matches.reverse();for(var j=0;j<matches.length;j++){this._elDropdownList.insertBefore(matches[j],elLi);i++;if(activeLabelsHash[matches[j].getAttribute("gtdi-labelname")])newActiveLabelEls.push(matches[j])}}if(activeLabelsHash[elLi.getAttribute("gtdi-labelname")])newActiveLabelEls.push(elLi)}for(var i=
0;i<activeLabelEls.length;i++){if(activeLabelsHash[activeLabelEls[i].getAttribute("gtdi-labelname")])newActiveLabelEls.push(activeLabelEls[i]);this._elDropdownList.appendChild(activeLabelEls[i])}for(var i=0;i<newActiveLabelEls.length;i++){newActiveLabelEls[i].getElementsByTagName("INPUT")[0].checked=true;if(firstInactiveNode)this._elDropdownList.insertBefore(newActiveLabelEls[i],firstInactiveNode);else this._elDropdownList.appendChild(newActiveLabelEls[i])}},_reloadLabels:function(event){this._elDropdownList.innerHTML=
"";var labels=this._main.labelsData.getLabelsArray(null,null,true);labels.sort(function(x,y){if(!x||!y)giLogger.error("Label param missing in sort function","gtdLabelsMenu._reloadLabels",this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID);if(x.toLowerCase()>y.toLowerCase())return 1;else return-1});var doc=this._main.gmail.canvasDocument;for(var i=0;i<labels.length;i++){var elLi=doc.createElement("LI");elLi.setAttribute("gtdi-labelname",labels[i]);elLi.innerHTML="<input type='checkbox'/><span>"+
labels[i]+"</span>";this._elDropdownList.appendChild(elLi)}},_threadChanged:function(event){for(var i=0;i<this._threads.length;i++)if(this._threads[i].threadId==event.thread){this._reorderLabels();break}},_click:function(event){try{var el=event.target;var elTree=el;var clickedWithinEl=false;var c=0;while(elTree.parentNode&&++c<5){if(elTree.nodeName=="LI"&&elTree.parentNode==this._elDropdownList){clickedWithinEl=true;var labelname=elTree.getAttribute("gtdi-labelname");if(elTree.getElementsByTagName("INPUT")[0].checked)for(var i=
0;i<this._threads.length;i++)this._main.gmail.actions.performAction(glActionManager.REMOVE_LABEL,this._threads[i],this._serverActionType,labelname);else for(var i=0;i<this._threads.length;i++)this._main.gmail.actions.performAction(glActionManager.ADD_LABEL,this._threads[i],this._serverActionType,labelname);if(el.nodeName!="INPUT");this._showDropdownList(false);break}if(elTree==this.el){clickedWithinEl=true;if(this._elDropdown.style.display=="none")this._showDropdownList(true);break}elTree=elTree.parentNode}if(!clickedWithinEl&&
this._elDropdown.style.display=="")this._showDropdownList(false)}catch(e){giLogger.warn(e,"gtdLabelsMenu._click",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}},_showDropdownList:function(show){if(show){this._elDropdown.style.display="";this._eventsContainer.stopObserving(this.el,"mousedown",this._click,false);setTimeout(giUtil.bind(this,function(){this._eventsContainer.observe(this.el.ownerDocument.body,"mousedown",this._click,false)}),10)}else{this._elDropdown.style.display="none";
this._eventsContainer.stopObserving(this.el.ownerDocument.body,"mousedown",this._click,false);setTimeout(giUtil.bind(this,function(){this._eventsContainer.observe(this.el,"mousedown",this._click,false)}),10)}},setServerActionType:function(type){this._serverActionType=type}},{});gtdLabelsMenu.implement(giEventDispatcher);
