var gtdLabelsTree=giUIObject.extend({el:null,type:null,_prefix:null,_eventsContainer:null,labelHash:null,connect:function(main){giLogger.log("st","gtdLabelsTree.connect",main?main.pageId:giLogger.UNKNOWN_PAGE_ID);this.base(main)},init:function(type,el){this.type=type;this._eventsContainer=new giEventsContainer(this);this.labelHash={};var typeSettings=this._main.prefs.getPref("labels.types");this._prefix=typeSettings[type].prefix;var doc=this._main.gmail.canvasDocument;if(el)this.el=el;else this.el=
doc.createElement("DIV");giUIObject.addClassName(this.el,"gtdi-labeldom");this._eventsContainer.observe(this.el,"click",this._click,false)},disconnect:function(){this._main=null;this.type=null;if(this.el.parentNode)this.el.parentNode.removeChild(this.el);this.el=null;this._eventsContainer.reset();this._eventsContainer=null;this.base()},addLabel:function(label){try{var doc=this._main.gmail.canvasDocument;var labelDisplayName=null;var el=null;var depth=0;var leafnameComputed=null;var labelname=label;
el=doc.createElement("DIV");giUIObject.addClassName(el,"gtdi-labeldom-label");el.setAttribute("gtdLabelName",labelname);this.labelHash[labelname]=el;var elContainer=this._getContainer(labelname,el);this.el.appendChild(el);var labelDisplayName=gtdLabelsData.removePrefix(labelname,this._prefix);var hierarchy=labelDisplayName.split("/");var leafnameComputed=hierarchy[hierarchy.length-1];var leafname=null;if(hierarchy.length>1){leafname=leafnameComputed;depth=hierarchy.length-1;var lastLabel=labelname;
var hadParent=false;while(hierarchy.length>1){hierarchy.length=hierarchy.length-1;var parentLabel=this._prefix+hierarchy.join("/");var elParent=this.labelHash[parentLabel];hadParent=!!this.labelHash[parentLabel];if(!hadParent){var elParent=null;var parentLeaf=gtdLabelsData.removePrefix(hierarchy[hierarchy.length-1],this._prefix);elParent=doc.createElement("DIV");elParent.innerHTML=parentLeaf||"/";elParent.setAttribute("gtdi-leaf",parentLeaf);giUIObject.addClassName(elParent,"gtdi-labeldom-label");
giUIObject.addClassName(elParent,"gtdi-labeldom-placeholder");var elParentContainer=this._getContainer(parentLabel,elParent);elParent.setAttribute("gtdi-depth",hierarchy.length-1);elParentContainer.style.paddingLeft=10+(hierarchy.length-1)*10+"px";elParentContainer.style.paddingLeft=(hierarchy.length-1)*(gtdLabelsTree.IMG_WIDTH_PX+gtdLabelsTree.IMG_GAP_PX)+(gtdLabelsTree.IMG_WIDTH_PX+gtdLabelsTree.IMG_GAP_PX)+"px";elParent.setAttribute("gtdi-placeholder","1");elParent.setAttribute("gtdi-type",this.type);
elParent.setAttribute("gtdLabelName",parentLabel);this.labelHash[lastLabel].parentNode.insertBefore(elParent,this.labelHash[lastLabel]);this.labelHash[parentLabel]=elParent;lastLabel=parentLabel}if(!this.getExpander(parentLabel,elParent)){var elExpander=doc.createElement("IMG");elExpander.className="gtdi-labeldom-expander";elExpander.src=giUrl.getURL("skin/gtd/triangle.gif");var elExpanderParent=this._getContainer(parentLabel,elParent);elExpander.style.paddingLeft=parseInt(elExpanderParent.getAttribute("gtdi-depth"))*
(gtdLabelsTree.IMG_WIDTH_PX+gtdLabelsTree.IMG_GAP_PX)+"px";elExpanderParent.insertBefore(elExpander,elExpanderParent.firstChild)}if(hierarchy.length-1>0)elParent.style.display="none";if(hadParent)break}}else leafname=labelDisplayName;el.setAttribute("gtdi-depth",depth);el.style.paddingLeft=depth*(gtdLabelsTree.IMG_WIDTH_PX+gtdLabelsTree.IMG_GAP_PX)+(gtdLabelsTree.IMG_WIDTH_PX+gtdLabelsTree.IMG_GAP_PX)+"px";if(depth>0)el.style.display="none";var elLeaf=doc.createElement("SPAN");elLeaf.className="gtdi-labeldom-label-leaf";
el.appendChild(elLeaf);elLeaf.innerHTML=leafname||"/";elLeaf.setAttribute("gtdi-leaf",leafnameComputed);el.setAttribute("gtdi-type",this.type)}catch(e){giLogger.warn(e,"gtdLabelDOM.addLabel",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}},finishAddingLabels:function(){var labelHash={};var labels=[];for(l in this.labelHash)labels.push(l);labels.sort();for(var i=0;i<labels.length;i++)labelHash[labels[i]]=this.labelHash[labels[i]];this.labelHash=labelHash},_getContainer:function(labelname,
el,elFailsafe){if(!el)el=this.getLabel(labelname);if(el){var elContainer=el.ownerDocument.evaluate(".//*[@gtdi-container]",el,null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue;return elContainer||el}},_click:function(event){try{var el=event.target;if(el.className=="gtdi-labeldom-expander"){while(el.parentNode&&!el.getAttribute("gtdLabelName"))el=el.parentNode;var labelname=el.getAttribute("gtdLabelName");if(labelname)if(this.isExpanded(labelname))this.close(labelname);else this.open(labelname,
true)}}catch(e){giLogger.warn(e,"gtdLabelsTree._click",null,this._main.gmail)}},getLabel:function(labelname){return this.labelHash[labelname]},getDepth:function(labelname){var el=this.getLabel(labelname);if(el)return parseInt(el.getAttribute("gtdi-depth"))||0;else return 0},isPlaceHolder:function(labelname){var el=this.getLabel(labelname);return el&&el.getAttribute("gtdi-placeholder")?true:false},getLeaf:function(labelname){var el=this.getLabel(labelname);if(el.hasAttribute("gtdi-leaf"))return el;
else return el.ownerDocument.evaluate(".//*[@gtdi-leaf]",el,null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue},getLeafName:function(labelname){var el=this.getLeaf(labelname);if(el)return el.getAttribute("gtdi-leaf");else return""},selected:function(labelname,isOn){var el=this.getLabel(labelname);if(el){if(typeof isOn=="undefined")return giUIObject.hasClassName(el,"gtdi-active");if(isOn)giUIObject.addClassName(el,"gtdi-active");else giUIObject.removeClassName(el,"gtdi-active")}},getSelectedLabelNames:function(){var labels=
[];var result=this.el.ownerDocument.evaluate(".//*[contains(@class,'gtdi-labeldom-label') and contains(@class,'gtdi-active')]",this.el,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null);for(var i=0;i<result.snapshotLength;i++)labels.push(result.snapshotItem(i).getAttribute("gtdLabelName"));return labels},getExpander:function(labelname,el){if(!el)el=this.getLabel(labelname);if(el)return el.ownerDocument.evaluate(".//IMG[contains(@class,'gtdi-labeldom-expander')]",el,null,XPathResult.FIRST_ORDERED_NODE_TYPE,
null).singleNodeValue},isExpanded:function(labelname,elExpander){elExpander=elExpander||this.getExpander(labelname);return elExpander.src==giUrl.getURL("skin/gtd/opentriangle.gif")?true:false},_setExpander:function(labelname,open,elImg){if(!elImg)elImg=this.getExpander(labelname);if(open){elImg.src=giUrl.getURL("skin/gtd/opentriangle.gif");elImg.title=giI18N.getString("LabelDOM.expander.closer")}else{elImg.src=giUrl.getURL("skin/gtd/triangle.gif");elImg.title=giI18N.getString("LabelDOM.expander.opener")}},
getChildren:function(labelname){var depth=this.getDepth(labelname)+1;var children=[];var foundFirstInSortedOrder=false;for(l in this.labelHash){if(l==labelname)foundFirstInSortedOrder=true;if(foundFirstInSortedOrder){var elChild=this.labelHash[l];if(elChild.getAttribute("gtdi-depth")==depth&&elChild.getAttribute("gtdLabelName").indexOf(labelname)==0)children.push(elChild.getAttribute("gtdLabelName"));if(children.length>0&&elChild.getAttribute("gtdLabelName").indexOf(labelname)!=0)break}}return children},
getParent:function(labelname){var hierarchy=labelname.split("/");if(hierarchy.length>0){hierarchy.length=hierarchy.length-1;var parentLabel=hierarchy.join("/");return this.getLabel(parentLabel)}},getLabelsArray:function(exclPlaceHolders,labels){var labels=labels||[];for(l in this.labelHash)if(!(exclPlaceHolders&&this.isPlaceHolder(l)))labels.push(l);return labels},getLabelsHash:function(exclPlaceHolders,labels){var labels=labels||{};for(l in this.labelHash)if(!(exclPlaceHolders&&this.isPlaceHolder(l)))labels[l]=
this.labelHash[l];return labels},open:function(labelname,ignoreParents){var labels=[labelname];if(!ignoreParents){var hierarchy=labelname.split("/");while(hierarchy.length>0){hierarchy.length=hierarchy.length-1;var parentLabel=hierarchy.join("/");if(this.getLabel(parentLabel))labels.push(parentLabel)}}for(var i=0;i<labels.length;i++){var el=this.getLabel(labels[i]);if(el){el.style.display="";if(elExpander=this.getExpander(labels[i]))this._setExpander(null,true,elExpander);var children=this.getChildren(labels[i]);
for(var j=0;j<children.length;j++){var elChild=this.getLabel(children[j]);if(elChild)elChild.style.display=""}}}},close:function(labelname){var foundFirstInSortedOrder=false;for(l in this.labelHash){if(!labelname||l==labelname)foundFirstInSortedOrder=true;if(foundFirstInSortedOrder){var el=this.labelHash[l];var elLabelName=el.getAttribute("gtdLabelName");if(!labelname||labelname==elLabelName||elLabelName.indexOf(labelname+"/")==0){if(elExpander=this.getExpander(l))this._setExpander(null,false,elExpander);
if(!labelname&&this.getDepth(l)>0||labelname&&l!=labelname)el.style.display="none"}if(labelname&&foundFirstInSortedOrder){var elLabelName=el.getAttribute("gtdLabelName");if(elLabelName!=labelname&&elLabelName.indexOf(labelname+"/")!=0)break}}}}},{IMG_WIDTH_PX:9,IMG_GAP_PX:4});
