var gtdStatsDayBox=boxSection.extend({_dayStats:null,connect:function(main){giLogger.log("st","gtdStatsDayBox.connect",main?main.pageId:giLogger.UNKNOWN_PAGE_ID);this._main=main;var box=giPluginManager.getPluginInstance(boxMain,this._main.gmail);this._labelsTrees={};this.id="gtdstatsdaybox";this.base(box);var doc=this._main.gmail.canvasDocument;this.elRow=doc.createElement("UL");this.elRow.className="gtdi-stats-notifier gtdi-threecol";this._elRowCategorised=doc.createElement("LI");this._elRowCategorised.className=
"gtdi-categorised";this.elRow.appendChild(this._elRowCategorised);this._elRowCategorisedItem=doc.createElement("SPAN");this._elRowCategorisedItem.innerHTML=0;this._elRowCategorised.appendChild(this._elRowCategorisedItem);this._elRowCompleted=doc.createElement("LI");this._elRowCompleted.className="gtdi-done";this.elRow.appendChild(this._elRowCompleted);this._elRowCompletedItem=doc.createElement("SPAN");this._elRowCompletedItem.innerHTML=0;this._elRowCompleted.appendChild(this._elRowCompletedItem);
this._elRowToDo=doc.createElement("LI");this._elRowToDo.className="gtdi-toprocess";this.elRow.appendChild(this._elRowToDo);this._elRowToDoItem=doc.createElement("SPAN");this._elRowToDoItem.innerHTML=0;this._elRowToDo.appendChild(this._elRowToDoItem);this.elPopout=doc.createElement("DIV");this._popoutRows={};this._popoutRows.categorised={};var elCategorisedHeader=doc.createElement("H2");elCategorisedHeader.innerHTML=giI18N.getString("stats.daybox.popout.categorised");this.elPopout.appendChild(elCategorisedHeader);
var categorised=["actioned","labelled"];for(var i=0;i<categorised.length;i++){this._popoutRows.categorised[categorised[i]]={};this._popoutRows.categorised[categorised[i]].elRow=doc.createElement("DIV");this._popoutRows.categorised[categorised[i]].elRow.className="gtdi-stats-daybox-popout-row";this._popoutRows.categorised[categorised[i]].elRow.innerHTML=giI18N.getString("stats.daybox.popout.categorised."+categorised[i]);this._popoutRows.categorised[categorised[i]].elItem=doc.createElement("SPAN");
this._popoutRows.categorised[categorised[i]].elRow.appendChild(this._popoutRows.categorised[categorised[i]].elItem);this.elPopout.appendChild(this._popoutRows.categorised[categorised[i]].elRow)}this._addRow("daybox",this.elRow,this.elPopout);this._dayStats=this._main.prefs.getPref("stats.day");var d=new Date;var todayStr=d.getFullYear()+d.getMonth()+d.getDate();if(!this._dayStats||this._dayStats.date!=todayStr)this._dayStats={date:todayStr};if(!this._dayStats.categorised)this._dayStats.categorised=
{};if(!this._dayStats.categorised.actioned)this._dayStats.categorised.actioned={};if(!this._dayStats.categorised.labelled)this._dayStats.categorised.labelled={};if(!this._dayStats.completed)this._dayStats.completed={};if(!this._dayStats.completed.archived_no_action)this._dayStats.completed.archived_no_action={};if(!this._dayStats.completed.action_finished)this._dayStats.completed.action_finished={};if(!this._dayStats.completed.spammed)this._dayStats.completed.spammed={};if(!this._dayStats.completed.deleted)this._dayStats.completed.deleted=
{};var sections=[this._dayStats.categorised,this._dayStats.completed];for(var i=0;i<sections.length;i++){var section=sections[i];for(t in section)if(section.hasOwnProperty(t)){var count=0;for(p in section[t])if(p!="count"&&section[t].hasOwnProperty(p))count=count+1;section[t].count=count}}this._main.prefs.setPref("stats.day",this._dayStats);this._main.gmail.actions.addEventListener(glActionManager.THREAD_CHANGED,this._threadChanged,this);this._main.statusThreadsContainer.addEventListener(glThreadContainer.CHANGED,
this._threadChanged,this);this._main.statusThreadsContainer.addEventListener(gtdStatusThreadContainer.LABEL_ZERO,this._labelZero,this)},disconnect:function(){this._main.gmail.actions.removeEventListener(glActionManager.THREAD_CHANGED,this._threadChanged,this);this._main.statusThreadsContainer.removeEventListener(glThreadContainer.CHANGED,this._threadChanged,this);this._main.statusThreadsContainer.removeEventListener(gtdStatusThreadContainer.LABEL_ZERO,this._labelZero,this);this.base()},_threadChanged:function(evt){var statusData=
this._main.labelsData.getStatusData();var changed=false;if(evt.name==glActionManager.THREAD_CHANGED){if(evt.action==glActionManager.ARCHIVE)if(!this._dayStats.completed.action_finished[evt.thread]&&!this._main.statusThreadsContainer.getThreadById(evt.thread)){this._dayStats.completed.archived_no_action[evt.thread]=true;changed=true}}else if(evt.name==glThreadContainer.CHANGED){if(evt.addedThreads.length>0)for(var i=0;i<evt.addedThreads.length;i++){var threadId=evt.addedThreads[i];if(this._dayStats.completed.action_finished[threadId]){delete this._dayStats.completed.action_finished[threadId];
changed=true}}if(evt.removedThreads.length>0){for(var i=0;i<evt.removedThreads.length;i++){var threadId=evt.removedThreads[i];this._dayStats.completed.action_finished[threadId]=true;if(!this._dayStats.completed.archived_no_action[threadId])delete this._dayStats.completed.archived_no_action[threadId]}changed=true}}if(changed)this._main.prefs.setPref("stats.day",this._dayStats)},_labelZero:function(evt){}});
