var gtdThreadListPreviewer=giUIObject.extend({_threadListTable:null,_elRow:null,_currentBrowser:null,_currentPopup:null,connect:function(main){this.base(main)},disconnect:function(){this.base()},load:function(elRow,positioningObject,threadListAlreadyChecked){try{this._elRow=elRow;var doc=this._main.gmail.canvasDocument;var threadListView=this._main.gmail.getCurrentViewObject();this._threadListTable=threadListView.getThreadListTableByEl(elRow);threadListView.uncheckRows();if(!this._threadListTable.threadsAreLoaded)this._threadListTable.getThreads();
this._currentBrowser=gtdBrowser.createBrowser(this._main,null,gtdBrowser.TYPES.THREAD);this._currentPopup=this._main.getUIObject("browserPopup");this._currentPopup.load(this._currentBrowser);this._currentPopup.setServerActionType(glActionManager.USE_AJAX_SYNC);this._currentPopup.addEventListener(gtdBrowserPopup.HIDE,this._closeThreadPopup,this);this._currentBrowser.addEventListener(gtdBrowserThread.MOVE_NEXT,this._movePreview,this);this._currentBrowser.addEventListener(gtdBrowserThread.MOVE_PREVIOUS,
this._movePreview,this);this._main.gmail.actions.addEventListener(glActionManager.THREAD_CHANGED,this._threadChanged,this);this._hadThreadChange=false;this._threadListTable.addEventListener(glThreadListTable.UI_REFRESHED,this._uiRefreshed,this);this._threadListTable.addEventListener(glThreadListTable.THREADS_LOADED,this._load,this);if(this._threadListTable.threadsAreLoaded)this._load()}catch(e){giLogger.warn(e,"gtdThreadListPreviewer.load",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}},
_uiRefreshed:function(){giLogger.log("st","gtdThreadListPreviewer._uiRefreshed",this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID);try{var currentThread=this._currentBrowser.getThread();if(currentThread)this._selectThreadListRow();if(this._threadListTable.threadsAreLoaded)this._load();else this._threadListTable.getThreads()}catch(e){giLogger.warn(e,"gtdThreadListPreviewer._uiRefreshed",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}},_load:function(evt){giLogger.log("st","gtdThreadListPreviewer._load",
this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID);try{var threads=this._threadListTable.getThreads();if(threads.length>0){var currentThread=this._currentBrowser.getThread();if(currentThread){var found=false;for(var i=0;i<threads.length;i++)if(currentThread.hasId(threads[i].threadId)){found=true;currentThread=threads[i];break}if(!found){giLogger.logConcern("After reload of threads from glThreadListTable, the current thread was no longer in the collection. Resorting to first thread.","gtdThreadListPreviewer._load",
this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID);currentThread=threads[0]}this._currentBrowser.load(null,currentThread);this._currentBrowser.setThreads(threads)}else{var offset=this._threadListTable.getRowOffset(this._elRow);var thread=this._threadListTable.getThread(offset);this._currentBrowser.load(null,thread);this._currentBrowser.setThreads(threads)}this._selectThreadListRow()}else{giLogger.logConcern("After a (re)load, there were no threads found by glThreadListTable. Closing Previewer.",
"gtdThreadListPreviewer._load",this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID);this._currentPopup.hide()}}catch(e){giLogger.warn(e,"gtdThreadListPreviewer._load",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}},_closeThreadPopup:function(){var gmailThreadListView=this._main.gmail.getCurrentViewObject();gmailThreadListView.uncheckRows();if(this._hadThreadChange)this._main.gmail.environment.requestRefreshTL();var popup=this._main.getUIObject("browserPopup");popup.removeEventListener(gtdBrowserPopup.HIDE,
this._closeThreadPopup,this);this._currentBrowser.removeEventListener(gtdBrowserThread.MOVE_NEXT,this._movePreview,this);this._currentBrowser.removeEventListener(gtdBrowserThread.MOVE_PREVIOUS,this._movePreview,this);this._main.gmail.actions.removeEventListener(glActionManager.THREAD_CHANGED,this._threadChanged,this);this._threadListTable.removeEventListener(glThreadListTable.UI_REFRESHED,this._uiRefreshed,this);this._threadListTable.removeEventListener(glThreadListTable.THREADS_LOADED,this._load,
this);this._threadListTable=null;this._elRow=null;this._elThreadListItem=null;this._currentBrowser=null},_threadChanged:function(evt){this._hadThreadChange=true},_selectThreadListRow:function(){try{var threadListView=this._main.gmail.getCurrentViewObject();threadListView.uncheckRows();var thread=this._currentBrowser.getThread();var subject=giUtil.decodeEntities(giUtil.stripTags(thread.subjectSnippetHtml));var date=giUtil.decodeEntities(giUtil.stripTags(thread.dateSnippetHtml));var contact=giUtil.decodeEntities(giUtil.stripTags(thread.contactsSnippetHtml));
var elTrs=this._threadListTable.elTable.getElementsByTagName("TR");if(this._threadListTable.threadsAreLoaded){var threads=this._currentBrowser.getThreads();var offset=-1;for(var i=0;i<threads.length;i++)if(threads[i].hasId(thread.threadId)){offset=i;break}if(offset>-1){var inner=giUtil.decodeEntities(giUtil.stripTags(elTrs[offset].innerHTML));if(inner.indexOf(subject)>-1&&inner.indexOf(date)>-1&&inner.indexOf(contact)>-1){this._threadListTable.checkRow(offset);return}else giLogger.logConcern("Offset indicated it had found the correct row, but didn't match text.\nSubject: "+
subject+"\nDate: "+date+"\nContact: "+contact+"\nRow: "+inner,"gtdThreadListPreviewer._selectThreadListRow",this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}}var idxs=[];for(var i=0;i<elTrs.length;i++){var inner=giUtil.decodeEntities(giUtil.stripTags(elTrs[i].innerHTML));if(inner.indexOf(subject)>-1&&inner.indexOf(date)>-1&&inner.indexOf(contact)>-1)idxs.push(i)}if(idxs.length>0)if(idxs.length==1)this._threadListTable.checkRow(idxs[0]);else if(this._threadListTable.threadsAreLoaded){var idxData=
null;var threadsInView=this._threadListTable.getThreads();for(var i=0;i<threadsInView.length;i++)if(thread.hasId(threadsInView[i].threadId)){idxData=i;break}if(idxData!==null){var minDiff=100;var currentIdx=null;for(var i=0;i<idxs.length;i++){var testDiff=idxs[i]-idxData;if(testDiff<0)testDiff*=-1;if(testDiff<minDiff){minDiff=testDiff;currentIdx=idxs[i]}}if(currentIdx)this._threadListTable.checkRow(currentIdx)}}}catch(e){giLogger.warn(e,"gtdThreadListPreviewer._selectThreadListRow",null,this._main?
this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}},_movePreview:function(evt){this._selectThreadListRow()},isCacheable:function(){return true}});
