var gtdTreeList=giUIObject.extend({el:null,type:null,labelType:null,_prefix:null,_eventsContainer:null,itemHash:null,connect:function(main){giLogger.log("st","gtdTreeList.connect",main?main.pageId:giLogger.UNKNOWN_PAGE_ID);this.base(main)},init:function(type,subType){this.type=type;this._eventsContainer=new giEventsContainer(this);this.itemHash={};if(type==gtdBrowser.TYPES.LABEL){if(subType){var typeSettings=this._main.prefs.getPref("labels.types");this._prefix=typeSettings[subType].prefix||""}}else if(type==
gtdBrowser.TYPES.STORED_SEARCH)if(subType)this._prefix=subType;var doc=this._main.gmail.canvasDocument;this.el=doc.createElement("DIV");giUIObject.addClassName(this.el,"gtdi-treelist");this._eventsContainer.observe(this.el,"click",this._click,false)},disconnect:function(){this._main=null;this.type=null;this.labelType=null;this._prefix=null;if(this.el.parentNode)this.el.parentNode.removeChild(this.el);this.el=null;this._eventsContainer.reset();this._eventsContainer=null;this.base()},addItem:function(item,
ignoreHierarchy){try{var doc=this._main.gmail.canvasDocument;var el=null;var depth=0;el=doc.createElement("DIV");giUIObject.addClassName(el,"gtdi-treelist-item");el.setAttribute("gtdi-item",item);el.setAttribute("gtdi-type",this.type);this.itemHash[item]=el;this.el.appendChild(el);var itemHierarchyName=item;if(this.type==gtdBrowser.TYPES.LABEL)if(this._prefix&&itemHierarchyName.indexOf(this._prefix)==0)itemHierarchyName=itemHierarchyName.replace(this._prefix,"");var hierarchy=itemHierarchyName.split("/");
if(this.type==gtdBrowser.TYPES.STORED_SEARCH)hierarchy.splice(0,1);var displayName=hierarchy[hierarchy.length-1];if(ignoreHierarchy)depth=0;else depth=hierarchy.length-1;if(!ignoreHierarchy&&hierarchy.length>1){var lastItem=item;var hadParent=false;while(hierarchy.length>1){hierarchy.length=hierarchy.length-1;var parentItem=hierarchy.join("/");if(this.type==gtdBrowser.TYPES.LABEL)parentItem=this._prefix+parentItem;var elParent=this.itemHash[parentItem];hadParent=!!elParent;if(!hadParent){var parentDisplayName=
hierarchy[hierarchy.length-1]||"/";elParent=doc.createElement("DIV");elParent.innerHTML="<span class='gtdi-treelist-item-name'>"+parentDisplayName+"</span>";elParent.getElementsByTagName("SPAN")[0].setAttribute("gtdi-item-name",parentDisplayName);giUIObject.addClassName(elParent,"gtdi-treelist-item");giUIObject.addClassName(elParent,"gtdi-treelist-placeholder");elParent.setAttribute("gtdi-depth",hierarchy.length-1);elParent.style.paddingLeft=10+(hierarchy.length-1)*10+"px";elParent.style.paddingLeft=
(hierarchy.length-1)*(gtdTreeList.IMG_WIDTH_PX+gtdTreeList.IMG_GAP_PX)+(gtdTreeList.IMG_WIDTH_PX+gtdTreeList.IMG_GAP_PX)+"px";elParent.setAttribute("gtdi-placeholder","1");elParent.setAttribute("gtdi-type",this.type);elParent.setAttribute("gtdi-item",parentItem);this.itemHash[lastItem].parentNode.insertBefore(elParent,this.itemHash[lastItem]);this.itemHash[parentItem]=elParent;lastItem=parentItem}if(!this.getExpander(parentItem,elParent)){var elExpander=doc.createElement("IMG");elExpander.className=
"gtdi-treelist-expander";elExpander.src=giUrl.getURL("skin/gtd/i/gtdi-tree-closed.png");elExpander.style.paddingLeft=parseInt(elParent.getAttribute("gtdi-depth"))*(gtdTreeList.IMG_WIDTH_PX+gtdTreeList.IMG_GAP_PX)+"px";elParent.insertBefore(elExpander,elParent.firstChild)}if(hierarchy.length-1>0)elParent.style.display="none";if(hadParent)break}}el.setAttribute("gtdi-depth",depth);if(!ignoreHierarchy)el.style.paddingLeft=depth*(gtdTreeList.IMG_WIDTH_PX+gtdTreeList.IMG_GAP_PX)+(gtdTreeList.IMG_WIDTH_PX+
gtdTreeList.IMG_GAP_PX)+"px";if(depth>0)el.style.display="none";var elName=doc.createElement("SPAN");elName.className="gtdi-treelist-item-name";elName.innerHTML=displayName||"/";elName.title=item;elName.setAttribute("gtdi-item-name",displayName);el.appendChild(elName)}catch(e){giLogger.warn(e,"gtdTreeList.addItem",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}},finishAdd:function(){var itemHash={};var items=[];for(l in this.itemHash)items.push(l);items.sort();for(var i=0;i<items.length;i++)itemHash[items[i]]=
this.itemHash[items[i]];this.itemHash=itemHash},_click:function(event){try{var el=event.target;if(el.className=="gtdi-treelist-expander"){while(el.parentNode&&!el.getAttribute("gtdi-item"))el=el.parentNode;var item=el.getAttribute("gtdi-item");if(item)if(this.isExpanded(item))this.close(item);else this.open(item,true)}}catch(e){giLogger.warn(e,"gtdTreeList._click",null,this._main.gmail.pageId)}},getItem:function(item){return this.itemHash[item]},getDepth:function(item){var el=this.getItem(item);if(el)return parseInt(el.getAttribute("gtdi-depth"))||
0;else return 0},isPlaceHolder:function(item){var el=this.getItem(item);return el&&el.getAttribute("gtdi-placeholder")?true:false},selected:function(item,isOn){var el=this.getItem(item);if(el){if(typeof isOn=="undefined")return giUIObject.hasClassName(el,"gtdi-active");if(isOn)giUIObject.addClassName(el,"gtdi-active");else giUIObject.removeClassName(el,"gtdi-active")}},getSelectedItems:function(){var items=[];var result=this.el.ownerDocument.evaluate(".//*[contains(@class,'gtdi-treelist-item') and contains(@class,'gtdi-active')]",
this.el,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null);for(var i=0;i<result.snapshotLength;i++)items.push(result.snapshotItem(i).getAttribute("gtdi-item"));return items},getExpander:function(item,el){if(!el)el=this.getItem(item);if(el)return el.ownerDocument.evaluate(".//IMG[contains(@class,'gtdi-treelist-expander')]",el,null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue},isExpanded:function(item,elExpander){elExpander=elExpander||this.getExpander(item);return elExpander.src==giUrl.getURL("skin/gtd/i/gtdi-tree-open.png")?
true:false},_setExpander:function(item,open,elImg){if(!elImg)elImg=this.getExpander(item);if(open){elImg.src=giUrl.getURL("skin/gtd/i/gtdi-tree-open.png");elImg.title=giI18N.getString("LabelDOM.expander.closer")}else{elImg.src=giUrl.getURL("skin/gtd/i/gtdi-tree-closed.png");elImg.title=giI18N.getString("LabelDOM.expander.opener")}},getChildren:function(item){var depth=this.getDepth(item)+1;var children=[];var foundFirstInSortedOrder=false;for(l in this.itemHash){if(l==item)foundFirstInSortedOrder=
true;if(foundFirstInSortedOrder){var elChild=this.itemHash[l];if(elChild.getAttribute("gtdi-depth")==depth&&elChild.getAttribute("gtdi-item").indexOf(item)==0)children.push(elChild.getAttribute("gtdi-item"));if(children.length>0&&elChild.getAttribute("gtdi-item").indexOf(item)!=0)break}}return children},getParent:function(item){var hierarchy=item.split("/");if(hierarchy.length>0){hierarchy.length=hierarchy.length-1;var parentItem=hierarchy.join("/");return this.getItem(parentItem)}},open:function(item,
ignoreParents){var items=[item];if(!ignoreParents){var hierarchy=item.split("/");while(hierarchy.length>0){hierarchy.length=hierarchy.length-1;var parentItem=hierarchy.join("/");if(this.getItem(parentItem))items.push(parentItem)}}for(var i=0;i<items.length;i++){var el=this.getItem(items[i]);if(el){el.style.display="";if(elExpander=this.getExpander(items[i]))this._setExpander(null,true,elExpander);var children=this.getChildren(items[i]);for(var j=0;j<children.length;j++){var elChild=this.getItem(children[j]);
if(elChild)elChild.style.display=""}}}},close:function(item){var foundFirstInSortedOrder=false;for(l in this.itemHash){if(!item||l==item)foundFirstInSortedOrder=true;if(foundFirstInSortedOrder){var el=this.itemHash[l];var itemFromEl=el.getAttribute("gtdi-item");if(!item||item==itemFromEl||itemFromEl.indexOf(item+"/")==0){if(elExpander=this.getExpander(l))this._setExpander(null,false,elExpander);if(!item&&this.getDepth(l)>0||item&&l!=item)el.style.display="none"}else break}}}},{IMG_WIDTH_PX:9,IMG_GAP_PX:4});
