var gtdThreadListCommands=giUIObject.extend({_eventsContainer:null,_threadListTables:null,elPopup:null,_currentPopupIcon:null,_currentThreadListTable:null,_popupTimeout:null,_lastElCmd:null,_elImgsAvailable:null,_elImgsInUse:null,connect:function(main){giLogger.log("st","gtdThreadListCommands.connect",main?main.pageId:giLogger.UNKNOWN_PAGE_ID);this.base(main);this._eventsContainer=new giEventsContainer(this);this._elImgsInUse={};this._elImgsAvailable={};var doc=this._main.gmail.canvasDocument;var viewRoot=
this._main.gmail.page.getViewRoot();var threadListView=this._main.gmail.getCurrentViewObject();this._threadListTables=threadListView.getThreadListTables();for(var i=0;i<this._threadListTables.length;i++){var threadListTable=this._threadListTables[i];threadListTable.addEventListener(glThreadListTable.UI_REFRESHED,this._integrateRows,this);this._integrateRows(null,threadListTable)}this.elPopup=this._main.gmail.canvasDocument.createElement("DIV");this.elPopup.id="gtdi-tlcmds-popup";this.elPopup.style.display=
"none";doc.body.appendChild(this.elPopup);var lineitems=["preview","action","finish","archive","del","spam"];for(var i=0;i<lineitems.length;i++){var elLi=doc.createElement("DIV");elLi.className="gtdi-tlcmds-popup-lineitem";elLi.setAttribute("gtdi-tlcmds-id",lineitems[i]);elLi.innerHTML=giI18N.getString("ThreadListUI.GTDBox.Popup.lineitem."+lineitems[i]);this.elPopup.appendChild(elLi)}this._eventsContainer.observe(viewRoot,"mousedown",this._click,true);this._eventsContainer.observe(this.elPopup,"mousedown",
this._click,true);this._main.gmail.offline.addEventListener(glOffline.GO_ONLINE,this._offlineStateChange,this);this._main.gmail.offline.addEventListener(glOffline.GO_UNSTABLE,this._offlineStateChange,this)},disconnect:function(){this._elImgsInUse=null;this._elImgsAvailable=null;this._main.gmail.offline.removeEventListener(glOffline.GO_ONLINE,this._offlineStateChange,this);this._main.gmail.offline.removeEventListener(glOffline.GO_UNSTABLE,this._offlineStateChange,this);if(this._popupTimeout)clearTimeout(this._popupTimeout);
if(this._currentThreadListTable){this._currentThreadListTable.removeEventListener(glThreadListTable.THREADS_LOADED,this._processCmdAction,this);this._currentThreadListTable=null}if(this.elPopup.parentNode)this.elPopup.parentNode.removeChild(this.elPopup);this._currentPopupIcon=null;this._threadListTables=null;this._eventsContainer.reset();this.base()},_offlineStateChange:function(evt){if(evt.name==glOffline.GO_ONLINE)for(var i=0;i<this._threadListTables.length;i++){var threadListTable=this._threadListTables[i];
this._integrateRows(null,threadListTable)}else if(evt.name==glOffline.GO_UNSTABLE)for(tid in this._elImgsInUse)if(this._elImgsInUse[tid]&&this._elImgsInUse[tid].length>0){var elImgsInUse=this._elImgsInUse[tid];for(var i=0;i<elImgsInUse.length;i++){var el=elImgsInUse[i];el.parentNode.removeChild(el)}this._elImgsAvailable[tid]=this._elImgsInUse[tid];this._elImgsInUse[tid]=null}},_integrateRows:function(evt,threadListTable){try{if(this._main.gmail.offline.isUnstable())return;if(!threadListTable)threadListTable=
evt.target;if(!threadListTable.elTable)return;var tid=threadListTable.id;if(this._elImgsInUse[tid]&&this._elImgsInUse[tid].length>0){this._elImgsAvailable[tid]=this._elImgsInUse[tid];this._elImgsInUse[tid]=null}var doc=this._main.gmail.canvasDocument;var previewEnabled=this._main.prefs.getPref("components.thread_list.preview_button.enabled");if(previewEnabled){var result=threadListTable.getLastTDInRows();if(result.snapshotLength>0)for(var i=0;i<result.snapshotLength;i++){result.snapshotItem(i).style.position=
"relative";result.snapshotItem(i).appendChild(this._getElImg(tid))}}}catch(e){giLogger.warn("Error in gtdThreadListCommands._integrateRows -> "+e.toString(),"gtdThreadListCommands._refresh",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}},_getElImg:function(tid){if(!this._elImgsInUse[tid])this._elImgsInUse[tid]=[];if(this._elImgsAvailable[tid]&&this._elImgsAvailable[tid].length>0){var elImg=this._elImgsAvailable[tid].shift();this._elImgsInUse[tid].push(elImg);return elImg}if(this._elImgsInUse[tid][0])var elImg=
this._elImgsInUse[tid][0].cloneNode(true);else{var elImg=this._main.gmail.canvasDocument.createElement("IMG");elImg.className="gtd-row-button";elImg.style.position="absolute";elImg.style.right="0px";elImg.src=giUrl.getURL("skin/gtd/gtd_lineitem.png");elImg.title=giI18N.getString("ThreadListUI.GTDBox.Tooltip")}this._eventsContainer.observe(elImg,"mouseover",this._mouseOver,true);this._elImgsInUse[tid].push(elImg);return elImg},_click:function(event){try{var elCmd=event.target;if(!(elCmd.className==
"gtd-row-button"||elCmd.getAttribute("gtdi-tlcmds-id")))return;giUtil.stopEvent(event);var threadListView=this._main.gmail.getCurrentViewObject();threadListView.uncheckRows();if(elCmd.className=="gtd-row-button"||elCmd.getAttribute("gtdi-tlcmds-id")=="preview"){var threadListPreviewer=this._main.getUIObject("threadListPreviewer");threadListPreviewer.load(this._currentPopupIcon,this._currentPopupIcon,true);this._hidePopup()}else if(this._currentThreadListTable.threadsAreLoaded)this._processCmdAction(null,
elCmd);else{giLogger.log("wait for THREADS_LOADED before _processCmdAction","gtdThreadListCommands._click",this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID);this._lastElCmd=elCmd;this._currentThreadListTable.addEventListener(glThreadListTable.THREADS_LOADED,this._processCmdAction,this);this._currentThreadListTable.getThreads()}}catch(e){giLogger.warn(e,"gtdThreadListCommands._click",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}},_processCmdAction:function(evt,elCmd){try{giLogger.log("st",
"gtdThreadListCommands._processCmdAction",this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID);if(!this._currentPopupIcon)return;if(!elCmd)elCmd=this._lastElCmd;this._lastElCmd=null;var threadListView=this._main.gmail.getCurrentViewObject();this._currentThreadListTable.removeEventListener(glThreadListTable.THREADS_LOADED,this._processCmdAction,this);var offset=this._currentThreadListTable.getRowOffset(this._currentPopupIcon);this._currentThreadListTable.checkRow(offset);var thread=this._currentThreadListTable.getThread(offset);
var id=elCmd.getAttribute("gtdi-tlcmds-id");giLogger.log("switch on cmd id: "+id,"gtdThreadListCommands._processCmdAction",this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID);var requestRefresh=false;switch(id){case "archive":this._main.gmail.actions.performAction(glActionManager.ARCHIVE,thread.threadId,glActionManager.USE_DOM,null,this._currentThreadListTable.actionsHeader);break;case "finish":var status=this._main.labelsData.getStatusData();if(this._main.labelsData.hasLabel(status.finished))this._main.gmail.actions.performAction(glActionManager.ADD_LABEL,
thread.threadId,glActionManager.USE_AJAX,status.finished);this._main.gmail.actions.performAction(glActionManager.MARK_AS_READ,thread.threadId,glActionManager.USE_AJAX);this._main.gmail.actions.performAction(glActionManager.ARCHIVE,thread.threadId,glActionManager.USE_DOM,null,this._currentThreadListTable.actionsHeader);if(threadListView.hasMultipleInboxes()&&this._main.gmail.page.locationIsInbox()&&this._main.gmail.page.locationHash().indexOf("#inbox/p")==-1)requestRefresh=true;break;case "action":var status=
this._main.labelsData.getStatusData();if(this._main.labelsData.hasLabel(status.action))this._main.gmail.actions.performAction(glActionManager.ADD_LABEL,thread.threadId,glActionManager.USE_AJAX,status.action);this._main.gmail.actions.performAction(glActionManager.ARCHIVE,thread.threadId,glActionManager.USE_DOM,null,this._currentThreadListTable.actionsHeader);if(threadListView.hasMultipleInboxes()&&this._main.gmail.page.locationIsInbox()&&this._main.gmail.page.locationHash().indexOf("#inbox/p")==-1)requestRefresh=
true;break;case "del":this._main.gmail.actions.performAction(glActionManager.DELETE,thread.threadId,glActionManager.USE_DOM,null,this._currentThreadListTable.actionsHeader);break;case "spam":this._main.gmail.actions.performAction(glActionManager.REPORT_SPAM,thread.threadId,glActionManager.USE_DOM,null,this._currentThreadListTable.actionsHeader);break}this._hidePopup();if(requestRefresh){var me=this;setTimeout(function(){me._main.gmail.environment.requestRefreshTL()},750)}}catch(e){giLogger.warn(e,
"gtdThreadListCommands._processCmdAction",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}},_mouseOver:function(evt){if(evt.target.className=="gtd-row-button")try{var el=evt.target;if(this._currentPopupIcon!=el){var threadListView=this._main.gmail.getCurrentViewObject();this._currentThreadListTable=threadListView.getThreadListTableByEl(el);this._currentThreadListTable.getThreads();if(this._popupTimeout){clearTimeout(this._popupTimeout);this._popupTimeout=null}var observeMove=false;if(this._currentPopupIcon)this._currentPopupIcon.src=
giUrl.getURL("skin/gtd/gtd_lineitem.png");else observeMove=true;this._currentPopupIcon=el;this._currentPopupIcon.src=giUrl.getURL("skin/gtd/gtd_lineitem-hover.png");if(this._main.serverAccount.getAccountType()==giServerAccount.TYPES.PLUS){var permitted=null;var status=this._main.labelsData.getStatusData();if(this._currentThreadListTable.actionsHeader){var labels=threadListView.getDOMRowLabels(el);var permitAction=true;if(!this._main.labelsData.hasLabel(status.action))permitAction=false;if(permitAction)for(var i=
0;i<labels.length;i++)if(gtdLabelsData.testPrefix(labels[i],status.prefix)){permitAction=false;break}permitted={preview:true,del:true,spam:true};if(this._main.gmail.page.locationHash().indexOf("inbox")>=-1)permitted.archive=true;permitted.action=permitAction;permitted.finish=this._main.labelsData.hasLabel(status.finished)}else permitted={preview:true};for(var i=0;i<this.elPopup.childNodes.length;i++){var elLi=this.elPopup.childNodes[i];elLi.style.display=permitted[elLi.getAttribute("gtdi-tlcmds-id")]?
"":"none"}this.elPopup.style.display="";var viewport=giUIObject.viewport(this._main.gmail.canvasDocument);var offset=giUIObject.cumulativeOffset(this._currentPopupIcon);var dims=giUIObject.getDimensions(this._currentPopupIcon);var popupDims=giUIObject.getDimensions(this.elPopup);var xy=giUIObject.boundsCheckXY(this.elPopup,0,offset[1],true);this.elPopup.style.top=xy[1]+"px";if(dims.width+offset[0]+popupDims.width>viewport[0])this.elPopup.style.left=offset[0]-popupDims.width+"px";else this.elPopup.style.left=
offset[0]+dims.width+"px"}if(observeMove)this._eventsContainer.observe(this._main.gmail.canvasDocument.body,"mousemove",this._mouseMove,false)}}catch(e){giLogger.warn(e,"gtdThreadListCommands._mouseOver",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}},_mouseMove:function(evt){var el=evt.target;var i=3;while(--i>=0&&el!=this._currentPopupIcon&&el!=this.elPopup&&el.parentNode)el=el.parentNode;if(el==this._currentPopupIcon||el==this.elPopup){if(this._popupTimeout){clearTimeout(this._popupTimeout);
this._popupTimeout=null}return}if(!this._popupTimeout)this._popupTimeout=setTimeout(giUtil.bind(this,this._hidePopup),150)},_hidePopup:function(){if(this._currentThreadListTable){this._currentThreadListTable.removeEventListener(glThreadListTable.THREADS_LOADED,this._processCmdAction,this);this._currentThreadListTable=null}this._eventsContainer.stopObserving(this._main.gmail.canvasDocument.body,"mousemove",this._mouseMove,false);this.elPopup.style.display="none";this._currentPopupIcon.src=giUrl.getURL("skin/gtd/gtd_lineitem.png");
this._currentPopupIcon=null}});
