var boxAbout=boxSection.extend({boxNews:null,_elBlogNew:null,connect:function(main){this.id="boxabout";this.base(main);this.boxNews=this._main.getUIObject("news");this.boxNews.addEventListener(boxNews.BLOG_UPDATED,this._blogUpdated,this);var links=[["support","http://gtdinbox.com/support.htm"],["blog","http://blog.gtdinbox.com"]];if(this._main.serverAccount.getAccountType()!=giServerAccount.TYPES.PLUS)links.push(["discoverpremium","http://www.gtdinbox.com/account/buyplus.php"]);if(this._main.serverAccount.isRegistered())links.push(["manageaccount",
"http://www.gtdinbox.com/account/manage.php"]);for(var i=0;i<links.length;i++){var elRow=this._main.gmail.doc.createElement("DIV");elRow.innerHTML="<a href='"+links[i][1]+"' target='_blank'>"+giI18N.getString("Box.about."+links[i][0])+"</a>";var data=null;if(links[i][0]=="blog"){data=this._addRow(links[i][0],elRow,this.boxNews.el);data.el.setAttribute("gtdi-link-id",links[i][0]);this._elBlogNew=this._main.gmail.doc.createElement("IMG");this._elBlogNew.className="gtdi-news-new";this._elBlogNew.style.display=
"none";this._elBlogNew.src=giUrl.getURL("skin/box/newitem.png");data.el.appendChild(this._elBlogNew)}else data=this._addRow(links[i][0],elRow);data.el.setAttribute("gtdi-link-id",links[i][0])}var elRow=this._main.gmail.doc.createElement("DIV");elRow.className="gtdi-legalnotice-link";elRow.innerHTML="<a href='#' onclick=\"javascript:alert('"+giI18N.getString("LegalNotice")+"');return false;\">"+giI18N.getString("Box.about.legalnotice")+"</a>";this._addRow("legalnotice",elRow);var elRow=this._main.gmail.doc.createElement("DIV");
elRow.className="gtdi-versioninfo";elRow.innerHTML=giPluginManager.version+" "+giI18N.getString("Box.about.versioninfo.beta");this._addRow("legalnotice",elRow);this._eventsContainer.observe(this.el,"mousedown",this._click,false);var elForceChatContainer=this._main.gmail.doc.createElement("DIV");elForceChatContainer.id="gtdi-boxpref-force-container";var elForceChat=this._main.gmail.doc.createElement("INPUT");elForceChat.setAttribute("type","checkbox");elForceChat.checked=this._main.prefs.getPref("force_above_chat");
elForceChat.id="gtdi-boxpref-force";elForceChatContainer.appendChild(elForceChat);elForceChatContainer.appendChild(this._main.gmail.doc.createTextNode("Force above Chat"));this._addRow("force_chat",elForceChatContainer);this._eventsContainer.observe(elForceChat,"click",function(evt){this._main.prefs.setPref("force_above_chat",elForceChat.checked,true);alert("Please refresh Gmail for changes to take affect.")},false);this._isExpandable(true)},disconnect:function(){if(this.boxNews){this.boxNews.disconnect();
this.boxNews=null}this._elBlogNew=null;this.base()},_click:function(evt){try{if(evt.button==2)return;var el=evt.target;var elLink=el;if(elLink.nodeName!="A")elLink=elLink.getElementsByTagName("A")[0];var elRow=null;while(el.parentNode&&!elRow){if(el==this.el)break;if(el.getAttribute("gtdi-link-id"))elRow=el;el=el.parentNode}if(elRow){var link=elLink.href;if(link)if(elRow.getAttribute("gtdi-link-id")=="blog")this.boxNews.unmarkNew();return false}}catch(e){giLogger.warn(e,"boxAbout._click",null,this._main?
this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}},_blogUpdated:function(evt){if(evt.newItems>0)giUIObject.addClassName(this._elBlogNew.parentNode,"gtdi-news-bloglink-isnew");else giUIObject.removeClassName(this._elBlogNew.parentNode,"gtdi-news-bloglink-isnew");if(evt.newItems>0)this._elBlogNew.style.display="";else this._elBlogNew.style.display="none";this._elBlogNew.title=giI18N.getString("News.blog.new.title").replace("%1",evt.newItems)},expanded:function(v){if(v)for(var i=0;i<this._rows.length;i++)this._rows[i].el.style.display=
"";else if(typeof v!="undefined")for(var i=0;i<this._rows.length;i++)this._rows[i].el.style.display="none";return this.base(v)},_showPopout:function(row){if(row.id=="blog")if(!this.boxNews.isInitiated())this.boxNews.refresh();this.base(row)},loadServerUI:function(serverAccount,loadSecondary){var serverUI=this._main.getUIObject("server");serverUI.load(serverAccount);var id="server";if(loadSecondary)id+=(new Date).valueOf();var data=this._addRow(id,serverUI.el);data.serverUI=serverUI;if(this._elExpand&&
this._elExpand.nextSibling)this.el.insertBefore(data.el,this._elExpand.nextSibling);else this.el.appendChild(data.el)}});
