var boxNews=giUIObject.extend({el:null,_elBlogEntries:null,_elTwitterDate:null,_blogRss:null,_twitterRss:null,_refreshInterval:null,_eventsContainer:null,_isInitiated:false,connect:function(main){giLogger.log("st","boxNews.connect",main?main.pageId:giLogger.UNKNOWN_PAGE_ID);this.base(main);this._eventsContainer=new giEventsContainer(this);var doc=main.gmail.canvasDocument;this.el=doc.createElement("DIV");this.el.className="gtdi-news";var elBlog=doc.createElement("DIV");elBlog.className="gtdi-news-blog";
this.el.appendChild(elBlog);var elBlogTitle=doc.createElement("A");elBlogTitle.className="gtdi-news-blog-title";elBlogTitle.href="http://blog.gtdinbox.com";elBlogTitle.innerHTML=giI18N.getString("News.blog.title");elBlog.appendChild(elBlogTitle);this._elBlogEntries=doc.createElement("DIV");this._elBlogEntries.className="gtdi-news-blog-entries";this._elBlogEntries.innerHTML="<img src='chrome://gtdinbox/skin/indicator_medium.gif'/>";elBlog.appendChild(this._elBlogEntries);var elSubscribe=doc.createElement("A");
elSubscribe.className="gtdi-news-blog-subscribe";elSubscribe.href="http://feedburner.google.com/fb/a/mailverify?uri=GtdinboxBlog&email="+this._main.gmail.environment.getAccount();elSubscribe.setAttribute("target","_blank");elSubscribe.innerHTML=giI18N.getString("News.blog.subscribe");elBlog.appendChild(elSubscribe);var elTwitter=doc.createElement("DIV");elTwitter.className="gtdi-news-twitter";this.el.appendChild(elTwitter);var elTwitterTitle=doc.createElement("A");elTwitterTitle.className="gtdi-news-twitter-title";
elTwitterTitle.href="http://www.twitter.com/gtdinbox";elTwitterTitle.innerHTML="<img src='http://www.twitter.com/favicon.ico'/> "+giI18N.getString("News.twitter.title")+":";elTwitter.appendChild(elTwitterTitle);var elTwitterDate=doc.createElement("DIV");elTwitterDate.className="gtdi-news-twitter-date-container";elTwitterDate.innerHTML=giI18N.getString("News.twitter.lastUpdate")+" ";elTwitter.appendChild(elTwitterDate);this._elTwitterDate=doc.createElement("SPAN");this._elTwitterDate.className="gtdi-news-twitter-date";
elTwitterDate.appendChild(this._elTwitterDate);this._eventsContainer.observe(this.el,"mousedown",this._click,false);this._blogRss=new giRss;this._blogRss.addEventListener(giRss.LOADED,this._blogLoaded,this);this._twitterRss=new giRss;this._twitterRss.addEventListener(giRss.LOADED,this._twitterLoaded,this);var me=this;setTimeout(function(){me.refresh()},1E3*15);this._refreshInterval=setInterval(function(){me.refresh()},2*60*60*1E3)},disconnect:function(){if(this.el&&this.el.parentNode)this.el.parentNode.removeChild(this.el);
for(p in this)if(this.hasOwnProperty(p)&&this[p].nodeName&&this[p].parentNode)this[p]=null;this._blogRss.unload();this._blogRss=null;this._twitterRss.unload();this._twitterRss=null;clearInterval(this._refreshInterval);this._eventsContainer.reset();this._eventsContainer=null;this.base()},refresh:function(){this._isInitiated=true;this._blogRss.load("http://feeds.feedburner.com/GTDInboxBlog");this._twitterRss.load("http://twitter.com/statuses/user_timeline/14171757.rss")},isInitiated:function(){return this._isInitiated},
_blogLoaded:function(evt){if(!this._main.prefs){giLogger.logConcern("Could not find this._main.prefs (null).","boxNews._blogLoaded",this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID);return}this._elBlogEntries.innerHTML="";var tsLastUpdate=this._main.prefs.getPref("news.lastview")||0;var newItems=0;var doc=this._main.gmail.canvasDocument;var rss=evt.target;for(var i=0;i<3&&i<rss.entries.length;i++){var elLi=doc.createElement("DIV");elLi.className="gtdi-news-blog-lineitem";elLi.innerHTML='<a href="'+
rss.entries[i].link+"\" target='_blank'>"+rss.entries[i].title+"</a>";elLi.title=giUtil.decodeEntities(rss.entries[i].contentSnippet);this._elBlogEntries.appendChild(elLi);var d=new Date(rss.entries[i].publishedDate);if(d.valueOf()>tsLastUpdate){giUIObject.addClassName(elLi,"gtdi-news-blog-lineitem-new");newItems++}}this.dispatchEvent({name:boxNews.BLOG_UPDATED,newItems:newItems})},_twitterLoaded:function(evt){var rss=evt.target;var dateTokens=rss.entries[0].publishedDate.split(" ");dateTokens.length=
3;this._elTwitterDate.innerHTML=dateTokens.join(" ")},_click:function(evt){try{var el=evt.target;if(el.nodeName=="A"&&(el.className=="gtdi-news-blog-title"||el.parentNode.className.indexOf("gtdi-news-blog-lineitem")>-1))this.unmarkNew()}catch(e){giLogger.warn(e,"boxNews._click",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}},unmarkNew:function(){var ts=(new Date).valueOf();this._main.prefs.setPref("news.lastview",ts);var results=this.el.ownerDocument.evaluate(".//*[contains(@class, 'gtdi-news-blog-lineitem-new')]",
this.el,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null);for(var i=0;i<results.snapshotLength;i++)giUIObject.removeClassName(results.snapshotItem(i),"gtdi-news-blog-lineitem-new");this.dispatchEvent({name:boxNews.BLOG_UPDATED,newItems:0})}},{BLOG_UPDATED:"blog_updated"});boxNews.implement(giEventDispatcher);
