var gtdSearchBuilderTypeList=gtdSearchBuilder.extend({treeList:null,id:null,_type:null,_subType:null,_pinned:null,connect:function(main){this.base(main);this._eventsContainer=new giEventsContainer(this);this._eventsContainer.observe(this.el,"click",this._click,false);giUIObject.addClassName(this.el,"gtdi-searchbuilder-typelist")},disconnect:function(){this.treeList.disconnect();this.treeList=null;this._eventsContainer.reset();this._eventsContainer=null;this.base()},load:function(parent,type,subType,
id,pinned){try{this.base(parent);if(this.treeList){this.treeList.disconnect();this.treeList=null}this.id=id;this._type=type;this._subType=subType;this._pinned=pinned;if(pinned){var pinnedItems=this._main.prefs.getPref("components.navigation.reviews.pinned."+this.id)||[];this.treeList=this._main.getUIObject("treeList");var removePinned=[];switch(this._type){case gtdBrowser.TYPES.LABEL:this.treeList.init(gtdBrowser.TYPES.LABEL,this._subType);var prefix=this._main.prefs.getPref("labels.types."+this._subType+
".prefix");for(var i=0;i<pinnedItems.length;i++)if(this._main.labelsData.hasLabel(pinnedItems[i],true))if(!prefix||gtdLabelsData.testPrefix(pinnedItems[i],prefix))this.treeList.addItem(pinnedItems[i],true);else removePinned.push(pinnedItems[i]);else removePinned.push(pinnedItems[i]);break;case gtdBrowser.TYPES.STORED_SEARCH:this.treeList.init(gtdBrowser.TYPES.STORED_SEARCH);for(var i=0;i<pinnedItems.length;i++)if(this._main.storedSearch.hasSearch(pinnedItems[i]))this.treeList.addItem(pinnedItems[i],
true);else removePinned.push(pinnedItems[i]);break}if(removePinned.length>-1){for(var i=0;i<removePinned.length;i++)if((idx=pinnedItems.indexOf(removePinned[i]))>-1)pinnedItems.splice(idx,1);this._main.prefs.setPref("components.navigation.reviews.pinned."+this.id,pinnedItems)}this.el.appendChild(this.treeList.el)}else{var elTitle=this._main.gmail.canvasDocument.createElement("DIV");elTitle.className="gtdi-searchbuilder-typelist-title";this.el.appendChild(elTitle);switch(this._type){case gtdBrowser.TYPES.LABEL:elTitle.innerHTML=
giI18N.getString("Labels.Types."+this._subType,this._subType);this.treeList=this._main.labelsData.getLabelsEl(this._subType);this.el.appendChild(this.treeList.el);break;case gtdBrowser.TYPES.STORED_SEARCH:elTitle.innerHTML=giI18N.getString("StoredSearch.Types."+this._subType,this._subType);this.treeList=this._main.getUIObject("treeList");this.treeList.init(gtdBrowser.TYPES.STORED_SEARCH,this._subType);searchIds=this._main.storedSearch.getSearchesByType(this._subType);for(var i=0;i<searchIds.length;i++)this.treeList.addItem(searchIds[i]);
this.el.appendChild(this.treeList.el);break}}this._adornTreeList(pinned);this.refreshItemCounts()}catch(e){giLogger.warn(e,"gtdSearchBuilderTypeList.load",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}},reload:function(){this.load(this.parent,this._type,this._subType,this.id,this._pinned)},_adornTreeList:function(exclPin){var pinnedItems=this._main.prefs.getPref("components.navigation.reviews.pinned."+this.id)||[];var doc=this._main.gmail.canvasDocument;var result=doc.evaluate(".//DIV[contains(@class,'gtdi-treelist-item')]",
this.el,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null);for(var i=0;i<result.snapshotLength;i++){var elItem=result.snapshotItem(i);var elItemName=elItem.getElementsByClassName("gtdi-treelist-item-name")[0];elItemName.title=this._pinned?giI18N.getString("SearchBuilder.TypeList.item.pinnedTooltip"):giI18N.getString("SearchBuilder.item.tooltip");var item=elItem.getAttribute("gtdi-item");if(!exclPin)if(elItem.getElementsByClassName("gtdi-box-row-pincontainer").length==0){var elSpan=doc.createElement("SPAN");
elSpan.className="gtdi-box-row-pincontainer";var elImg=doc.createElement("IMG");elImg.className="gtdi-box-row-pin";elImg.src=giUrl.getURL("skin/gtd/i/gtdi-pin-off.png");elImg.title=giI18N.getString("Box.gtdtypes.pin").replace("%1",item);elSpan.appendChild(elImg);elItem.insertBefore(elSpan,elItem.firstChild);if(pinnedItems.indexOf(item)>-1){giUIObject.addClassName(elImg,"gtdi-active");elImg.src=giUrl.getURL("skin/gtd/i/gtdi-pin-on.png")}else{giUIObject.removeClassName(elImg,"gtdi-active");elImg.src=
giUrl.getURL("skin/gtd/i/gtdi-pin-off.png")}}if(1==2)if(elItem.getElementsByClassName("gtdi-box-row-popupcontainer").length==0){var elSpan=doc.createElement("SPAN");elSpan.className="gtdi-box-row-popupcontainer";var elImg=doc.createElement("IMG");elImg.className="gtdi-box-row-popup";elImg.src=giUrl.getURL("skin/gtd/i/gtdi-popup.png");elSpan.title=giI18N.getString("Box.popup").replace("%1",item);elSpan.appendChild(elImg);elItem.appendChild(elSpan)}if(elItem.getElementsByClassName("gtdi-box-row-extendcontainer").length==
0){var elSpan=doc.createElement("SPAN");elSpan.className="gtdi-box-row-extendcontainer";var elImg=doc.createElement("IMG");elImg.className="gtdi-box-row-extend";elImg.src=giUrl.getURL("skin/gtd/i/gtdi-extend.png");elSpan.title=giI18N.getString("Box.filterextend").replace("%1",item);elSpan.appendChild(elImg);elItem.appendChild(elSpan)}}},refreshItemCounts:function(){try{var doc=this._main.gmail.canvasDocument;var result=doc.evaluate(".//div[@gtdi-item]",this.el,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,
null);for(var i=0;i<result.snapshotLength;i++){var elItem=result.snapshotItem(i);var elItemName=elItem.getElementsByClassName("gtdi-treelist-item-name")[0];var item=elItem.getAttribute("gtdi-item");if(this._type==gtdBrowser.TYPES.LABEL){var childLabels=this._main.labelsData.getChildLabels(item);if(childLabels.length>0){var labelCountSearch=[];labelCountSearch.push(glSearch.l(item));for(var j=0;j<childLabels.length;j++)labelCountSearch.push(glSearch.l(childLabels[j]));var count=this._main.statusThreadsContainer.getCountBySearch(labelCountSearch.join(" OR "))}else var count=
this._main.statusThreadsContainer.getLabelCount(item)}else if(this._type==gtdBrowser.TYPES.STORED_SEARCH){var search=this._main.storedSearch.getSearchText(item);var count=this._main.statusThreadsContainer.getCountBySearch(search)}else;if(count){elItemName.innerHTML=elItemName.innerHTML.replace(/(.+?)(\s\(\d+\))?$/,"$1"+" ("+count+")");giUIObject.addClassName(elItem,"gtdi-box-popout-label-has_statuses")}else{elItemName.innerHTML=elItemName.innerHTML.replace(/(.+?)(\s\(\d+\))?$/,"$1");giUIObject.removeClassName(elItem,
"gtdi-box-popout-label-has_statuses")}}}catch(e){giLogger.warn(e,"gtdSearchBuilderTypeList.refreshItemCounts",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}},_getSearchInner:function(){return this.base()},_createChild:function(){return this._main.getUIObject("searchBuilderMenu")},getLabelType:function(){return this._subType},_click:function(evt){try{var el=evt.target;while(el.parentNode){if(el.className.indexOf("gtdi-treelist-expander")>-1)return;else if(el.className.indexOf("gtdi-box-row-pincontainer")>
-1){giLogger.log("#IDPROBLEM(to-remove) click: toggle pin","gtdSearchBuilderTypeList._click",this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID);var pinnedItems=this._main.prefs.getPref("components.navigation.reviews.pinned."+this.id)||[];var elRow=el;while(elRow.parentNode&&elRow.getAttribute&&!elRow.getAttribute("gtdi-item"))elRow=elRow.parentNode;if(!elRow.parentNode||!elRow.getAttribute)return;var item=elRow.getAttribute("gtdi-item");if(el.nodeName!="IMG")el=el.getElementsByTagName("IMG")[0];
if(giUIObject.hasClassName(el,"gtdi-active")){var idx=pinnedItems.indexOf(item);if(idx>-1)pinnedItems.splice(idx,1);el.src=giUrl.getURL("skin/gtd/i/gtdi-pin-off.png");giUIObject.removeClassName(el,"gtdi-active")}else{if(pinnedItems.indexOf(item)==-1)pinnedItems.push(item);el.src=giUrl.getURL("skin/gtd/i/gtdi-pin-on.png");giUIObject.addClassName(el,"gtdi-active")}this._main.prefs.setPref("components.navigation.reviews.pinned."+this.id,pinnedItems,true);this.dispatchEvent({name:gtdSearchBuilderTypeList.TOGGLE_PIN});
return}else if(el.className.indexOf("gtdi-box-row-extendcontainer")>-1){giLogger.log("#IDPROBLEM(to-remove) click: extend / show filter","gtdSearchBuilderTypeList._click",this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID);while(el.parentNode&&el.getAttribute&&!el.getAttribute("gtdi-item"))el=el.parentNode;if(!el.parentNode||!el.getAttribute)return;var item=el.getAttribute("gtdi-item");this._setCurrent(this._type,item,el);this.openChild();return}else if(el.className.indexOf("gtdi-box-row-popupcontainer")>
-1){while(el.parentNode&&el.getAttribute&&!el.getAttribute("gtdi-item"))el=el.parentNode;if(!el.parentNode||!el.getAttribute)return;var labelName=el.getAttribute("gtdi-item");if(labelName){var type=this._main.labelsData.getLabelType(labelName).toUpperCase();var popup=this._main.getUIObject("browserPopup");popup.load(gtdBrowser.createBrowser(this._main,labelName));if(!evt.altKey)this.hide(true)}}else if(el.getAttribute("gtdi-item")){giLogger.log("#IDPROBLEM(to-remove) click: item","gtdSearchBuilderTypeList._click",
this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID);var item=el.getAttribute("gtdi-item");this._setCurrent(this._type,item,el);if(!this.parent&&this._type==gtdBrowser.TYPES.LABEL){var childLabels=this._main.labelsData.getChildLabels(this._selectedItem);if(childLabels.length==0)this._main.gmail.page.location("hash","label/"+encodeURIComponent(item));else{var searchStr=this.getSearch();this._main.gmail.page.location("hash","search/"+encodeURIComponent(searchStr))}}else{var searchStr=this.getSearch();
this._main.gmail.page.location("hash","search/"+encodeURIComponent(searchStr))}if(!evt.altKey)this.hide(true)}el=el.parentNode}}catch(e){giLogger.warn(e,"gtdSearchBuilderTypeList._click",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}}},{TOGGLE_PIN:"toggle_pin"});
