var gtdSearchBuilderLabelsTree=gtdSearchBuilder.extend({elLabelsTree:null,labelsTree:null,_labelType:null,disconnect:function(){this.elLabelsTree=null;this.labelsTree.disconnect();this.labelsTree=null;this._eventsContainer.reset();this._eventsContainer=null;this.base()},load:function(parent,labelType){try{this.base(parent);var doc=this._main.gmail.canvasDocument;if(labelType){this._labelType=labelType;this._eventsContainer=new giEventsContainer(this);if(this._labelType!="statuses"){var elRecent=doc.createElement("DIV");
elRecent.className="gtdi-box-popout-label-recent";elRecent.style.display="none";this.el.appendChild(elRecent)}this.labelsTree=this._main.labelsData.getLabelsEl(this._labelType);this.elLabelsTree=this.labelsTree.el;this.el.appendChild(this.elLabelsTree);var result=doc.evaluate(".//DIV[contains(@class,'gtdi-labeldom-label')]",this.el,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null);for(var i=0;i<result.snapshotLength;i++){var elLabel=result.snapshotItem(i);if(!giUIObject.hasClassName(elLabel,"gtdi-labeldom-placeholder")){elLabel.title=
giI18N.getString("Box.label").replace("%1",elLabel.getAttribute("gtdLabelName"));var elImg=doc.createElement("IMG");elImg.className="gtdi-box-row-popup";elImg.src=giUrl.getURL("skin/gtd/popout.png");elImg.title=giI18N.getString("Box.popup").replace("%1",elLabel.getAttribute("gtdLabelName"));elLabel.appendChild(elImg)}}this._eventsContainer.observe(this.el,"click",this._click,false)}if(this._labelType!="statuses"){var elRecent=doc.evaluate(".//*[@class='gtdi-box-popout-label-recent']",this.el,null,
XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue;var recent=this._main.recent.getLabels(this._labelType);if(recent.length==0)elRecent.style.display="none";else{if(recent.length>3)recent.length=3;recent.sort();elRecent.style.display="";elRecent.innerHTML="";var elRecentTitle=doc.createElement("DIV");elRecentTitle.innerHTML=giI18N.getString("Labelling.dropdown.recent");elRecentTitle.className="gtdi-box-popout-label-recent-title";elRecent.appendChild(elRecentTitle);for(var i=0;i<recent.length;i++){var elRecentItem=
doc.createElement("DIV");elRecentItem.className="gtdi-box-popout-label-recent-item";elRecentItem.innerHTML=recent[i][0];elRecentItem.innerHTML+="<img src='"+giUrl.getURL("skin/gtd/popout.png")+"' class='gtdi-box-row-popup' title='"+giI18N.getString("Box.popup").replace("%1",recent[i][0])+"' />";elRecentItem.title=giI18N.getString("Box.label").replace("%1",recent[i][0]);elRecentItem.setAttribute("gtdLabelName",recent[i][0]);elRecent.appendChild(elRecentItem)}}}var result=doc.evaluate(".//div[@gtdLabelName]",
this.el,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null);for(var i=0;i<result.snapshotLength;i++){var elLabel=result.snapshotItem(i);var count=this._main.statusThreadsContainer.getLabelCount(elLabel.getAttribute("gtdLabelName"));if(count){elLabel.innerHTML=elLabel.innerHTML.replace(/(.+?)(\s\(\d+\))?$/,"$1"+" ("+count+")");var hierarchy=elLabel.getAttribute("gtdLabelName").split("/");var parents={};var path="";for(var j=0;j<hierarchy.length;j++){if(j>0)path+="/";path+=hierarchy[j];parents[path]=
true}while(elLabel){if(!parents[elLabel.getAttribute("gtdLabelName")]&&elLabel.getAttribute("gtdi-depth")==0)break;if(parents[elLabel.getAttribute("gtdLabelName")])giUIObject.addClassName(elLabel,"gtdi-box-popout-label-has_statuses");elLabel=elLabel.previousSibling}}else{elLabel.innerHTML=elLabel.innerHTML.replace(/(.+?)(\s\(\d+\))?$/,"$1");giUIObject.removeClassName(elLabel,"gtdi-box-popout-label-has_statuses")}}}catch(e){giLogger.warn(e,"gtdSearchBuilderLabelsTree.load",null,this._main?this._main.pageId:
giLogger.UNKNOWN_PAGE_ID)}},_getSearchInner:function(){return new glSearchConditions(glSearch.l(this.currentItem))},getLabelType:function(){return this._labelType},_click:function(evt){try{var el=evt.target;if(giUIObject.hasClassName(el,"gtdi-labeldom-placeholder")||giUIObject.hasClassName(el.parentNode,"gtdi-labeldom-placeholder"))return;if(el.className.indexOf("gtdi-labeldom-expander")>-1);else if(el.className.indexOf("gtdi-box-row-extend")>-1){while(el.parentNode&&el.getAttribute&&!el.getAttribute("gtdLabelName"))el=
el.parentNode;if(!el.parentNode||!el.getAttribute)return;var labelName=el.getAttribute("gtdLabelName");this._setCurrent(labelName,el);this.openChild();return}else if(el.className.indexOf("gtdi-box-row-popup")>-1){while(el.parentNode&&el.getAttribute&&!el.getAttribute("gtdLabelName"))el=el.parentNode;if(!el.parentNode||!el.getAttribute)return;var labelName=el.getAttribute("gtdLabelName");if(labelName){var type=this._main.labelsData.getLabelType(labelName).toUpperCase();var popup=this._main.getUIObject("browserPopup");
popup.load(gtdBrowser.createBrowser(this._main,labelName));this.hide(true)}}else if(el.className=="gtdi-labeldom-label-leaf"){var labelName=el.parentNode.getAttribute("gtdLabelName");this._setCurrent(labelName,el.parentNode);var searchStr=this.getSearch().toString();if(!evt.shiftKey){var statusData=this._main.labelsData.getStatusData(true);if(this._labelType!="statuses"){var statuses=this._main.labelsData.getLabelsArray("statuses",false);if(statuses.length>0)searchStr+=" (";for(var i=0;i<statuses.length;i++)if(statusData.reverseLookup[statuses[i]]!=
"finished"){if(i>0)searchStr+=" OR ";searchStr+=glSearch.l(statuses[i])}if(statuses.length>0)searchStr+=")"}if(this._main.labelsData.hasLabel(statusData.finished))searchStr+=" -"+glSearch.l(statusData.finished)}this._main.gmail.page.location("hash","search/"+encodeURIComponent(searchStr));this.hide(true)}else{var labelName=el.getAttribute("gtdLabelName");this._setCurrent(labelName,el);var searchStr=this.getSearch().toString();if(!evt.shiftKey){var statusData=this._main.labelsData.getStatusData(true);
if(this._labelType!="statuses"){var statuses=this._main.labelsData.getLabelsArray("statuses",false);if(statuses.length>0)searchStr+=" (";for(var i=0;i<statuses.length;i++)if(statusData.reverseLookup[statuses[i]]!="finished"){if(i>0)searchStr+=" OR ";searchStr+=glSearch.l(statuses[i])}if(statuses.length>0)searchStr+=")"}if(this._main.labelsData.hasLabel(statusData.finished))searchStr+=" -"+glSearch.l(statusData.finished)}this._main.gmail.page.location("hash","search/"+encodeURIComponent(searchStr));
this.hide(true)}}catch(e){giLogger.warn(e,"gtdSearchBuilderLabelsTree._click",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}}});
