var gtdSearchBuilderMenu=gtdSearchBuilder.extend({_sections:null,connect:function(main){this.base(main);this._eventsContainer=new giEventsContainer(this);this._eventsContainer.observe(this.el,"mousedown",this._click,false);giUIObject.addClassName(this.el,"gtdi-searchbuilder-menu")},disconnect:function(){if(this._sections)for(sid in this._sections)if(this._sections[sid].treeList){this._sections[sid].treeList.disconnect();this._sections[sid].treeList=null}this._eventsContainer.reset();this._eventsContainer=
null;this.base()},load:function(parent){this.base(parent);giLogger.log("st","gtdSearchBuilderMenu.load",this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID);if(this._sections)for(sid in this._sections){this._sections[sid].treeList.disconnect();this._sections[sid].treeList=null}this._sections={};var doc=this._main.gmail.canvasDocument;if(this._main.serverAccount.getAccountType()==giServerAccount.TYPES.PLUS){var section=this._addSection(gtdBrowser.TYPES.STORED_SEARCH+"scheduled",giI18N.getString("StoredSearch.Types.scheduled"));
section.treeList=this._main.getUIObject("treeList");section.treeList.init(gtdBrowser.TYPES.STORED_SEARCH,"scheduled");searchIds=this._main.storedSearch.getSearchesByType("scheduled");for(var i=0;i<searchIds.length;i++)section.treeList.addItem(searchIds[i]);section.elContent.appendChild(section.treeList.el)}var typeSettings=this._main.prefs.getPref("labels.types");for(t in typeSettings)if(!typeSettings[t].isHidden)if(this._main.labelsData.getLabelsArray(t).length>0){var section=this._addSection(gtdBrowser.TYPES.LABEL+
t,giI18N.getString("Labels.Types."+t,t));section.treeList=this._main.labelsData.getLabelsEl(t);section.elContent.appendChild(section.treeList.el)}section=this._addSection("search_within",giI18N.getString("SearchBuilder.Menu.search_within"));section.elContent.innerHTML="<div class='gtdi-searchbuilder-menu-search_within'><input type='text' /><button class='gtdi-searchbuilder-menu-search_within.search'>"+giI18N.getString("SearchBuilder.Menu.search_within.search")+"</button></div>";this._expandSection(section.id,
this._main.prefs.getPref("expanded_sections.searchBuilder_"+section.id)||false,true);this._adornTreeList();this.refreshCounts()},_addSection:function(sid,name){var doc=this._main.gmail.canvasDocument;var elSection=doc.createElement("DIV");elSection.className="gtdi-searchbuilder-menu-section";elSection.setAttribute("gtdi-searchbuilder-menu-section-id",sid);var elTitle=doc.createElement("DIV");elTitle.className="gtdi-searchbuilder-menu-section-title";elTitle.innerHTML=name;elSection.appendChild(elTitle);
var elContent=doc.createElement("DIV");elContent.className="gtdi-searchbuilder-menu-section-content";elContent.style.display="none";elSection.appendChild(elContent);this.el.appendChild(elSection);var section={id:sid};section.el=elSection;section.elTitle=elTitle;section.elContent=elContent;this._sections[sid]=section;return section},_adornTreeList:function(){var doc=this._main.gmail.canvasDocument;var result=doc.evaluate(".//DIV[contains(@class,'gtdi-treelist-item')]",this.el,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,
null);for(var i=0;i<result.snapshotLength;i++){var elItem=result.snapshotItem(i);var elItemName=elItem.getElementsByClassName("gtdi-treelist-item-name")[0];elItemName.title=giI18N.getString("SearchBuilder.item.tooltip");var item=elItem.getAttribute("gtdi-item");if(1==2)if(elItem.getElementsByClassName("gtdi-box-row-popupcontainer").length==0){var elSpan=doc.createElement("SPAN");elSpan.className="gtdi-box-row-popupcontainer";var elImg=doc.createElement("IMG");elImg.className="gtdi-box-row-popup";
elImg.src=giUrl.getURL("skin/gtd/i/gtdi-popup.png");elSpan.title=giI18N.getString("Box.popup").replace("%1",item);elSpan.appendChild(elImg);elItem.appendChild(elSpan)}if(elItem.getElementsByClassName("gtdi-box-row-extendcontainer").length==0){var elSpan=doc.createElement("SPAN");elSpan.className="gtdi-box-row-extendcontainer";var elImg=doc.createElement("IMG");elImg.className="gtdi-box-row-extend";elImg.src=giUrl.getURL("skin/gtd/i/gtdi-extend.png");elSpan.title=giI18N.getString("Box.filterextend").replace("%1",
item);elSpan.appendChild(elImg);elItem.appendChild(elSpan)}}},refreshCounts:function(openCloseSection){var threads=null;if(this.parent){threads=[];var search=glSearchConditions.createFromSearchString(this.parent.getSearch());var statusThreads=this._main.statusThreadsContainer.threads;for(var i=0;i<statusThreads.length;i++)if(search.matchThread(statusThreads[i]))threads.push(statusThreads[i])}for(sid in this._sections){giLogger.log("#IDPROBLEM(to-remove) section from this._sections, id: "+sid+", typeof: "+
typeof this._sections[sid],"gtdSearchBuilderMenu.refreshCounts",this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID);var section=this._sections[sid];if(section.treeList){var sectionCount=0;var result=this._main.gmail.canvasDocument.evaluate(".//div[@gtdi-item]",section.treeList.el,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null);for(var i=0;i<result.snapshotLength;i++){var elItem=result.snapshotItem(i);var elItemName=elItem.getElementsByClassName("gtdi-treelist-item-name")[0];var type=elItem.getAttribute("gtdi-type");
var item=elItem.getAttribute("gtdi-item");if(type==gtdBrowser.TYPES.LABEL){var childLabels=this._main.labelsData.getChildLabels(item);if(childLabels.length>0){var labelCountSearch=[];labelCountSearch.push(glSearch.l(item));for(var j=0;j<childLabels.length;j++)labelCountSearch.push(glSearch.l(childLabels[j]));var count=this._main.statusThreadsContainer.getCountBySearch(labelCountSearch.join(" OR "),threads)}else var count=this._main.statusThreadsContainer.getCountBySearch(glSearch.l(item),threads)}else if(type==
gtdBrowser.TYPES.STORED_SEARCH){var search=this._main.storedSearch.getSearchText(item);var count=this._main.statusThreadsContainer.getCountBySearch(search,threads)}var alreadySeen=false;if(count>0){var ancestor=this.parent;while(ancestor){if(item==ancestor.getCurrentItem()){alreadySeen=true;break}ancestor=ancestor.parent}}if(count&&!alreadySeen){sectionCount+=count;elItemName.innerHTML=elItemName.innerHTML.replace(/(.+?)(\s\(\d+\))?$/,"$1"+" ("+count+")");giUIObject.addClassName(elItem,"gtdi-box-popout-label-has_statuses")}else{elItemName.innerHTML=
elItemName.innerHTML.replace(/(.+?)(\s\(\d+\))?$/,"$1");giUIObject.removeClassName(elItem,"gtdi-box-popout-label-has_statuses")}}if(sectionCount){section.elTitle.innerHTML=section.elTitle.innerHTML.replace(/(.+?)(\s\(\d+\))?$/,"$1"+" ("+sectionCount+")");if(openCloseSection)this._expandSection(sid,true,true)}else{section.elTitle.innerHTML=section.elTitle.innerHTML.replace(/(.+?)(\s\(\d+\))?$/,"$1");if(openCloseSection)this._expandSection(sid,false,true)}}else if(openCloseSection)this._expandSection(sid,
this._main.prefs.getPref("expanded_sections.searchBuilder_"+sid)||false,true)}},_expandSection:function(sid,expanded,inhibitSavePref){giLogger.log("st (id: "+sid+"), expanded: "+expanded,"gtdSearchBuilderMenu._expandSection",this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID);var section=this._sections[sid];if(typeof expanded=="undefined")return giUIObject.hasClassName(section.elTitle,"gtdi-expanded");if(expanded){section.elContent.style.display="";giUIObject.addClassName(section.elTitle,"gtdi-expanded")}else{section.elContent.style.display=
"none";giUIObject.removeClassName(section.elTitle,"gtdi-expanded")}if(!inhibitSavePref)this._main.prefs.setPref("expanded_sections.searchBuilder_"+sid,expanded);return expanded},_getSearchInner:function(){return this.base()},_createChild:function(){return this._main.getUIObject("searchBuilderMenu")},_click:function(evt){try{var el=evt.target;while(el.parentNode){if(el.className.indexOf("gtdi-treelist-expander")>-1)return;else if(giUIObject.hasClassName(el,"gtdi-searchbuilder-menu-section-title")){var sid=
el.parentNode.getAttribute("gtdi-searchbuilder-menu-section-id");this._expandSection(sid,!this._expandSection(sid))}else if(el.getAttribute("gtdi-type")&&el.getAttribute("gtdi-item")){this._setCurrent(el.getAttribute("gtdi-type"),el.getAttribute("gtdi-item"),el);var searchStr=this.getSearch();this._main.gmail.page.location("hash","search/"+encodeURIComponent(searchStr));if(!evt.altKey)this.hide(true);return}else if(el.className.indexOf("gtdi-box-row-extendcontainer")>-1){while(el.parentNode&&el.getAttribute&&
!el.getAttribute("gtdi-item"))el=el.parentNode;if(!el.parentNode||!el.getAttribute)return;this._setCurrent(el.getAttribute("gtdi-type"),el.getAttribute("gtdi-item"),el);this.openChild();return}else if(el.className.indexOf("gtdi-box-row-popupcontainer")>-1){while(el.parentNode&&el.getAttribute&&!el.getAttribute("gtdi-item"))el=el.parentNode;if(!el.parentNode||!el.getAttribute)return;this._setCurrent(el.getAttribute("gtdi-type"),el.getAttribute("gtdi-item"),el);var searchStr=this.getSearch();var ancestor=
this;while(ancestor.parent)ancestor=ancestor.parent;var browser=gtdBrowser.createBrowser(this._main,searchStr,gtdBrowser.TYPES.SEARCH);var popup=this._main.getUIObject("browserPopup");popup.load(browser);if(!evt.altKey)this.hide(true)}else if(el.className.indexOf("gtdi-searchbuilder-menu-search_within.search")>-1){var elInput=el.parentNode.getElementsByTagName("INPUT")[0];this._setCurrent(gtdBrowser.TYPES.SEARCH,elInput.value);var searchStr=this.getSearch();this._main.gmail.page.location("hash","search/"+
encodeURIComponent(searchStr));this.hide(true)}el=el.parentNode}}catch(e){giLogger.warn(e,"gtdSearchBuilderMenu._click",null,this._main?this._main.pageId:giLogger.UNKNOWN_PAGE_ID)}}});
